"""
扩展城市知识库 V4 - 华中/西南/东北/其他地区城市数据
"""

EXTENDED_CITY_DB = {
    # ==================== 华中地区 ====================
    "长沙": {
        "province": "湖南",
        "hotels": [
            {"name": "长沙万达文华酒店", "type": "豪华型", "price_per_night": 980, "rating": 4.8, "facilities": ["WiFi", "泳池", "SPA"], "address": "开福区中山路"},
            {"name": "长沙岳麓山民宿", "type": "特色民宿", "price_per_night": 380, "rating": 4.6, "facilities": ["WiFi", "早餐"], "address": "岳麓区麓山路"},
            {"name": "长沙五一广场青旅", "type": "经济型", "price_per_night": 79, "rating": 4.3, "facilities": ["WiFi"], "address": "芙蓉区五一广场"},
        ],
        "restaurants": [
            {"name": "茶颜悦色", "cuisine": "新式茶饮", "avg_price": 18, "rating": 4.8, "specialties": ["幽兰拿铁", "声声乌龙", "栀晓"]},
            {"name": "黑色经典臭豆腐", "cuisine": "长沙小吃", "avg_price": 15, "rating": 4.7, "specialties": ["臭豆腐", "糖油粑粑", "口味虾"]},
            {"name": "文和友老长沙龙虾馆", "cuisine": "湘菜", "avg_price": 108, "rating": 4.7, "specialties": ["口味虾", "臭豆腐", "糖油粑粑"]},
            {"name": "费大厨辣椒炒肉", "cuisine": "湘菜", "avg_price": 78, "rating": 4.8, "specialties": ["辣椒炒肉", "剁椒鱼头", "外婆菜"]},
            {"name": "炊烟时代", "cuisine": "湘菜", "avg_price": 88, "rating": 4.7, "specialties": ["小炒黄牛肉", "剁椒鱼头", "辣椒炒肉"]},
            {"name": "火宫殿", "cuisine": "长沙小吃", "avg_price": 45, "rating": 4.6, "specialties": ["臭豆腐", "龙脂猪血", "姊妹团子"]},
            {"name": "茶颜悦色奶茶", "cuisine": "茶饮", "avg_price": 18, "rating": 4.7, "specialties": ["桂花弄", "蔓越阑珊", "人间烟火"]},
            {"name": "文和友大香肠", "cuisine": "长沙小吃", "avg_price": 15, "rating": 4.5, "specialties": ["大香肠", "臭豆腐", "糖油粑粑"]},
        ],
        "attractions": [
            {"name": "橘子洲头", "type": "自然风光", "price": 0, "rating": 4.8, "description": "毛主席青年雕像所在地"},
            {"name": "岳麓山", "type": "自然风光", "price": 0, "rating": 4.7, "description": "千年学府岳麓书院"},
            {"name": "岳麓书院", "type": "历史文化", "price": 50, "rating": 4.8, "description": "四大书院之首"},
            {"name": "湖南省博物馆", "type": "博物馆", "price": 0, "rating": 4.7, "description": "马王堆汉墓文物"},
            {"name": "太平老街", "type": "历史街区", "price": 0, "rating": 4.6, "description": "长沙最古老街道"},
            {"name": "五一广场", "type": "购物商圈", "price": 0, "rating": 4.6, "description": "长沙商业中心"},
            {"name": "长沙世界之窗", "type": "主题公园", "price": 150, "rating": 4.5, "description": "微缩世界景观"},
            {"name": "长沙海底世界", "type": "主题公园", "price": 150, "rating": 4.5, "description": "海洋生物展览"},
            {"name": "杜甫江阁", "type": "历史文化", "price": 0, "rating": 4.5, "description": "杜甫纪念建筑"},
            {"name": "长沙摩天轮", "type": "城市地标", "price": 80, "rating": 4.4, "description": "城市观景台"},
            {"name": "梅溪湖大剧院", "type": "城市地标", "price": 0, "rating": 4.5, "description": "扎哈·哈迪德设计"},
            {"name": "天心阁", "type": "历史文化", "price": 32, "rating": 4.5, "description": "长沙古城标志"},
            {"name": "简牍博物馆", "type": "博物馆", "price": 0, "rating": 4.4, "description": "长沙简牍文化"},
            {"name": "靖港古镇", "type": "古镇风情", "price": 0, "rating": 4.4, "description": "千年古镇"},
            {"name": "长沙生态动物园", "type": "主题公园", "price": 100, "rating": 4.3, "description": "亲子游好去处"},
        ],
    },
    "郑州": {
        "province": "河南",
        "hotels": [
            {"name": "郑州希尔顿酒店", "type": "豪华型", "price_per_night": 880, "rating": 4.8, "facilities": ["WiFi", "泳池", "SPA"], "address": "郑东新区CBD"},
            {"name": "郑州商城遗址民宿", "type": "特色民宿", "price_per_night": 320, "rating": 4.5, "facilities": ["WiFi", "早餐"], "address": "管城回族区商城路"},
            {"name": "郑州二七广场青旅", "type": "经济型", "price_per_night": 69, "rating": 4.3, "facilities": ["WiFi"], "address": "二七区二七广场"},
        ],
        "restaurants": [
            {"name": "合记烩面", "cuisine": "河南面食", "avg_price": 35, "rating": 4.8, "specialties": ["烩面", "羊肉烩面", "牛肉烩面"]},
            {"name": "萧记三鲜烩面", "cuisine": "河南面食", "avg_price": 38, "rating": 4.7, "specialties": ["三鲜烩面", "羊肉烩面", "牛肉烩面"]},
            {"name": "郑州烤鸭总店", "cuisine": "豫菜", "avg_price": 78, "rating": 4.6, "specialties": ["烤鸭", "红烧黄河大鲤鱼", "道口烧鸡"]},
            {"name": "方中山胡辣汤", "cuisine": "河南小吃", "avg_price": 12, "rating": 4.7, "specialties": ["胡辣汤", "牛肉胡辣汤", "豆腐脑"]},
            {"name": "蔡记蒸饺", "cuisine": "河南小吃", "avg_price": 25, "rating": 4.6, "specialties": ["蒸饺", "灌汤包", "小笼包"]},
            {"name": "葛记焖饼", "cuisine": "河南小吃", "avg_price": 30, "rating": 4.5, "specialties": ["坛子肉焖饼", "红豆焖饼", "素焖饼"]},
            {"name": "阿五黄河大鲤鱼", "cuisine": "豫菜", "avg_price": 98, "rating": 4.6, "specialties": ["红烧黄河大鲤鱼", "烩面", "烧鸡"]},
            {"name": "二七广场小吃", "cuisine": "小吃", "avg_price": 20, "rating": 4.4, "specialties": ["烤串", "臭豆腐", "酸辣粉"]},
        ],
        "attractions": [
            {"name": "少林寺", "type": "佛教圣地", "price": 80, "rating": 4.7, "description": "禅宗祖庭武术圣地"},
            {"name": "河南博物院", "type": "博物馆", "price": 0, "rating": 4.8, "description": "中国八大博物馆之一"},
            {"name": "二七纪念塔", "type": "城市地标", "price": 0, "rating": 4.5, "description": "郑州城市标志"},
            {"name": "嵩山风景区", "type": "自然风光", "price": 80, "rating": 4.6, "description": "五岳之中岳"},
            {"name": "嵩阳书院", "type": "历史文化", "price": 30, "rating": 4.6, "description": "四大书院之一"},
            {"name": "中岳庙", "type": "历史文化", "price": 30, "rating": 4.5, "description": "道教圣地"},
            {"name": "郑州商城遗址", "type": "历史文化", "price": 0, "rating": 4.5, "description": "3600年商城遗址"},
            {"name": "黄河风景名胜区", "type": "自然风光", "price": 60, "rating": 4.5, "description": "黄河风光"},
            {"name": "郑州动物园", "type": "主题公园", "price": 30, "rating": 4.3, "description": "亲子游好去处"},
            {"name": "绿博园", "type": "主题公园", "price": 50, "rating": 4.4, "description": "园艺博览会"},
            {"name": "郑州海洋馆", "type": "主题公园", "price": 100, "rating": 4.4, "description": "海洋生物展览"},
            {"name": "康百万庄园", "type": "历史文化", "price": 50, "rating": 4.5, "description": "中原豪宅"},
            {"name": "杜甫故里", "type": "历史文化", "price": 40, "rating": 4.4, "description": "诗圣故里"},
            {"name": "伏羲山大峡谷", "type": "自然风光", "price": 80, "rating": 4.5, "description": "峡谷风光"},
            {"name": "郑州植物园", "type": "城市公园", "price": 0, "rating": 4.3, "description": "城市绿肺"},
        ],
    },
    "洛阳": {
        "province": "河南",
        "hotels": [
            {"name": "洛阳钼都利豪酒店", "type": "豪华型", "price_per_night": 780, "rating": 4.7, "facilities": ["WiFi", "泳池", "SPA"], "address": "洛龙区开元大道"},
            {"name": "洛阳龙门民宿", "type": "特色民宿", "price_per_night": 350, "rating": 4.6, "facilities": ["WiFi", "早餐"], "address": "洛龙区龙门大道"},
            {"name": "洛阳老城青旅", "type": "经济型", "price_per_night": 59, "rating": 4.3, "facilities": ["WiFi"], "address": "老城区西大街"},
        ],
        "restaurants": [
            {"name": "真不同洛阳水席", "cuisine": "洛阳菜", "avg_price": 128, "rating": 4.7, "specialties": ["牡丹燕菜", "连汤肉片", "蜜汁红薯"]},
            {"name": "管记水席", "cuisine": "洛阳菜", "avg_price": 98, "rating": 4.6, "specialties": ["洛阳水席", "牡丹燕菜", "焦炸丸子"]},
            {"name": "老洛阳面馆", "cuisine": "洛阳面食", "avg_price": 25, "rating": 4.6, "specialties": ["浆面条", "糊涂面", "烩面"]},
            {"name": "马杰山牛肉汤", "cuisine": "洛阳小吃", "avg_price": 18, "rating": 4.7, "specialties": ["牛肉汤", "羊肉汤", "驴肉汤"]},
            {"name": "洛阳不翻汤", "cuisine": "洛阳小吃", "avg_price": 12, "rating": 4.6, "specialties": ["不翻汤", "丸子汤", "豆腐汤"]},
            {"name": "老城十字街小吃", "cuisine": "小吃", "avg_price": 20, "rating": 4.5, "specialties": ["浆面条", "糊涂面", "烤串"]},
            {"name": "洛阳水席园", "cuisine": "洛阳菜", "avg_price": 108, "rating": 4.6, "specialties": ["洛阳水席", "牡丹燕菜", "红烧黄河大鲤鱼"]},
            {"name": "牛肉汤泡馍", "cuisine": "洛阳面食", "avg_price": 22, "rating": 4.5, "specialties": ["牛肉汤泡馍", "羊肉汤泡馍", "丸子汤"]},
        ],
        "attractions": [
            {"name": "龙门石窟", "type": "世界文化遗产", "price": 90, "rating": 4.8, "description": "中国四大石窟之一"},
            {"name": "白马寺", "type": "佛教圣地", "price": 35, "rating": 4.7, "description": "中国第一古刹"},
            {"name": "洛阳博物馆", "type": "博物馆", "price": 0, "rating": 4.7, "description": "河洛文化"},
            {"name": "关林", "type": "历史文化", "price": 40, "rating": 4.6, "description": "关羽首级葬地"},
            {"name": "洛阳老城", "type": "历史街区", "price": 0, "rating": 4.5, "description": "千年古都风貌"},
            {"name": "洛阳牡丹园", "type": "自然风光", "price": 50, "rating": 4.6, "description": "牡丹花城"},
            {"name": "白云山", "type": "自然风光", "price": 75, "rating": 4.6, "description": "中原第一高峰"},
            {"name": "鸡冠洞", "type": "自然风光", "price": 80, "rating": 4.5, "description": "北国第一洞"},
            {"name": "龙潭大峡谷", "type": "自然风光", "price": 80, "rating": 4.5, "description": "世界地质公园"},
            {"name": "天子驾六博物馆", "type": "博物馆", "price": 30, "rating": 4.5, "description": "东周天子车马坑"},
            {"name": "丽景门", "type": "历史文化", "price": 0, "rating": 4.4, "description": "洛阳古城门"},
            {"name": "定鼎门遗址", "type": "历史文化", "price": 0, "rating": 4.4, "description": "隋唐洛阳城"},
            {"name": "隋唐城遗址植物园", "type": "城市公园", "price": 0, "rating": 4.4, "description": "遗址公园"},
            {"name": "洛邑古城", "type": "历史街区", "price": 0, "rating": 4.5, "description": "汉服体验圣地"},
            {"name": "栾川老君山", "type": "自然风光", "price": 100, "rating": 4.6, "description": "道教名山"},
        ],
    },

    # ==================== 西南地区 ====================
    "重庆": {
        "province": "重庆",
        "hotels": [
            {"name": "重庆丽晶酒店", "type": "豪华型", "price_per_night": 1200, "rating": 4.9, "facilities": ["WiFi", "泳池", "SPA", "江景"], "address": "江北区江北嘴"},
            {"name": "重庆洪崖洞民宿", "type": "特色民宿", "price_per_night": 450, "rating": 4.6, "facilities": ["WiFi", "江景", "早餐"], "address": "渝中区洪崖洞"},
            {"name": "重庆解放碑青旅", "type": "经济型", "price_per_night": 79, "rating": 4.3, "facilities": ["WiFi"], "address": "渝中区解放碑"},
        ],
        "restaurants": [
            {"name": "珮姐老火锅", "cuisine": "火锅", "avg_price": 108, "rating": 4.8, "specialties": ["牛油锅底", "毛肚", "鸭肠"]},
            {"name": "小面庄", "cuisine": "重庆小面", "avg_price": 15, "rating": 4.7, "specialties": ["豌杂面", "牛肉面", "小面"]},
            {"name": "南山泉水鸡", "cuisine": "川菜", "avg_price": 78, "rating": 4.6, "specialties": ["泉水鸡", "辣子鸡", "毛血旺"]},
            {"name": "八一好吃街", "cuisine": "小吃", "avg_price": 25, "rating": 4.5, "specialties": ["酸辣粉", "好又来酸辣粉", "山城小汤圆"]},
            {"name": "磁器口古镇小吃", "cuisine": "小吃", "avg_price": 20, "rating": 4.5, "specialties": ["陈麻花", "毛血旺", "千张皮"]},
            {"name": "大龙火锅", "cuisine": "火锅", "avg_price": 98, "rating": 4.7, "specialties": ["九宫格火锅", "毛肚", "黄喉"]},
            {"name": "李子坝梁山鸡", "cuisine": "川菜", "avg_price": 88, "rating": 4.6, "specialties": ["梁山鸡", "辣子鸡", "毛血旺"]},
            {"name": "胡记蹄花汤", "cuisine": "重庆小吃", "avg_price": 35, "rating": 4.5, "specialties": ["蹄花汤", "豌杂面", "小面"]},
        ],
        "attractions": [
            {"name": "洪崖洞", "type": "城市地标", "price": 0, "rating": 4.8, "description": "现实版千与千寻"},
            {"name": "磁器口古镇", "type": "古镇风情", "price": 0, "rating": 4.6, "description": "千年古镇"},
            {"name": "解放碑", "type": "购物商圈", "price": 0, "rating": 4.6, "description": "重庆城市中心"},
            {"name": "长江索道", "type": "城市景观", "price": 20, "rating": 4.7, "description": "万里长江第一条空中走廊"},
            {"name": "武隆天坑地缝", "type": "自然风光", "price": 135, "rating": 4.7, "description": "世界自然遗产"},
            {"name": "大足石刻", "type": "世界文化遗产", "price": 115, "rating": 4.8, "description": "世界石刻艺术宝库"},
            {"name": "南山一棵树观景台", "type": "城市景观", "price": 30, "rating": 4.6, "description": "俯瞰重庆夜景"},
            {"name": "朝天门广场", "type": "城市地标", "price": 0, "rating": 4.5, "description": "两江交汇处"},
            {"name": "三峡博物馆", "type": "博物馆", "price": 0, "rating": 4.6, "description": "三峡文化"},
            {"name": "李子坝轻轨站", "type": "城市地标", "price": 0, "rating": 4.5, "description": "轻轨穿楼奇观"},
            {"name": "歌乐山烈士陵园", "type": "历史文化", "price": 0, "rating": 4.5, "description": "红岩精神"},
            {"name": "白帝城", "type": "历史文化", "price": 100, "rating": 4.6, "description": "刘备托孤之地"},
            {"name": "酉阳桃花源", "type": "自然风光", "price": 100, "rating": 4.5, "description": "世外桃源"},
            {"name": "重庆科技馆", "type": "博物馆", "price": 0, "rating": 4.4, "description": "科普教育"},
            {"name": "南山植物园", "type": "自然风光", "price": 30, "rating": 4.4, "description": "山城绿肺"},
        ],
    },
    "昆明": {
        "province": "云南",
        "hotels": [
            {"name": "昆明洲际酒店", "type": "豪华型", "price_per_night": 980, "rating": 4.8, "facilities": ["WiFi", "泳池", "SPA"], "address": "西山区滇池路"},
            {"name": "昆明翠湖畔民宿", "type": "特色民宿", "price_per_night": 380, "rating": 4.6, "facilities": ["WiFi", "早餐"], "address": "五华区翠湖边"},
            {"name": "昆明南屏街青旅", "type": "经济型", "price_per_night": 69, "rating": 4.3, "facilities": ["WiFi"], "address": "五华区南屏街"},
        ],
        "restaurants": [
            {"name": "建新园过桥米线", "cuisine": "云南米线", "avg_price": 38, "rating": 4.7, "specialties": ["过桥米线", "小锅米线", "凉米线"]},
            {"name": "桥香园过桥米线", "cuisine": "云南米线", "avg_price": 42, "rating": 4.6, "specialties": ["过桥米线", "汽锅鸡", "卤饵丝"]},
            {"name": "福照楼汽锅鸡", "cuisine": "滇菜", "avg_price": 88, "rating": 4.7, "specialties": ["汽锅鸡", "过桥米线", "饵块"]},
            {"name": "一颗印老宅", "cuisine": "滇菜", "avg_price": 78, "rating": 4.6, "specialties": ["铜锅洋芋焖饭", "凉鸡米线", "官渡粑粑"]},
            {"name": "南屏街小吃", "cuisine": "小吃", "avg_price": 20, "rating": 4.5, "specialties": ["官渡粑粑", "烧饵块", "豆花米线"]},
            {"name": "篆新农贸市场", "cuisine": "小吃", "avg_price": 25, "rating": 4.5, "specialties": ["烧饵块", "豆花米线", "木瓜水"]},
            {"name": "云南蒸汽石锅鱼", "cuisine": "滇菜", "avg_price": 98, "rating": 4.6, "specialties": ["石锅鱼", "鲜花饼", "汽锅鸡"]},
            {"name": "大滇园", "cuisine": "滇菜", "avg_price": 88, "rating": 4.5, "specialties": ["野生菌火锅", "过桥米线", "饵块"]},
        ],
        "attractions": [
            {"name": "石林", "type": "世界自然遗产", "price": 130, "rating": 4.7, "description": "天下第一奇观"},
            {"name": "滇池", "type": "自然风光", "price": 0, "rating": 4.6, "description": "高原明珠"},
            {"name": "翠湖公园", "type": "城市公园", "price": 0, "rating": 4.5, "description": "城中碧玉"},
            {"name": "西山龙门", "type": "自然风光", "price": 40, "rating": 4.6, "description": "滇池第一胜境"},
            {"name": "云南民族村", "type": "主题公园", "price": 90, "rating": 4.5, "description": "26个民族风情"},
            {"name": "金殿风景区", "type": "历史文化", "price": 30, "rating": 4.5, "description": "铜殿"},
            {"name": "大观楼", "type": "历史文化", "price": 20, "rating": 4.5, "description": "天下第一长联"},
            {"name": "官渡古镇", "type": "古镇风情", "price": 0, "rating": 4.4, "description": "千年古镇"},
            {"name": "圆通寺", "type": "佛教圣地", "price": 0, "rating": 4.5, "description": "昆明最大佛寺"},
            {"name": "云南陆军讲武堂", "type": "博物馆", "price": 0, "rating": 4.5, "description": "近代军事史"},
            {"name": "昆明世博园", "type": "主题公园", "price": 100, "rating": 4.4, "description": "世界园艺博览园"},
            {"name": "海埂公园", "type": "城市公园", "price": 0, "rating": 4.4, "description": "滇池之滨"},
            {"name": "金马碧鸡坊", "type": "城市地标", "price": 0, "rating": 4.4, "description": "昆明标志"},
            {"name": "云南大学", "type": "高校参观", "price": 0, "rating": 4.5, "description": "最美大学之一"},
            {"name": "黑龙潭公园", "type": "自然风光", "price": 15, "rating": 4.3, "description": "梅花胜地"},
        ],
    },
    "贵阳": {
        "province": "贵州",
        "hotels": [
            {"name": "贵阳万豪酒店", "type": "豪华型", "price_per_night": 880, "rating": 4.7, "facilities": ["WiFi", "泳池", "SPA"], "address": "观山湖区长岭北路"},
            {"name": "贵阳甲秀楼民宿", "type": "特色民宿", "price_per_night": 320, "rating": 4.5, "facilities": ["WiFi", "早餐"], "address": "南明区翠微巷"},
            {"name": "贵阳喷水池青旅", "type": "经济型", "price_per_night": 59, "rating": 4.3, "facilities": ["WiFi"], "address": "云岩区喷水池"},
        ],
        "restaurants": [
            {"name": "酸汤鱼火锅", "cuisine": "贵州菜", "avg_price": 88, "rating": 4.7, "specialties": ["酸汤鱼", "糟辣鱼", "红酸汤"]},
            {"name": "肠旺面", "cuisine": "贵州面食", "avg_price": 18, "rating": 4.7, "specialties": ["肠旺面", "牛肉面", "素面"]},
            {"name": "丝娃娃", "cuisine": "贵州小吃", "avg_price": 25, "rating": 4.6, "specialties": ["丝娃娃", "恋爱豆腐果", "糕粑稀饭"]},
            {"name": "花溪牛肉粉", "cuisine": "贵州面食", "avg_price": 20, "rating": 4.7, "specialties": ["花溪牛肉粉", "羊肉粉", "酸汤粉"]},
            {"name": "贵阳老凯俚酸汤鱼", "cuisine": "贵州菜", "avg_price": 98, "rating": 4.6, "specialties": ["酸汤鱼", "折耳根", "辣子鸡"]},
            {"name": "二七路小吃街", "cuisine": "小吃", "avg_price": 25, "rating": 4.5, "specialties": ["烤串", "丝娃娃", "豆腐果"]},
            {"name": "青岩古镇卤猪脚", "cuisine": "贵州小吃", "avg_price": 30, "rating": 4.5, "specialties": ["卤猪脚", "糕粑稀饭", "玫瑰糖"]},
            {"name": "贵州龙里辣子鸡", "cuisine": "贵州菜", "avg_price": 78, "rating": 4.5, "specialties": ["辣子鸡", "折耳根炒腊肉", "宫保鸡丁"]},
        ],
        "attractions": [
            {"name": "黄果树瀑布", "type": "自然风光", "price": 160, "rating": 4.8, "description": "亚洲最大瀑布"},
            {"name": "甲秀楼", "type": "历史文化", "price": 0, "rating": 4.6, "description": "贵阳城市标志"},
            {"name": "青岩古镇", "type": "古镇风情", "price": 0, "rating": 4.6, "description": "600年古镇"},
            {"name": "黔灵山公园", "type": "城市公园", "price": 5, "rating": 4.5, "description": "黔南第一山"},
            {"name": "天河潭", "type": "自然风光", "price": 80, "rating": 4.5, "description": "贵州浓缩盆景"},
            {"name": "花溪湿地公园", "type": "自然生态", "price": 0, "rating": 4.5, "description": "城市湿地"},
            {"name": "贵州省博物馆", "type": "博物馆", "price": 0, "rating": 4.5, "description": "贵州历史文化"},
            {"name": "南江大峡谷", "type": "自然风光", "price": 88, "rating": 4.5, "description": "漂流胜地"},
            {"name": "织金洞", "type": "自然风光", "price": 120, "rating": 4.6, "description": "中国溶洞之王"},
            {"name": "荔波小七孔", "type": "世界自然遗产", "price": 130, "rating": 4.7, "description": "地球绿宝石"},
            {"name": "西江千户苗寨", "type": "古镇风情", "price": 90, "rating": 4.6, "description": "世界最大苗寨"},
            {"name": "花溪公园", "type": "城市公园", "price": 0, "rating": 4.4, "description": "高原明珠"},
            {"name": "文昌阁", "type": "历史文化", "price": 0, "rating": 4.4, "description": "贵阳古城楼"},
            {"name": "贵阳森林公园", "type": "自然风光", "price": 0, "rating": 4.3, "description": "城市森林"},
            {"name": "时光贵州", "type": "主题公园", "price": 0, "rating": 4.3, "description": "贵州文化小镇"},
        ],
    },
    "遵义": {
        "province": "贵州",
        "hotels": [
            {"name": "遵义万达嘉华酒店", "type": "豪华型", "price_per_night": 680, "rating": 4.7, "facilities": ["WiFi", "泳池", "健身房"], "address": "红花岗区万达广场"},
            {"name": "遵义会议会址民宿", "type": "特色民宿", "price_per_night": 280, "rating": 4.5, "facilities": ["WiFi", "早餐"], "address": "红花岗区子尹路"},
            {"name": "遵义火车站青旅", "type": "经济型", "price_per_night": 59, "rating": 4.3, "facilities": ["WiFi"], "address": "红花岗区火车站"},
        ],
        "restaurants": [
            {"name": "遵义羊肉粉", "cuisine": "贵州面食", "avg_price": 22, "rating": 4.8, "specialties": ["羊肉粉", "牛肉粉", "素粉"]},
            {"name": "遵义豆花面", "cuisine": "贵州面食", "avg_price": 18, "rating": 4.6, "specialties": ["豆花面", "肠旺面", "牛肉面"]},
            {"name": "刘二妈米皮", "cuisine": "贵州小吃", "avg_price": 15, "rating": 4.5, "specialties": ["米皮", "凉粉", "凉面"]},
            {"name": "遵义鸡蛋糕", "cuisine": "贵州小吃", "avg_price": 20, "rating": 4.5, "specialties": ["鸡蛋糕", "碗耳糕", "米花糖"]},
            {"name": "红军街美食", "cuisine": "小吃", "avg_price": 25, "rating": 4.4, "specialties": ["烤串", "酸辣粉", "凉粉"]},
            {"name": "虾子辣椒", "cuisine": "贵州菜", "avg_price": 68, "rating": 4.5, "specialties": ["辣椒鸡", "糟辣鱼", "折耳根"]},
            {"name": "乌江豆腐鱼", "cuisine": "贵州菜", "avg_price": 78, "rating": 4.6, "specialties": ["豆腐鱼", "酸汤鱼", "辣子鸡"]},
            {"name": "南白黄糕粑", "cuisine": "贵州小吃", "avg_price": 12, "rating": 4.4, "specialties": ["黄糕粑", "碗耳糕", "米花糖"]},
        ],
        "attractions": [
            {"name": "遵义会议会址", "type": "历史文化", "price": 0, "rating": 4.8, "description": "转折之城"},
            {"name": "赤水丹霞", "type": "世界自然遗产", "price": 90, "rating": 4.7, "description": "丹霞地貌"},
            {"name": "茅台镇", "type": "历史文化", "price": 0, "rating": 4.6, "description": "国酒之都"},
            {"name": "海龙屯", "type": "世界文化遗产", "price": 80, "rating": 4.6, "description": "播州土司遗址"},
            {"name": "娄山关", "type": "历史文化", "price": 0, "rating": 4.5, "description": "雄关漫道"},
            {"name": "红军山", "type": "历史文化", "price": 0, "rating": 4.5, "description": "红军烈士陵园"},
            {"name": "四洞沟景区", "type": "自然风光", "price": 85, "rating": 4.5, "description": "四帘飞瀑"},
            {"name": "燕子岩国家森林公园", "type": "自然风光", "price": 60, "rating": 4.4, "description": "丹霞奇观"},
            {"name": "中国侏罗纪公园", "type": "自然风光", "price": 50, "rating": 4.4, "description": "桫椤王国"},
            {"name": "遵义美术馆", "type": "博物馆", "price": 0, "rating": 4.3, "description": "文化艺术"},
            {"name": "红军街", "type": "历史街区", "price": 0, "rating": 4.4, "description": "红色文化街区"},
            {"name": "凤凰山国家森林公园", "type": "自然风光", "price": 0, "rating": 4.3, "description": "城市绿肺"},
            {"name": "遵义古城", "type": "历史街区", "price": 0, "rating": 4.3, "description": "历史文化"},
            {"name": "杨粲墓", "type": "历史文化", "price": 20, "rating": 4.3, "description": "播州土司墓"},
            {"name": "务川仡佬族文化村", "type": "历史文化", "price": 0, "rating": 4.3, "description": "仡佬族文化"},
        ],
    },

    # ==================== 东北地区 ====================
    "哈尔滨": {
        "province": "黑龙江",
        "hotels": [
            {"name": "哈尔滨松北香格里拉大酒店", "type": "豪华型", "price_per_night": 980, "rating": 4.8, "facilities": ["WiFi", "泳池", "SPA"], "address": "松北区世茂大道"},
            {"name": "哈尔滨中央大街民宿", "type": "特色民宿", "price_per_night": 380, "rating": 4.5, "facilities": ["WiFi", "暖气", "早餐"], "address": "道里区中央大街"},
            {"name": "哈尔滨火车站青旅", "type": "经济型", "price_per_night": 69, "rating": 4.3, "facilities": ["WiFi", "暖气"], "address": "南岗区火车站"},
        ],
        "restaurants": [
            {"name": "马迭尔西餐厅", "cuisine": "俄式西餐", "avg_price": 128, "rating": 4.7, "specialties": ["罐焖牛肉", "红菜汤", "俄式西餐"]},
            {"name": "华梅西餐厅", "cuisine": "俄式西餐", "avg_price": 108, "rating": 4.6, "specialties": ["红菜汤", "罐虾", "奶油面包"]},
            {"name": "秋林里道斯红肠", "cuisine": "哈尔滨特产", "avg_price": 35, "rating": 4.7, "specialties": ["红肠", "大列巴", "格瓦斯"]},
            {"name": "老昌春饼", "cuisine": "东北菜", "avg_price": 58, "rating": 4.6, "specialties": ["春饼", "锅包肉", "地三鲜"]},
            {"name": "东方饺子王", "cuisine": "东北菜", "avg_price": 45, "rating": 4.5, "specialties": ["饺子", "锅包肉", "酱骨架"]},
            {"name": "老道外小吃", "cuisine": "小吃", "avg_price": 25, "rating": 4.5, "specialties": ["干肠", "红肠", "大列巴"]},
            {"name": "毛毛熏肉大饼", "cuisine": "东北菜", "avg_price": 48, "rating": 4.5, "specialties": ["熏肉大饼", "锅包肉", "杀猪菜"]},
            {"name": "哈尔滨师大夜市", "cuisine": "小吃", "avg_price": 30, "rating": 4.5, "specialties": ["烤冷面", "烤串", "炸串"]},
        ],
        "attractions": [
            {"name": "冰雪大世界", "type": "主题公园", "price": 300, "rating": 4.7, "description": "世界最大冰雪主题乐园"},
            {"name": "中央大街", "type": "历史街区", "price": 0, "rating": 4.7, "description": "百年建筑艺术长廊"},
            {"name": "索菲亚教堂", "type": "历史文化", "price": 0, "rating": 4.6, "description": "远东最大东正教堂"},
            {"name": "太阳岛风景区", "type": "自然风光", "price": 30, "rating": 4.5, "description": "北方园林"},
            {"name": "东北虎林园", "type": "主题公园", "price": 100, "rating": 4.5, "description": "东北虎繁育基地"},
            {"name": "哈尔滨极地馆", "type": "主题公园", "price": 160, "rating": 4.5, "description": "极地动物表演"},
            {"name": "松花江畔", "type": "自然风光", "price": 0, "rating": 4.5, "description": "松花江风光"},
            {"name": "老道外历史街区", "type": "历史街区", "price": 0, "rating": 4.4, "description": "中华巴洛克建筑群"},
            {"name": "哈尔滨大剧院", "type": "城市地标", "price": 0, "rating": 4.5, "description": "世界最佳建筑"},
            {"name": "伏尔加庄园", "type": "主题公园", "price": 100, "rating": 4.4, "description": "俄式风情"},
            {"name": "亚布力滑雪场", "type": "度假区", "price": 200, "rating": 4.5, "description": "中国顶级滑雪场"},
            {"name": "龙塔", "type": "城市地标", "price": 150, "rating": 4.3, "description": "亚洲第一高钢塔"},
            {"name": "哈尔滨科学技术馆", "type": "博物馆", "price": 30, "rating": 4.3, "description": "科普教育"},
            {"name": "果戈里大街", "type": "历史街区", "price": 0, "rating": 4.4, "description": "俄式风情街"},
            {"name": "冰灯游园会", "type": "主题公园", "price": 150, "rating": 4.5, "description": "冰灯艺术"},
        ],
    },
    "大连": {
        "province": "辽宁",
        "hotels": [
            {"name": "大连君悦酒店", "type": "豪华型", "price_per_night": 1080, "rating": 4.8, "facilities": ["WiFi", "泳池", "海景"], "address": "中山区人民路"},
            {"name": "大连星海广场民宿", "type": "特色民宿", "price_per_night": 380, "rating": 4.5, "facilities": ["WiFi", "海景", "早餐"], "address": "沙河口区星海广场"},
            {"name": "大连火车站青旅", "type": "经济型", "price_per_night": 69, "rating": 4.3, "facilities": ["WiFi"], "address": "中山区火车站"},
        ],
        "restaurants": [
            {"name": "品海楼", "cuisine": "海鲜", "avg_price": 128, "rating": 4.7, "specialties": ["海胆", "鲍鱼", "清蒸石斑"]},
            {"name": "老虎滩渔人码头", "cuisine": "海鲜", "avg_price": 108, "rating": 4.6, "specialties": ["烤海鲜", "清蒸虾", "蒜蓉扇贝"]},
            {"name": "大连铁板鱿鱼", "cuisine": "大连小吃", "avg_price": 25, "rating": 4.6, "specialties": ["铁板鱿鱼", "烤鱿鱼", "炸鱿鱼"]},
            {"name": "焖子", "cuisine": "大连小吃", "avg_price": 15, "rating": 4.5, "specialties": ["焖子", "海凉粉", "咸鱼饼子"]},
            {"name": "大连海鲜大排档", "cuisine": "海鲜", "avg_price": 98, "rating": 4.5, "specialties": ["蒜蓉生蚝", "清蒸虾", "烤鱼"]},
            {"name": "回声馆", "cuisine": "日料", "avg_price": 88, "rating": 4.5, "specialties": ["寿司", "刺身", "天妇罗"]},
            {"name": "大连老菜", "cuisine": "东北菜", "avg_price": 68, "rating": 4.5, "specialties": ["锅包肉", "溜肉段", "地三鲜"]},
            {"name": "天津街小吃", "cuisine": "小吃", "avg_price": 20, "rating": 4.4, "specialties": ["烤鱿鱼", "炸串", "臭豆腐"]},
        ],
        "attractions": [
            {"name": "星海广场", "type": "城市地标", "price": 0, "rating": 4.7, "description": "亚洲最大城市广场"},
            {"name": "老虎滩海洋公园", "type": "主题公园", "price": 210, "rating": 4.7, "description": "极地海洋馆"},
            {"name": "金石滩", "type": "自然风光", "price": 0, "rating": 4.6, "description": "黄金海岸"},
            {"name": "棒棰岛", "type": "自然风光", "price": 20, "rating": 4.6, "description": "国宾浴场"},
            {"name": "大连圣亚海洋世界", "type": "主题公园", "price": 190, "rating": 4.5, "description": "海洋公园"},
            {"name": "滨海路", "type": "自然风光", "price": 0, "rating": 4.6, "description": "滨海风光"},
            {"name": "旅顺口", "type": "历史文化", "price": 0, "rating": 4.5, "description": "军港之城"},
            {"name": "大连森林动物园", "type": "主题公园", "price": 120, "rating": 4.5, "description": "森林中的动物园"},
            {"name": "东港商务区", "type": "城市景观", "price": 0, "rating": 4.5, "description": "现代都市风光"},
            {"name": "发现王国主题公园", "type": "主题公园", "price": 200, "rating": 4.5, "description": "主题乐园"},
            {"name": "俄罗斯风情街", "type": "历史街区", "price": 0, "rating": 4.4, "description": "俄式建筑群"},
            {"name": "渔人码头", "type": "城市景观", "price": 0, "rating": 4.4, "description": "欧式码头"},
            {"name": "大连现代博物馆", "type": "博物馆", "price": 0, "rating": 4.4, "description": "大连历史"},
            {"name": "西郊国家森林公园", "type": "自然风光", "price": 0, "rating": 4.3, "description": "天然氧吧"},
            {"name": "大连自然博物馆", "type": "博物馆", "price": 0, "rating": 4.4, "description": "自然标本"},
        ],
    },
    "沈阳": {
        "province": "辽宁",
        "hotels": [
            {"name": "沈阳丽都索菲特酒店", "type": "豪华型", "price_per_night": 780, "rating": 4.7, "facilities": ["WiFi", "泳池", "SPA"], "address": "和平区青年大街"},
            {"name": "沈阳故宫民宿", "type": "特色民宿", "price_per_night": 320, "rating": 4.5, "facilities": ["WiFi", "早餐"], "address": "沈河区沈阳路"},
            {"name": "沈阳太原街青旅", "type": "经济型", "price_per_night": 59, "rating": 4.3, "facilities": ["WiFi"], "address": "和平区太原街"},
        ],
        "restaurants": [
            {"name": "老边饺子", "cuisine": "东北菜", "avg_price": 58, "rating": 4.7, "specialties": ["煸馅饺子", "冰花饺子", "三鲜饺子"]},
            {"name": "李连贵熏肉大饼", "cuisine": "东北菜", "avg_price": 45, "rating": 4.6, "specialties": ["熏肉大饼", "锅包肉", "酱骨架"]},
            {"name": "马家烧麦", "cuisine": "回民菜", "avg_price": 48, "rating": 4.6, "specialties": ["烧麦", "牛肉烧麦", "羊肉烧麦"]},
            {"name": "沈阳鸡架", "cuisine": "沈阳小吃", "avg_price": 20, "rating": 4.5, "specialties": ["鸡架", "烤鸡架", "煮鸡架"]},
            {"name": "西塔韩国料理", "cuisine": "韩国料理", "avg_price": 68, "rating": 4.5, "specialties": ["烤肉", "冷面", "拌饭"]},
            {"name": "中街大果", "cuisine": "小吃", "avg_price": 8, "rating": 4.4, "specialties": ["冰棍", "雪糕", "冰淇淋"]},
            {"name": "老四季抻面", "cuisine": "沈阳小吃", "avg_price": 18, "rating": 4.5, "specialties": ["抻面", "鸡汤面", "牛肉面"]},
            {"name": "沈阳烧烤", "cuisine": "烧烤", "avg_price": 58, "rating": 4.5, "specialties": ["烤鸡架", "烤串", "烤肉"]},
        ],
        "attractions": [
            {"name": "沈阳故宫", "type": "世界文化遗产", "price": 50, "rating": 4.7, "description": "清朝发祥地"},
            {"name": "张氏帅府", "type": "博物馆", "price": 60, "rating": 4.7, "description": "张作霖张学良故居"},
            {"name": "九一八历史博物馆", "type": "博物馆", "price": 0, "rating": 4.7, "description": "勿忘国耻"},
            {"name": "北陵公园", "type": "历史文化", "price": 6, "rating": 4.5, "description": "清昭陵"},
            {"name": "东陵公园", "type": "历史文化", "price": 40, "rating": 4.5, "description": "清福陵"},
            {"name": "沈阳中街", "type": "购物商圈", "price": 0, "rating": 4.5, "description": "中国第一条商业街"},
            {"name": "棋盘山风景区", "type": "自然风光", "price": 0, "rating": 4.4, "description": "自然风光"},
            {"name": "沈阳方特欢乐世界", "type": "主题公园", "price": 260, "rating": 4.4, "description": "主题乐园"},
            {"name": "辽宁省博物馆", "type": "博物馆", "price": 0, "rating": 4.5, "description": "辽宁历史文化"},
            {"name": "西塔街", "type": "历史街区", "price": 0, "rating": 4.4, "description": "朝鲜族风情街"},
            {"name": "太原街", "type": "购物商圈", "price": 0, "rating": 4.4, "description": "商业步行街"},
            {"name": "沈阳鸟岛", "type": "自然生态", "price": 30, "rating": 4.3, "description": "观鸟胜地"},
            {"name": "新乐遗址", "type": "博物馆", "price": 0, "rating": 4.3, "description": "新石器时代遗址"},
            {"name": "沈阳科学宫", "type": "博物馆", "price": 20, "rating": 4.3, "description": "科普教育"},
            {"name": "南湖公园", "type": "城市公园", "price": 0, "rating": 4.3, "description": "城市休闲公园"},
        ],
    },
    "长春": {
        "province": "吉林",
        "hotels": [
            {"name": "长春香格里拉大酒店", "type": "豪华型", "price_per_night": 780, "rating": 4.7, "facilities": ["WiFi", "泳池", "SPA"], "address": "朝阳区西安大路"},
            {"name": "长春伪满皇宫民宿", "type": "特色民宿", "price_per_night": 280, "rating": 4.5, "facilities": ["WiFi", "早餐"], "address": "宽城区光复路"},
            {"name": "长春重庆路青旅", "type": "经济型", "price_per_night": 59, "rating": 4.3, "facilities": ["WiFi"], "address": "朝阳区重庆路"},
        ],
        "restaurants": [
            {"name": "春发合饭庄", "cuisine": "东北菜", "avg_price": 68, "rating": 4.6, "specialties": ["锅包肉", "溜肉段", "地三鲜"]},
            {"name": "老昌春饼", "cuisine": "东北菜", "avg_price": 58, "rating": 4.5, "specialties": ["春饼", "熏肉大饼", "锅包肉"]},
            {"name": "回宝珍饺子", "cuisine": "东北菜", "avg_price": 45, "rating": 4.5, "specialties": ["饺子", "酸菜饺子", "三鲜饺子"]},
            {"name": "雪衣豆沙", "cuisine": "东北菜", "avg_price": 35, "rating": 4.5, "specialties": ["雪衣豆沙", "拔丝地瓜", "锅包肉"]},
            {"name": "长春烧烤", "cuisine": "烧烤", "avg_price": 58, "rating": 4.5, "specialties": ["烤串", "烤鸡架", "烤肉"]},
            {"name": "重庆路小吃", "cuisine": "小吃", "avg_price": 20, "rating": 4.4, "specialties": ["烤冷面", "烤串", "炸串"]},
            {"name": "真不同酱骨头", "cuisine": "东北菜", "avg_price": 58, "rating": 4.5, "specialties": ["酱骨头", "锅包肉", "杀猪菜"]},
            {"name": "延吉冷面", "cuisine": "朝鲜族菜", "avg_price": 25, "rating": 4.5, "specialties": ["冷面", "石锅拌饭", "烤肉"]},
        ],
        "attractions": [
            {"name": "长影世纪城", "type": "主题公园", "price": 198, "rating": 4.5, "description": "东方好莱坞"},
            {"name": "伪满皇宫博物院", "type": "博物馆", "price": 70, "rating": 4.6, "description": "伪满洲国皇宫"},
            {"name": "净月潭国家森林公园", "type": "自然风光", "price": 30, "rating": 4.5, "description": "亚洲最大人工森林"},
            {"name": "长春电影制片厂", "type": "博物馆", "price": 0, "rating": 4.5, "description": "新中国电影摇篮"},
            {"name": "南湖公园", "type": "城市公园", "price": 0, "rating": 4.4, "description": "城市绿肺"},
            {"name": "伪满八大部", "type": "历史文化", "price": 0, "rating": 4.4, "description": "伪满政府机构"},
            {"name": "长春世界雕塑园", "type": "主题公园", "price": 30, "rating": 4.5, "description": "雕塑艺术"},
            {"name": "般若寺", "type": "佛教圣地", "price": 0, "rating": 4.4, "description": "长春最大佛寺"},
            {"name": "长春动植物公园", "type": "主题公园", "price": 30, "rating": 4.3, "description": "动植物园"},
            {"name": "长影旧址博物馆", "type": "博物馆", "price": 0, "rating": 4.5, "description": "电影文化"},
            {"name": "文化广场", "type": "城市地标", "price": 0, "rating": 4.4, "description": "城市中心广场"},
            {"name": "伪满国务院旧址", "type": "历史文化", "price": 0, "rating": 4.3, "description": "历史建筑"},
            {"name": "牡丹园", "type": "自然风光", "price": 0, "rating": 4.3, "description": "牡丹观赏"},
            {"name": "长春北湖国家湿地公园", "type": "自然生态", "price": 0, "rating": 4.3, "description": "湿地公园"},
            {"name": "关帝庙", "type": "历史文化", "price": 0, "rating": 4.3, "description": "关公庙"},
        ],
    },

    # ==================== 其他地区 ====================
    "天津": {
        "province": "天津",
        "hotels": [
            {"name": "天津丽思卡尔顿酒店", "type": "豪华型", "price_per_night": 1080, "rating": 4.8, "facilities": ["WiFi", "泳池", "SPA"], "address": "河北区大沽北路"},
            {"name": "天津五大道民宿", "type": "特色民宿", "price_per_night": 380, "rating": 4.5, "facilities": ["WiFi", "早餐"], "address": "和平区五大道"},
            {"name": "天津火车站青旅", "type": "经济型", "price_per_night": 69, "rating": 4.3, "facilities": ["WiFi"], "address": "河北区火车站"},
        ],
        "restaurants": [
            {"name": "狗不理包子", "cuisine": "天津小吃", "avg_price": 58, "rating": 4.5, "specialties": ["包子", "三鲜包", "肉包"]},
            {"name": "耳朵眼炸糕", "cuisine": "天津小吃", "avg_price": 8, "rating": 4.6, "specialties": ["炸糕", "豆沙糕", "桂花糕"]},
            {"name": "十八街麻花", "cuisine": "天津小吃", "avg_price": 25, "rating": 4.5, "specialties": ["麻花", "大麻花", "小麻花"]},
            {"name": "桂发祥麻花", "cuisine": "天津小吃", "avg_price": 30, "rating": 4.5, "specialties": ["麻花", "什锦麻花", "椒盐麻花"]},
            {"name": "天津菜馆", "cuisine": "津菜", "avg_price": 78, "rating": 4.6, "specialties": ["罾蹦鲤鱼", "贴饽饽熬鱼", "锅塌里脊"]},
            {"name": "南市食品街", "cuisine": "小吃", "avg_price": 35, "rating": 4.4, "specialties": ["包子", "炸糕", "麻花"]},
            {"name": "煎饼果子", "cuisine": "天津小吃", "avg_price": 10, "rating": 4.6, "specialties": ["煎饼果子", "锅巴菜", "老豆腐"]},
            {"name": "天津海鲜", "cuisine": "海鲜", "avg_price": 108, "rating": 4.5, "specialties": ["皮皮虾", "梭子蟹", "清蒸鱼"]},
        ],
        "attractions": [
            {"name": "天津之眼", "type": "城市地标", "price": 70, "rating": 4.6, "description": "世界唯一桥上摩天轮"},
            {"name": "五大道", "type": "历史文化", "price": 0, "rating": 4.7, "description": "万国建筑博览会"},
            {"name": "意大利风情区", "type": "历史街区", "price": 0, "rating": 4.5, "description": "意式建筑群"},
            {"name": "古文化街", "type": "历史街区", "price": 0, "rating": 4.5, "description": "津门十景"},
            {"name": "瓷房子", "type": "历史文化", "price": 50, "rating": 4.5, "description": "瓷片贴面建筑"},
            {"name": "天津博物馆", "type": "博物馆", "price": 0, "rating": 4.5, "description": "天津历史文化"},
            {"name": "海河游船", "type": "城市景观", "price": 80, "rating": 4.5, "description": "海河两岸夜景"},
            {"name": "天津之眼摩天轮", "type": "城市地标", "price": 70, "rating": 4.5, "description": "俯瞰天津全景"},
            {"name": "盘山风景区", "type": "自然风光", "price": 75, "rating": 4.5, "description": "京东第一山"},
            {"name": "天津方特欢乐世界", "type": "主题公园", "price": 260, "rating": 4.4, "description": "主题乐园"},
            {"name": "天津极地海洋馆", "type": "主题公园", "price": 160, "rating": 4.4, "description": "极地海洋动物"},
            {"name": "大沽口炮台", "type": "历史文化", "price": 30, "rating": 4.4, "description": "近代海防遗址"},
            {"name": "天津自然博物馆", "type": "博物馆", "price": 0, "rating": 4.4, "description": "自然标本"},
            {"name": "天津广播电视塔", "type": "城市地标", "price": 50, "rating": 4.3, "description": "天津之巅"},
            {"name": "天津科技馆", "type": "博物馆", "price": 20, "rating": 4.3, "description": "科普教育"},
        ],
    },
    "太原": {
        "province": "山西",
        "hotels": [
            {"name": "太原洲际酒店", "type": "豪华型", "price_per_night": 780, "rating": 4.7, "facilities": ["WiFi", "泳池", "SPA"], "address": "小店区长风街"},
            {"name": "太原晋祠民宿", "type": "特色民宿", "price_per_night": 280, "rating": 4.5, "facilities": ["WiFi", "早餐"], "address": "晋源区晋祠镇"},
            {"name": "太原柳巷青旅", "type": "经济型", "price_per_night": 59, "rating": 4.3, "facilities": ["WiFi"], "address": "迎泽区柳巷"},
        ],
        "restaurants": [
            {"name": "认一力", "cuisine": "山西面食", "avg_price": 35, "rating": 4.7, "specialties": ["刀削面", "打卤面", "剔尖"]},
            {"name": "六味斋", "cuisine": "山西小吃", "avg_price": 25, "rating": 4.6, "specialties": ["酱肉", "熏肉", "过油肉"]},
            {"name": "山西会馆", "cuisine": "晋菜", "avg_price": 88, "rating": 4.6, "specialties": ["过油肉", "糖醋丸子", "百花稍梅"]},
            {"name": "上帝炸鸡", "cuisine": "山西小吃", "avg_price": 15, "rating": 4.5, "specialties": ["炸鸡", "炸鸡排", "鸡腿"]},
            {"name": "柳巷小吃", "cuisine": "小吃", "avg_price": 20, "rating": 4.5, "specialties": ["刀削面", "丸子汤", "灌肠"]},
            {"name": "太原头脑", "cuisine": "山西小吃", "avg_price": 25, "rating": 4.5, "specialties": ["头脑", "烧麦", "稍梅"]},
            {"name": "平遥牛肉", "cuisine": "山西特产", "avg_price": 45, "rating": 4.5, "specialties": ["平遥牛肉", "牛肉干", "酱牛肉"]},
            {"name": "清和元", "cuisine": "山西小吃", "avg_price": 30, "rating": 4.5, "specialties": ["头脑", "烧麦", "丸子汤"]},
        ],
        "attractions": [
            {"name": "晋祠", "type": "世界文化遗产", "price": 80, "rating": 4.7, "description": "山西小江南"},
            {"name": "平遥古城", "type": "世界文化遗产", "price": 150, "rating": 4.7, "description": "保存最完整古城"},
            {"name": "山西博物院", "type": "博物馆", "price": 0, "rating": 4.7, "description": "晋文化宝库"},
            {"name": "五台山", "type": "佛教圣地", "price": 135, "rating": 4.8, "description": "四大佛教名山之首"},
            {"name": "云冈石窟", "type": "世界文化遗产", "price": 120, "rating": 4.8, "description": "中国四大石窟之一"},
            {"name": "太原古县城", "type": "历史街区", "price": 0, "rating": 4.4, "description": "明代古城"},
            {"name": "双塔寺", "type": "历史文化", "price": 20, "rating": 4.5, "description": "太原标志"},
            {"name": "蒙山大佛", "type": "历史文化", "price": 0, "rating": 4.5, "description": "世界最大石刻佛像"},
            {"name": "迎泽公园", "type": "城市公园", "price": 0, "rating": 4.4, "description": "城市休闲公园"},
            {"name": "乔家大院", "type": "历史文化", "price": 72, "rating": 4.6, "description": "晋商大院"},
            {"name": "王家大院", "type": "历史文化", "price": 55, "rating": 4.6, "description": "民间故宫"},
            {"name": "壶口瀑布", "type": "自然风光", "price": 90, "rating": 4.7, "description": "黄河奇观"},
            {"name": "恒山", "type": "自然风光", "price": 69, "rating": 4.5, "description": "五岳之北岳"},
            {"name": "悬空寺", "type": "历史文化", "price": 125, "rating": 4.7, "description": "悬在空中的寺庙"},
            {"name": "柳巷商业街", "type": "购物商圈", "price": 0, "rating": 4.4, "description": "太原最繁华商业街"},
        ],
    },
    "石家庄": {
        "province": "河北",
        "hotels": [
            {"name": "石家庄富力洲际酒店", "type": "豪华型", "price_per_night": 680, "rating": 4.7, "facilities": ["WiFi", "泳池", "健身房"], "address": "长安区中山东路"},
            {"name": "石家庄正定古城民宿", "type": "特色民宿", "price_per_night": 280, "rating": 4.5, "facilities": ["WiFi", "早餐"], "address": "正定县古城"},
            {"name": "石家庄火车站青旅", "type": "经济型", "price_per_night": 59, "rating": 4.3, "facilities": ["WiFi"], "address": "桥西区火车站"},
        ],
        "restaurants": [
            {"name": "正定八大碗", "cuisine": "河北菜", "avg_price": 78, "rating": 4.6, "specialties": ["八大碗", "扣肉", "丸子"]},
            {"name": "安徽板面", "cuisine": "面食", "avg_price": 15, "rating": 4.5, "specialties": ["板面", "牛肉面", "鸡蛋面"]},
            {"name": "缸炉烧饼", "cuisine": "河北小吃", "avg_price": 8, "rating": 4.5, "specialties": ["烧饼", "驴肉火烧", "熏肉"]},
            {"name": "石家庄牛肉板面", "cuisine": "面食", "avg_price": 18, "rating": 4.5, "specialties": ["牛肉板面", "鸡蛋板面", "素板面"]},
            {"name": "金凤扒鸡", "cuisine": "河北特产", "avg_price": 45, "rating": 4.5, "specialties": ["扒鸡", "烧鸡", "酱鸡"]},
            {"name": "正定马家卤鸡", "cuisine": "河北小吃", "avg_price": 35, "rating": 4.5, "specialties": ["卤鸡", "卤牛肉", "卤猪蹄"]},
            {"name": "石家庄烤串", "cuisine": "烧烤", "avg_price": 58, "rating": 4.4, "specialties": ["烤串", "烤羊腰", "烤鸡翅"]},
            {"name": "北国商城美食", "cuisine": "各地美食", "avg_price": 68, "rating": 4.4, "specialties": ["火锅", "烤肉", "日料"]},
        ],
        "attractions": [
            {"name": "正定古城", "type": "历史街区", "price": 0, "rating": 4.6, "description": "千年古郡"},
            {"name": "赵州桥", "type": "历史文化", "price": 40, "rating": 4.6, "description": "世界最古老敞肩石拱桥"},
            {"name": "正定隆兴寺", "type": "佛教圣地", "price": 50, "rating": 4.6, "description": "大佛寺"},
            {"name": "正定荣国府", "type": "主题公园", "price": 40, "rating": 4.4, "description": "红楼梦拍摄地"},
            {"name": "西柏坡", "type": "历史文化", "price": 0, "rating": 4.6, "description": "新中国从这里走来"},
            {"name": "苍岩山", "type": "自然风光", "price": 65, "rating": 4.5, "description": "太行奇峰"},
            {"name": "河北省博物院", "type": "博物馆", "price": 0, "rating": 4.5, "description": "河北历史文化"},
            {"name": "抱犊寨", "type": "自然风光", "price": 65, "rating": 4.4, "description": "兵家古寨"},
            {"name": "驼梁风景区", "type": "自然风光", "price": 65, "rating": 4.5, "description": "太行之巅"},
            {"name": "嶂石岩", "type": "自然风光", "price": 65, "rating": 4.4, "description": "丹崖翠壁"},
            {"name": "正定四塔", "type": "历史文化", "price": 20, "rating": 4.4, "description": "古塔群"},
            {"name": "石家庄电视塔", "type": "城市地标", "price": 50, "rating": 4.3, "description": "城市观景台"},
            {"name": "天山海世界", "type": "主题公园", "price": 150, "rating": 4.3, "description": "水上乐园"},
            {"name": "石家庄动物园", "type": "主题公园", "price": 50, "rating": 4.3, "description": "亲子游好去处"},
            {"name": "赵云庙", "type": "历史文化", "price": 20, "rating": 4.3, "description": "常山赵子龙"},
        ],
    },
    "济南": {
        "province": "山东",
        "hotels": [
            {"name": "济南香格里拉大酒店", "type": "豪华型", "price_per_night": 880, "rating": 4.8, "facilities": ["WiFi", "泳池", "SPA"], "address": "历下区泺源大街"},
            {"name": "济南大明湖畔民宿", "type": "特色民宿", "price_per_night": 350, "rating": 4.6, "facilities": ["WiFi", "早餐"], "address": "历下区大明湖路"},
            {"name": "济南泉城路青旅", "type": "经济型", "price_per_night": 69, "rating": 4.3, "facilities": ["WiFi"], "address": "历下区泉城路"},
        ],
        "restaurants": [
            {"name": "油旋张", "cuisine": "济南小吃", "avg_price": 10, "rating": 4.7, "specialties": ["油旋", "甜沫", "牛肉烧饼"]},
            {"name": "草包包子铺", "cuisine": "济南小吃", "avg_price": 35, "rating": 4.6, "specialties": ["灌汤包", "素包", "肉包"]},
            {"name": "便宜坊", "cuisine": "鲁菜", "avg_price": 88, "rating": 4.6, "specialties": ["糖醋鲤鱼", "爆炒腰花", "九转大肠"]},
            {"name": "燕喜堂", "cuisine": "鲁菜", "avg_price": 98, "rating": 4.6, "specialties": ["九转大肠", "糖醋鲤鱼", "爆炒腰花"]},
            {"name": "把子肉", "cuisine": "济南小吃", "avg_price": 25, "rating": 4.5, "specialties": ["把子肉", "四喜丸子", "甜沫"]},
            {"name": "泉城路小吃", "cuisine": "小吃", "avg_price": 20, "rating": 4.4, "specialties": ["烤地瓜", "炸串", "臭豆腐"]},
            {"name": "老济南甜沫", "cuisine": "济南小吃", "avg_price": 12, "rating": 4.5, "specialties": ["甜沫", "油旋", "牛肉烧饼"]},
            {"name": "济南烧烤", "cuisine": "烧烤", "avg_price": 58, "rating": 4.5, "specialties": ["烤串", "烤腰子", "烤鸡翅"]},
        ],
        "attractions": [
            {"name": "趵突泉", "type": "自然风光", "price": 40, "rating": 4.7, "description": "天下第一泉"},
            {"name": "大明湖", "type": "自然风光", "price": 0, "rating": 4.6, "description": "泉城明珠"},
            {"name": "千佛山", "type": "自然风光", "price": 30, "rating": 4.5, "description": "济南三大名胜"},
            {"name": "山东博物馆", "type": "博物馆", "price": 0, "rating": 4.6, "description": "齐鲁文化"},
            {"name": "泉城广场", "type": "城市地标", "price": 0, "rating": 4.5, "description": "济南城市客厅"},
            {"name": "芙蓉街", "type": "美食街区", "price": 0, "rating": 4.5, "description": "济南美食聚集地"},
            {"name": "黑虎泉", "type": "自然风光", "price": 0, "rating": 4.5, "description": "泉群"},
            {"name": "九如山瀑布群", "type": "自然风光", "price": 80, "rating": 4.5, "description": "瀑布群"},
            {"name": "红叶谷", "type": "自然风光", "price": 60, "rating": 4.4, "description": "秋天红叶"},
            {"name": "济南方特东方神画", "type": "主题公园", "price": 260, "rating": 4.4, "description": "主题乐园"},
            {"name": "灵岩寺", "type": "佛教圣地", "price": 60, "rating": 4.5, "description": "海内第一名塑"},
            {"name": "解放阁", "type": "历史文化", "price": 0, "rating": 4.4, "description": "解放济南纪念碑"},
            {"name": "曲水亭街", "type": "历史街区", "price": 0, "rating": 4.5, "description": "家家泉水户户垂杨"},
            {"name": "济南动物园", "type": "主题公园", "price": 25, "rating": 4.3, "description": "亲子游好去处"},
            {"name": "百脉泉公园", "type": "自然风光", "price": 50, "rating": 4.4, "description": "章丘泉群"},
        ],
    },
    "青岛": {
        "province": "山东",
        "hotels": [
            {"name": "青岛海天大酒店", "type": "豪华型", "price_per_night": 1080, "rating": 4.8, "facilities": ["WiFi", "泳池", "海景"], "address": "市南区香港西路"},
            {"name": "青岛八大关民宿", "type": "特色民宿", "price_per_night": 450, "rating": 4.6, "facilities": ["WiFi", "海景", "早餐"], "address": "市南区八大关"},
            {"name": "青岛栈桥青旅", "type": "经济型", "price_per_night": 79, "rating": 4.3, "facilities": ["WiFi"], "address": "市南区中山路"},
        ],
        "restaurants": [
            {"name": "青岛啤酒街", "cuisine": "啤酒海鲜", "avg_price": 88, "rating": 4.6, "specialties": ["原浆啤酒", "烤鱿鱼", "辣炒蛤蜊"]},
            {"name": "王姐烧烤", "cuisine": "烧烤", "avg_price": 68, "rating": 4.5, "specialties": ["烤鱿鱼", "烤大虾", "烤扇贝"]},
            {"name": "船歌鱼水饺", "cuisine": "海鲜", "avg_price": 78, "rating": 4.7, "specialties": ["墨鱼水饺", "黄花鱼水饺", "鲅鱼水饺"]},
            {"name": "万和春排骨米饭", "cuisine": "青岛小吃", "avg_price": 30, "rating": 4.5, "specialties": ["排骨米饭", "海菜凉粉", "辣炒蛤蜊"]},
            {"name": "青岛大虾", "cuisine": "海鲜", "avg_price": 128, "rating": 4.5, "specialties": ["油焖大虾", "清蒸虾", "蒜蓉虾"]},
            {"name": "台东夜市", "cuisine": "小吃", "avg_price": 30, "rating": 4.4, "specialties": ["烤串", "臭豆腐", "煎饼果子"]},
            {"name": "劈柴院小吃", "cuisine": "小吃", "avg_price": 25, "rating": 4.4, "specialties": ["锅贴", "鱿鱼", "烤海鲜"]},
            {"name": "青岛锅贴", "cuisine": "青岛小吃", "avg_price": 20, "rating": 4.5, "specialties": ["海鲜锅贴", "三鲜锅贴", "素锅贴"]},
        ],
        "attractions": [
            {"name": "栈桥", "type": "城市地标", "price": 0, "rating": 4.6, "description": "青岛标志"},
            {"name": "八大关", "type": "历史文化", "price": 0, "rating": 4.7, "description": "万国建筑博览会"},
            {"name": "崂山风景区", "type": "自然风光", "price": 90, "rating": 4.6, "description": "海上第一名山"},
            {"name": "青岛海底世界", "type": "主题公园", "price": 130, "rating": 4.5, "description": "海洋生物展览"},
            {"name": "五四广场", "type": "城市地标", "price": 0, "rating": 4.5, "description": "五月的风"},
            {"name": "奥帆中心", "type": "城市景观", "price": 0, "rating": 4.5, "description": "奥运帆船赛场"},
            {"name": "青岛啤酒博物馆", "type": "博物馆", "price": 50, "rating": 4.5, "description": "啤酒文化"},
            {"name": "金沙滩", "type": "海滩风光", "price": 0, "rating": 4.5, "description": "亚洲第一滩"},
            {"name": "信号山公园", "type": "城市公园", "price": 15, "rating": 4.4, "description": "旋转观景楼"},
            {"name": "小鱼山公园", "type": "城市公园", "price": 10, "rating": 4.4, "description": "俯瞰红瓦绿树"},
            {"name": "青岛极地海洋世界", "type": "主题公园", "price": 200, "rating": 4.5, "description": "极地动物"},
            {"name": "天主教堂", "type": "历史文化", "price": 0, "rating": 4.4, "description": "哥特式建筑"},
            {"name": "小青岛", "type": "自然风光", "price": 15, "rating": 4.4, "description": "琴屿飘灯"},
            {"name": "石老人海水浴场", "type": "海滩风光", "price": 0, "rating": 4.4, "description": "海滨浴场"},
            {"name": "海军博物馆", "type": "博物馆", "price": 0, "rating": 4.5, "description": "海军历史"},
        ],
    },
    "南昌": {
        "province": "江西",
        "hotels": [
            {"name": "南昌万达嘉华酒店", "type": "豪华型", "price_per_night": 780, "rating": 4.7, "facilities": ["WiFi", "泳池", "SPA"], "address": "东湖区阳明路"},
            {"name": "南昌滕王阁民宿", "type": "特色民宿", "price_per_night": 320, "rating": 4.5, "facilities": ["WiFi", "早餐"], "address": "东湖区滕王阁路"},
            {"name": "南昌八一广场青旅", "type": "经济型", "price_per_night": 59, "rating": 4.3, "facilities": ["WiFi"], "address": "东湖区八一广场"},
        ],
        "restaurants": [
            {"name": "南昌拌粉", "cuisine": "江西小吃", "avg_price": 12, "rating": 4.7, "specialties": ["拌粉", "炒粉", "凉拌粉"]},
            {"name": "瓦罐汤", "cuisine": "江西小吃", "avg_price": 18, "rating": 4.6, "specialties": ["瓦罐排骨汤", "瓦罐鸡汤", "瓦罐藕汤"]},
            {"name": "绳金塔美食街", "cuisine": "小吃", "avg_price": 30, "rating": 4.5, "specialties": ["烤串", "拌粉", "瓦罐汤"]},
            {"name": "南昌炒粉", "cuisine": "江西小吃", "avg_price": 15, "rating": 4.5, "specialties": ["炒粉", "炒面", "炒年糕"]},
            {"name": "石头街小吃", "cuisine": "小吃", "avg_price": 20, "rating": 4.4, "specialties": ["烤串", "臭豆腐", "油炸"]},
            {"name": "藜蒿炒腊肉", "cuisine": "赣菜", "avg_price": 68, "rating": 4.5, "specialties": ["藜蒿炒腊肉", "粉蒸肉", "啤酒鸭"]},
            {"name": "白糖糕", "cuisine": "江西小吃", "avg_price": 8, "rating": 4.4, "specialties": ["白糖糕", "油炸糕", "米糕"]},
            {"name": "南昌夜市", "cuisine": "小吃", "avg_price": 25, "rating": 4.4, "specialties": ["烤串", "小龙虾", "烧烤"]},
        ],
        "attractions": [
            {"name": "滕王阁", "type": "历史文化", "price": 50, "rating": 4.6, "description": "落霞与孤鹜齐飞"},
            {"name": "八一广场", "type": "城市地标", "price": 0, "rating": 4.5, "description": "南昌城市中心"},
            {"name": "八一起义纪念馆", "type": "博物馆", "price": 0, "rating": 4.6, "description": "军旗升起的地方"},
            {"name": "绳金塔", "type": "历史文化", "price": 0, "rating": 4.4, "description": "千年古塔"},
            {"name": "秋水广场", "type": "城市景观", "price": 0, "rating": 4.5, "description": "亚洲最大音乐喷泉"},
            {"name": "南昌之星摩天轮", "type": "城市地标", "price": 50, "rating": 4.4, "description": "亚洲高摩天轮"},
            {"name": "八大山人纪念馆", "type": "博物馆", "price": 0, "rating": 4.5, "description": "朱耷纪念馆"},
            {"name": "梅岭风景区", "type": "自然风光", "price": 30, "rating": 4.4, "description": "小庐山"},
            {"name": "天香园", "type": "自然生态", "price": 30, "rating": 4.4, "description": "城市鸟岛"},
            {"name": "南昌万达主题乐园", "type": "主题公园", "price": 220, "rating": 4.4, "description": "主题乐园"},
            {"name": "赣江夜游", "type": "城市景观", "price": 80, "rating": 4.4, "description": "赣江两岸夜景"},
            {"name": "佑民寺", "type": "佛教圣地", "price": 0, "rating": 4.3, "description": "南昌古寺"},
            {"name": "万寿宫", "type": "历史文化", "price": 0, "rating": 4.3, "description": "南昌古城楼"},
            {"name": "南昌动物园", "type": "主题公园", "price": 30, "rating": 4.3, "description": "亲子游好去处"},
            {"name": "艾溪湖湿地公园", "type": "自然生态", "price": 0, "rating": 4.3, "description": "城市湿地"},
        ],
    },
    "合肥": {
        "province": "安徽",
        "hotels": [
            {"name": "合肥万达威斯汀酒店", "type": "豪华型", "price_per_night": 780, "rating": 4.7, "facilities": ["WiFi", "泳池", "SPA"], "address": "包河区芜湖路"},
            {"name": "合肥包公园民宿", "type": "特色民宿", "price_per_night": 300, "rating": 4.5, "facilities": ["WiFi", "早餐"], "address": "包河区包公园"},
            {"name": "合肥三孝口青旅", "type": "经济型", "price_per_night": 59, "rating": 4.3, "facilities": ["WiFi"], "address": "庐阳区三孝口"},
        ],
        "restaurants": [
            {"name": "臭鳜鱼", "cuisine": "徽菜", "avg_price": 88, "rating": 4.7, "specialties": ["臭鳜鱼", "毛豆腐", "问政山笋"]},
            {"name": "耿福兴", "cuisine": "安徽小吃", "avg_price": 25, "rating": 4.6, "specialties": ["虾籽面", "酥烧饼", "小笼包"]},
            {"name": "三河米饺", "cuisine": "安徽小吃", "avg_price": 12, "rating": 4.5, "specialties": ["米饺", "酥糖", "茶干"]},
            {"name": "合肥小龙虾", "cuisine": "小龙虾", "avg_price": 68, "rating": 4.5, "specialties": ["麻辣小龙虾", "蒜蓉小龙虾", "十三香小龙虾"]},
            {"name": "庐州烤鸭", "cuisine": "安徽菜", "avg_price": 68, "rating": 4.5, "specialties": ["烤鸭", "卤鸭", "板鸭"]},
            {"name": "逍遥津小吃", "cuisine": "小吃", "avg_price": 20, "rating": 4.4, "specialties": ["烤串", "臭豆腐", "煎饼果子"]},
            {"name": "下塘烧饼", "cuisine": "安徽小吃", "avg_price": 8, "rating": 4.4, "specialties": ["烧饼", "酥烧饼", "蟹壳黄"]},
            {"name": "官亭路美食街", "cuisine": "各地美食", "avg_price": 35, "rating": 4.4, "specialties": ["火锅", "烤肉", "日料"]},
        ],
        "attractions": [
            {"name": "包公园", "type": "历史文化", "price": 20, "rating": 4.5, "description": "包青天故里"},
            {"name": "逍遥津公园", "type": "历史文化", "price": 0, "rating": 4.5, "description": "三国古战场"},
            {"name": "安徽省博物院", "type": "博物馆", "price": 0, "rating": 4.6, "description": "安徽历史文化"},
            {"name": "三河古镇", "type": "古镇风情", "price": 0, "rating": 4.5, "description": "千年水乡古镇"},
            {"name": "巢湖风景区", "type": "自然风光", "price": 0, "rating": 4.5, "description": "中国五大淡水湖"},
            {"name": "李鸿章故居", "type": "历史文化", "price": 20, "rating": 4.5, "description": "淮军名将故居"},
            {"name": "大蜀山国家森林公园", "type": "自然风光", "price": 0, "rating": 4.4, "description": "城市绿肺"},
            {"name": "合肥野生动物园", "type": "主题公园", "price": 50, "rating": 4.3, "description": "亲子游好去处"},
            {"name": "中国科学技术大学", "type": "高校参观", "price": 0, "rating": 4.5, "description": "中国顶尖学府"},
            {"name": "滨湖湿地公园", "type": "自然生态", "price": 0, "rating": 4.4, "description": "城市湿地"},
            {"name": "紫蓬山", "type": "自然风光", "price": 0, "rating": 4.4, "description": "庐州第一山"},
            {"name": "合肥植物园", "type": "城市公园", "price": 0, "rating": 4.3, "description": "植物王国"},
            {"name": "罍街", "type": "美食街区", "price": 0, "rating": 4.4, "description": "合肥美食地标"},
            {"name": "开福寺", "type": "佛教圣地", "price": 0, "rating": 4.3, "description": "合肥古寺"},
            {"name": "安徽名人馆", "type": "博物馆", "price": 0, "rating": 4.4, "description": "安徽名人"},
        ],
    },
    "香港": {
        "province": "香港",
        "hotels": [
            {"name": "香港半岛酒店", "type": "豪华型", "price_per_night": 3500, "rating": 4.9, "facilities": ["WiFi", "泳池", "SPA", "海景"], "address": "尖沙咀梳士巴利道"},
            {"name": "香港旺角民宿", "type": "特色民宿", "price_per_night": 580, "rating": 4.4, "facilities": ["WiFi", "早餐"], "address": "旺角"},
            {"name": "香港铜锣湾青旅", "type": "经济型", "price_per_night": 180, "rating": 4.3, "facilities": ["WiFi"], "address": "铜锣湾"},
        ],
        "restaurants": [
            {"name": "添好运", "cuisine": "港式点心", "avg_price": 58, "rating": 4.7, "specialties": ["酥皮叉烧包", "虾饺", "肠粉"]},
            {"name": "九记牛腩", "cuisine": "港式面食", "avg_price": 55, "rating": 4.7, "specialties": ["清汤牛腩", "咖喱牛腩", "牛腩面"]},
            {"name": "兰芳园", "cuisine": "港式茶餐厅", "avg_price": 48, "rating": 4.6, "specialties": ["丝袜奶茶", "猪扒包", "鸳鸯"]},
            {"name": "翠华餐厅", "cuisine": "港式茶餐厅", "avg_price": 68, "rating": 4.5, "specialties": ["咖喱牛腩饭", "猪扒包", "奶茶"]},
            {"name": "池记", "cuisine": "港式面食", "avg_price": 45, "rating": 4.5, "specialties": ["鲜虾云吞面", "牛腩面", "叉烧面"]},
            {"name": "蛋挞王", "cuisine": "港式点心", "avg_price": 25, "rating": 4.5, "specialties": ["蛋挞", "菠萝包", "叉烧包"]},
            {"name": "麦文记", "cuisine": "港式面食", "avg_price": 40, "rating": 4.5, "specialties": ["鲜虾云吞面", "牛杂面", "鱼蛋粉"]},
            {"name": "许留山", "cuisine": "港式甜品", "avg_price": 35, "rating": 4.4, "specialties": ["芒果班戟", "杨枝甘露", "芒果布丁"]},
        ],
        "attractions": [
            {"name": "维多利亚港", "type": "城市景观", "price": 0, "rating": 4.8, "description": "世界三大夜景之一"},
            {"name": "太平山顶", "type": "自然风光", "price": 88, "rating": 4.7, "description": "俯瞰港岛全景"},
            {"name": "迪士尼乐园", "type": "主题公园", "price": 539, "rating": 4.7, "description": "亚洲第一座迪士尼"},
            {"name": "海洋公园", "type": "主题公园", "price": 438, "rating": 4.6, "description": "海洋主题乐园"},
            {"name": "星光大道", "type": "城市地标", "price": 0, "rating": 4.6, "description": "电影文化"},
            {"name": "天坛大佛", "type": "佛教圣地", "price": 0, "rating": 4.6, "description": "世界最大青铜坐佛"},
            {"name": "大屿山", "type": "自然风光", "price": 0, "rating": 4.5, "description": "香港最大岛屿"},
            {"name": "庙街夜市", "type": "美食街区", "price": 0, "rating": 4.5, "description": "香港夜市文化"},
            {"name": "旺角", "type": "购物商圈", "price": 0, "rating": 4.5, "description": "购物天堂"},
            {"name": "中环", "type": "城市景观", "price": 0, "rating": 4.5, "description": "金融中心"},
            {"name": "黄大仙祠", "type": "佛教圣地", "price": 0, "rating": 4.4, "description": "道教圣地"},
            {"name": "香港历史博物馆", "type": "博物馆", "price": 0, "rating": 4.5, "description": "香港历史"},
            {"name": "赤柱", "type": "海滩风光", "price": 0, "rating": 4.4, "description": "海滨小镇"},
            {"name": "铜锣湾", "type": "购物商圈", "price": 0, "rating": 4.5, "description": "购物消费中心"},
            {"name": "兰桂坊", "type": "娱乐街区", "price": 0, "rating": 4.4, "description": "酒吧街"},
        ],
    },
    "澳门": {
        "province": "澳门",
        "hotels": [
            {"name": "澳门威尼斯人度假村", "type": "豪华型", "price_per_night": 2800, "rating": 4.8, "facilities": ["WiFi", "泳池", "赌场", "购物"], "address": "路氹金光大道"},
            {"name": "澳门议事亭民宿", "type": "特色民宿", "price_per_night": 480, "rating": 4.4, "facilities": ["WiFi", "早餐"], "address": "澳门半岛议事亭前地"},
            {"name": "澳门氹仔青旅", "type": "经济型", "price_per_night": 150, "rating": 4.3, "facilities": ["WiFi"], "address": "氹仔"},
        ],
        "restaurants": [
            {"name": "安德鲁蛋挞", "cuisine": "葡式蛋挞", "avg_price": 12, "rating": 4.8, "specialties": ["葡式蛋挞", "玛嘉烈蛋挞"]},
            {"name": "大利来记猪扒包", "cuisine": "澳门小吃", "avg_price": 35, "rating": 4.6, "specialties": ["猪扒包", "牛杂", "鱼蛋"]},
            {"name": "黄枝记", "cuisine": "澳门面食", "avg_price": 38, "rating": 4.5, "specialties": ["虾子捞面", "云吞面", "牛腩面"]},
            {"name": "番茄屋葡国美食", "cuisine": "葡国菜", "avg_price": 88, "rating": 4.5, "specialties": ["葡国鸡", "非洲鸡", "木糠布丁"]},
            {"name": "官也街小吃", "cuisine": "小吃", "avg_price": 25, "rating": 4.5, "specialties": ["猪扒包", "蛋挞", "杏仁饼"]},
            {"name": "诚昌饭店", "cuisine": "澳门菜", "avg_price": 78, "rating": 4.5, "specialties": ["水蟹粥", "椒盐九肚鱼", "炸响铃"]},
            {"name": "义顺牛奶公司", "cuisine": "港式甜品", "avg_price": 25, "rating": 4.5, "specialties": ["双皮奶", "姜撞奶", "炖奶"]},
            {"name": "莫义记", "cuisine": "澳门小吃", "avg_price": 20, "rating": 4.4, "specialties": ["榴莲雪糕", "木糠布丁", "大菜糕"]},
        ],
        "attractions": [
            {"name": "大三巴牌坊", "type": "世界文化遗产", "price": 0, "rating": 4.7, "description": "澳门标志"},
            {"name": "威尼斯人度假村", "type": "度假区", "price": 0, "rating": 4.6, "description": "亚洲最大赌场"},
            {"name": "澳门历史城区", "type": "世界文化遗产", "price": 0, "rating": 4.6, "description": "中西文化交融"},
            {"name": "妈阁庙", "type": "历史文化", "price": 0, "rating": 4.5, "description": "澳门最古老庙宇"},
            {"name": "大炮台", "type": "历史文化", "price": 0, "rating": 4.5, "description": "圣保禄炮台"},
            {"name": "官也街", "type": "美食街区", "price": 0, "rating": 4.5, "description": "澳门美食街"},
            {"name": "渔人码头", "type": "主题公园", "price": 0, "rating": 4.4, "description": "欧式建筑群"},
            {"name": "澳门塔", "type": "城市地标", "price": 165, "rating": 4.5, "description": "澳门观光塔"},
            {"name": "路氹金光大道", "type": "购物商圈", "price": 0, "rating": 4.5, "description": "赌场度假区"},
            {"name": "东望洋灯塔", "type": "历史文化", "price": 0, "rating": 4.4, "description": "中国海岸最古老灯塔"},
            {"name": "黑沙海滩", "type": "海滩风光", "price": 0, "rating": 4.4, "description": "澳门最美海滩"},
            {"name": "议事亭前地", "type": "历史街区", "price": 0, "rating": 4.5, "description": "葡式广场"},
            {"name": "龙环葡韵", "type": "历史文化", "price": 0, "rating": 4.5, "description": "葡式建筑群"},
            {"name": "大炮台花园", "type": "城市公园", "price": 0, "rating": 4.3, "description": "花园"},
            {"name": "澳门博物馆", "type": "博物馆", "price": 15, "rating": 4.4, "description": "澳门历史文化"},
        ],
    },
    "拉萨": {
        "province": "西藏",
        "hotels": [
            {"name": "拉萨瑞吉度假酒店", "type": "豪华型", "price_per_night": 1800, "rating": 4.9, "facilities": ["WiFi", "供氧", "SPA"]},
            {"name": "拉萨香格里拉大酒店", "type": "高档型", "price_per_night": 980, "rating": 4.8, "facilities": ["WiFi", "供氧", "餐厅"]},
            {"name": "拉萨东措青旅", "type": "经济型", "price_per_night": 59, "rating": 4.4, "facilities": ["WiFi", "公共厨房"]},
        ],
        "restaurants": [
            {"name": "玛吉阿米", "cuisine": "藏餐", "avg_price": 88, "rating": 4.7, "specialties": ["酥油茶", "糌粑", "牦牛肉"]},
            {"name": "娜玛瑟德", "cuisine": "尼泊尔菜", "avg_price": 65, "rating": 4.6, "specialties": ["咖喱", "手抓饭", "奶茶"]},
            {"name": "光明港琼甜茶馆", "cuisine": "藏餐", "avg_price": 20, "rating": 4.5, "specialties": ["甜茶", "藏面", "炸土豆"]},
            {"name": "藏家宴", "cuisine": "藏餐", "avg_price": 78, "rating": 4.5, "specialties": ["藏式火锅", "手抓羊肉", "酸奶"]},
            {"name": "雪域餐厅", "cuisine": "藏餐", "avg_price": 68, "rating": 4.5, "specialties": ["牦牛肉火锅", "青稞饼", "酥油茶"]},
            {"name": "如意林卡", "cuisine": "藏餐", "avg_price": 88, "rating": 4.5, "specialties": ["石锅鸡", "藏香猪", "松茸"]},
            {"name": "八廓街小吃", "cuisine": "小吃", "avg_price": 25, "rating": 4.4, "specialties": ["烤羊肉串", "甜茶", "糌粑"]},
            {"name": "岗底斯餐厅", "cuisine": "藏餐", "avg_price": 75, "rating": 4.5, "specialties": ["牦牛肉", "酥油茶", "藏式包子"]},
        ],
        "attractions": [
            {"name": "布达拉宫", "type": "世界文化遗产", "price": 200, "rating": 4.9, "description": "世界海拔最高的宫殿"},
            {"name": "大昭寺", "type": "世界文化遗产", "price": 85, "rating": 4.8, "description": "藏传佛教最神圣的寺庙"},
            {"name": "八廓街", "type": "历史街区", "price": 0, "rating": 4.7, "description": "转经道，藏族风情街"},
            {"name": "纳木错", "type": "自然风光", "price": 120, "rating": 4.9, "description": "世界最高的大湖"},
            {"name": "色拉寺", "type": "佛教圣地", "price": 50, "rating": 4.6, "description": "辩经场"},
            {"name": "罗布林卡", "type": "园林古迹", "price": 60, "rating": 4.5, "description": "达赖夏宫"},
            {"name": "药王山", "type": "自然风光", "price": 0, "rating": 4.5, "description": "50元人民币背景"},
            {"name": "哲蚌寺", "type": "佛教圣地", "price": 50, "rating": 4.5, "description": "世界最大寺庙"},
            {"name": "甘丹寺", "type": "佛教圣地", "price": 40, "rating": 4.4, "description": "格鲁派祖庭"},
            {"name": "楚布寺", "type": "佛教圣地", "price": 45, "rating": 4.4, "description": "噶玛噶举派主寺"},
            {"name": "羊卓雍错", "type": "自然风光", "price": 60, "rating": 4.8, "description": "三大圣湖之一"},
            {"name": "林芝", "type": "自然风光", "price": 0, "rating": 4.7, "description": "西藏江南，桃花沟"},
            {"name": "日喀则", "type": "历史文化", "price": 0, "rating": 4.5, "description": "后藏中心，扎什伦布寺"},
            {"name": "西藏博物馆", "type": "博物馆", "price": 0, "rating": 4.5, "description": "了解藏族文化"},
            {"name": "宗角禄康公园", "type": "城市公园", "price": 0, "rating": 4.4, "description": "布达拉宫后花园"},
        ],
    },
    "桂林": {
        "province": "广西",
        "hotels": [
            {"name": "桂林香格里拉大酒店", "type": "豪华型", "price_per_night": 980, "rating": 4.8, "facilities": ["WiFi", "泳池", "SPA"]},
            {"name": "桂林阳朔西街青旅", "type": "经济型", "price_per_night": 59, "rating": 4.3, "facilities": ["WiFi"]},
        ],
        "restaurants": [
            {"name": "阳朔啤酒鱼", "cuisine": "桂林菜", "avg_price": 88, "rating": 4.7, "specialties": ["啤酒鱼", "田螺酿", "荔浦芋扣肉"]},
            {"name": "桂林米粉", "cuisine": "桂林小吃", "avg_price": 12, "rating": 4.6, "specialties": ["卤菜粉", "汤粉", "马肉米粉"]},
            {"name": "椿记烧鹅", "cuisine": "粤菜", "avg_price": 78, "rating": 4.5, "specialties": ["烧鹅", "白切鸡", "叉烧"]},
            {"name": "金龙寨", "cuisine": "桂菜", "avg_price": 68, "rating": 4.5, "specialties": ["啤酒鱼", "芋头扣肉", "田螺酿"]},
            {"name": "崇善米粉", "cuisine": "桂林小吃", "avg_price": 10, "rating": 4.5, "specialties": ["米粉", "卤蛋", "锅烧"]},
            {"name": "谢大姐啤酒鱼", "cuisine": "桂林菜", "avg_price": 75, "rating": 4.5, "specialties": ["啤酒鱼", "黄焖鸡", "竹筒饭"]},
            {"name": "日头火米粉", "cuisine": "桂林小吃", "avg_price": 12, "rating": 4.4, "specialties": ["桂林米粉", "卤菜粉", "牛腩粉"]},
            {"name": "阿牛嫂米粉", "cuisine": "桂林小吃", "avg_price": 10, "rating": 4.4, "specialties": ["米粉", "油茶", "糯米饭"]},
        ],
        "attractions": [
            {"name": "漓江", "type": "自然风光", "price": 210, "rating": 4.9, "description": "桂林山水甲天下"},
            {"name": "阳朔西街", "type": "历史街区", "price": 0, "rating": 4.6, "description": "洋人街"},
            {"name": "象鼻山", "type": "城市地标", "price": 55, "rating": 4.6, "description": "桂林城徽"},
            {"name": "龙脊梯田", "type": "自然风光", "price": 80, "rating": 4.7, "description": "壮美梯田"},
            {"name": "两江四湖", "type": "城市景观", "price": 190, "rating": 4.5, "description": "桂林夜景"},
            {"name": "独秀峰", "type": "历史文化", "price": 50, "rating": 4.5, "description": "靖江王府"},
            {"name": "遇龙河", "type": "自然风光", "price": 150, "rating": 4.6, "description": "小漓江"},
            {"name": "七星公园", "type": "城市公园", "price": 55, "rating": 4.4, "description": "桂林最大公园"},
            {"name": "芦笛岩", "type": "自然奇观", "price": 90, "rating": 4.5, "description": "国宾洞"},
            {"name": "靖江王城", "type": "历史文化", "price": 50, "rating": 4.5, "description": "明代藩王府"},
            {"name": "兴坪古镇", "type": "古镇风情", "price": 0, "rating": 4.5, "description": "20元人民币背景"},
            {"name": "十里画廊", "type": "自然风光", "price": 0, "rating": 4.5, "description": "骑行胜地"},
            {"name": "银子岩", "type": "自然奇观", "price": 65, "rating": 4.4, "description": "溶洞奇观"},
            {"name": "灵川大圩古镇", "type": "古镇风情", "price": 0, "rating": 4.4, "description": "千年古镇"},
            {"name": "桂林园博园", "type": "主题公园", "price": 60, "rating": 4.3, "description": "园林博览"},
        ],
    },
    "潍坊": {
        "province": "山东",
        "hotels": [
            {"name": "潍坊富华大酒店", "type": "豪华型", "price_per_night": 680, "rating": 4.6, "facilities": ["WiFi", "泳池", "健身房"]},
            {"name": "潍坊火车站青旅", "type": "经济型", "price_per_night": 59, "rating": 4.2, "facilities": ["WiFi"]},
        ],
        "restaurants": [
            {"name": "潍坊朝天锅", "cuisine": "潍坊小吃", "avg_price": 25, "rating": 4.6, "specialties": ["朝天锅", "肉火烧", "鸡鸭和乐"]},
            {"name": "杨家埠", "cuisine": "潍坊小吃", "avg_price": 30, "rating": 4.5, "specialties": ["潍坊肉火烧", "芥末鸡", "潍县萝卜"]},
            {"name": "潍坊大酒店餐厅", "cuisine": "鲁菜", "avg_price": 88, "rating": 4.5, "specialties": ["葱烧海参", "糖醋鲤鱼", "九转大肠"]},
            {"name": "青州隆盛糕点", "cuisine": "糕点", "avg_price": 20, "rating": 4.5, "specialties": ["隆盛糕点", "蜜三刀", "绿豆糕"]},
            {"name": "诸城烧肉", "cuisine": "卤味", "avg_price": 35, "rating": 4.5, "specialties": ["烧肉", "烤鸡", "卤猪蹄"]},
            {"name": "安丘芝畔烧肉", "cuisine": "烧烤", "avg_price": 45, "rating": 4.4, "specialties": ["烧肉", "烤肉", "烤串"]},
            {"name": "潍坊朝天锅总店", "cuisine": "潍坊小吃", "avg_price": 28, "rating": 4.5, "specialties": ["朝天锅", "肉火烧", "豆腐脑"]},
            {"name": "青州全羊", "cuisine": "羊肉", "avg_price": 68, "rating": 4.5, "specialties": ["全羊汤", "羊肉火锅", "烤羊排"]},
        ],
        "attractions": [
            {"name": "青州古城", "type": "历史街区", "price": 0, "rating": 4.7, "description": "古九州之一"},
            {"name": "世界风筝博物馆", "type": "博物馆", "price": 30, "rating": 4.5, "description": "风筝之都"},
            {"name": "杨家埠民间艺术大观园", "type": "民俗文化", "price": 40, "rating": 4.5, "description": "年画之乡"},
            {"name": "沂山", "type": "自然风光", "price": 80, "rating": 4.5, "description": "东泰山"},
            {"name": "青州博物馆", "type": "博物馆", "price": 0, "rating": 4.5, "description": "县级综合性博物馆"},
            {"name": "十笏园", "type": "园林古迹", "price": 30, "rating": 4.4, "description": "袖珍园林"},
            {"name": "潍坊风筝广场", "type": "城市公园", "price": 0, "rating": 4.4, "description": "国际风筝节举办地"},
            {"name": "安丘青云山", "type": "自然风光", "price": 40, "rating": 4.4, "description": "道教圣地"},
            {"name": "诸城恐龙博物馆", "type": "博物馆", "price": 80, "rating": 4.5, "description": "恐龙之乡"},
            {"name": "临朐沂山风景区", "type": "自然风光", "price": 80, "rating": 4.4, "description": "五镇之首"},
            {"name": "寿光蔬菜博览会", "type": "主题公园", "price": 50, "rating": 4.4, "description": "蔬菜之乡"},
            {"name": "青云山民俗游乐园", "type": "主题公园", "price": 30, "rating": 4.3, "description": "民俗体验"},
            {"name": "浮烟山", "type": "自然风光", "price": 0, "rating": 4.3, "description": "潍坊西郊名山"},
            {"name": "潍坊人民公园", "type": "城市公园", "price": 0, "rating": 4.3, "description": "城市绿肺"},
            {"name": "金宝乐园", "type": "主题公园", "price": 40, "rating": 4.3, "description": "亲子乐园"},
        ],
    },
}


def get_extended_city_data(city: str):
    """获取扩展城市数据"""
    return EXTENDED_CITY_DB.get(city)


def get_all_extended_cities():
    """获取所有扩展城市列表"""
    return list(EXTENDED_CITY_DB.keys())


def search_attractions(city: str, keyword: str):
    """搜索城市景点"""
    city_data = EXTENDED_CITY_DB.get(city)
    if not city_data:
        return []
    results = []
    for attr in city_data.get("attractions", []):
        if keyword in attr.get("name", "") or keyword in attr.get("type", "") or keyword in attr.get("description", ""):
            results.append(attr)
    return results
