"""
扩展城市知识库 V3 - 华南+华东地区城市数据
"""

EXTENDED_CITY_DB = {
    # ==================== 华南地区 ====================
    "广州": {
        "province": "广东",
        "hotels": [
            {"name": "广州四季酒店", "type": "豪华型", "price_per_night": 1800, "rating": 4.9, "facilities": ["WiFi", "泳池", "SPA", "米其林餐厅"], "address": "天河区珠江新城珠江西路5号"},
            {"name": "广州白天鹅宾馆", "type": "高档型", "price_per_night": 880, "rating": 4.7, "facilities": ["WiFi", "泳池", "餐厅"], "address": "荔湾区沙面南街1号"},
            {"name": "广州北京路青旅", "type": "经济型", "price_per_night": 98, "rating": 4.3, "facilities": ["WiFi", "公共厨房"], "address": "越秀区北京路"},
        ],
        "restaurants": [
            {"name": "广州酒家", "cuisine": "粤菜", "avg_price": 128, "rating": 4.8, "specialties": ["白切鸡", "烧鹅", "虾饺"]},
            {"name": "陶陶居", "cuisine": "粤菜", "avg_price": 108, "rating": 4.7, "specialties": ["叉烧包", "凤爪", "蛋挞"]},
            {"name": "点都德", "cuisine": "早茶", "avg_price": 78, "rating": 4.7, "specialties": ["虾饺皇", "流沙包", "肠粉"]},
            {"name": "银记肠粉", "cuisine": "广州小吃", "avg_price": 25, "rating": 4.6, "specialties": ["布拉肠粉", "艇仔粥", "牛三星"]},
            {"name": "陈添记", "cuisine": "广州小吃", "avg_price": 30, "rating": 4.5, "specialties": ["祖传爽鱼皮", "艇仔粥", "猪肠粉"]},
            {"name": "惠食佳", "cuisine": "粤菜", "avg_price": 98, "rating": 4.6, "specialties": ["啫啫煲", "烧鹅", "煲仔饭"]},
            {"name": "木屋烧烤", "cuisine": "烧烤", "avg_price": 88, "rating": 4.5, "specialties": ["烤生蚝", "烤羊排", "烤茄子"]},
            {"name": "炳胜品味", "cuisine": "粤菜", "avg_price": 138, "rating": 4.7, "specialties": ["黑叉烧", "脆皮叉烧", "菠萝包"]},
        ],
        "attractions": [
            {"name": "广州塔", "type": "城市地标", "price": 150, "rating": 4.8, "description": "小蛮腰，广州新地标"},
            {"name": "沙面岛", "type": "历史文化", "price": 0, "rating": 4.7, "description": "欧陆风情建筑群"},
            {"name": "陈家祠", "type": "历史文化", "price": 10, "rating": 4.7, "description": "岭南建筑艺术明珠"},
            {"name": "白云山", "type": "自然风光", "price": 5, "rating": 4.6, "description": "羊城第一秀"},
            {"name": "长隆旅游度假区", "type": "主题公园", "price": 350, "rating": 4.7, "description": "综合主题乐园"},
            {"name": "珠江夜游", "type": "城市景观", "price": 100, "rating": 4.6, "description": "珠江两岸夜景"},
            {"name": "北京路步行街", "type": "购物商圈", "price": 0, "rating": 4.5, "description": "千年商业街"},
            {"name": "越秀公园", "type": "城市公园", "price": 0, "rating": 4.5, "description": "五羊雕像所在地"},
            {"name": "广东省博物馆", "type": "博物馆", "price": 0, "rating": 4.6, "description": "岭南文化展览"},
            {"name": "黄埔古港", "type": "历史文化", "price": 0, "rating": 4.5, "description": "海上丝绸之路起点"},
            {"name": "上下九步行街", "type": "购物商圈", "price": 0, "rating": 4.4, "description": "西关风情商业街"},
            {"name": "石室圣心大教堂", "type": "历史文化", "price": 0, "rating": 4.6, "description": "全球四座全石教堂之一"},
            {"name": "花城广场", "type": "城市景观", "price": 0, "rating": 4.5, "description": "广州城市客厅"},
            {"name": "南越王博物院", "type": "博物馆", "price": 10, "rating": 4.5, "description": "南越国遗迹"},
            {"name": "荔枝湾", "type": "历史文化", "price": 0, "rating": 4.4, "description": "西关水乡风情"},
        ],
    },
    "深圳": {
        "province": "广东",
        "hotels": [
            {"name": "深圳瑞吉酒店", "type": "豪华型", "price_per_night": 2200, "rating": 4.9, "facilities": ["WiFi", "泳池", "SPA"], "address": "南山区深南大道"},
            {"name": "深圳福田亚朵酒店", "type": "高档型", "price_per_night": 520, "rating": 4.6, "facilities": ["WiFi", "餐厅", "健身房"], "address": "福田区福华一路"},
            {"name": "深圳东门老街青旅", "type": "经济型", "price_per_night": 89, "rating": 4.3, "facilities": ["WiFi"], "address": "罗湖区东门"},
        ],
        "restaurants": [
            {"name": "润园四季椰子鸡", "cuisine": "海南菜", "avg_price": 128, "rating": 4.8, "specialties": ["椰子鸡", "竹荪", "马蹄"]},
            {"name": "松记糖水", "cuisine": "甜品", "avg_price": 25, "rating": 4.6, "specialties": ["双皮奶", "姜撞奶", "杨枝甘露"]},
            {"name": "潮汕牛肉火锅", "cuisine": "火锅", "avg_price": 108, "rating": 4.7, "specialties": ["牛肉丸", "吊龙", "匙柄"]},
            {"name": "海岸城美食街", "cuisine": "各地美食", "avg_price": 78, "rating": 4.5, "specialties": ["烧烤", "火锅", "日料"]},
            {"name": "木屋烧烤", "cuisine": "烧烤", "avg_price": 88, "rating": 4.5, "specialties": ["烤生蚝", "烤羊腿", "烤玉米"]},
            {"name": "松记肠粉", "cuisine": "广东小吃", "avg_price": 20, "rating": 4.5, "specialties": ["肠粉", "艇仔粥", "云吞面"]},
            {"name": "顺德公猪肚鸡", "cuisine": "粤菜", "avg_price": 98, "rating": 4.6, "specialties": ["猪肚鸡", "酿豆腐", "均安蒸猪"]},
            {"name": "喜茶", "cuisine": "茶饮", "avg_price": 25, "rating": 4.5, "specialties": ["芝士莓莓", "多肉葡萄", "满杯红柚"]},
        ],
        "attractions": [
            {"name": "世界之窗", "type": "主题公园", "price": 220, "rating": 4.6, "description": "微缩世界景观"},
            {"name": "欢乐谷", "type": "主题公园", "price": 230, "rating": 4.6, "description": "华侨城主题乐园"},
            {"name": "大梅沙海滨公园", "type": "海滩风光", "price": 0, "rating": 4.5, "description": "免费海滨浴场"},
            {"name": "东部华侨城", "type": "主题公园", "price": 200, "rating": 4.5, "description": "山地生态度假区"},
            {"name": "深圳湾公园", "type": "城市公园", "price": 0, "rating": 4.7, "description": "海滨休闲长廊"},
            {"name": "梧桐山", "type": "自然风光", "price": 0, "rating": 4.7, "description": "深圳最高峰"},
            {"name": "仙湖植物园", "type": "自然生态", "price": 15, "rating": 4.6, "description": "植物王国"},
            {"name": "甘坑客家小镇", "type": "古镇风情", "price": 0, "rating": 4.4, "description": "客家文化体验"},
            {"name": "深圳博物馆", "type": "博物馆", "price": 0, "rating": 4.5, "description": "深圳历史变迁"},
            {"name": "大芬油画村", "type": "文创街区", "price": 0, "rating": 4.4, "description": "中国油画第一村"},
            {"name": "华强北电子市场", "type": "购物商圈", "price": 0, "rating": 4.3, "description": "电子产品集散地"},
            {"name": "大小梅沙", "type": "海滩风光", "price": 0, "rating": 4.5, "description": "深圳黄金海岸"},
            {"name": "平安金融中心云际观光层", "type": "城市地标", "price": 200, "rating": 4.5, "description": "俯瞰深圳全景"},
            {"name": "大鹏所城", "type": "历史文化", "price": 0, "rating": 4.5, "description": "深圳鹏城由来"},
            {"name": "西涌海滩", "type": "海滩风光", "price": 68, "rating": 4.6, "description": "深圳最美海滩"},
        ],
    },
    "珠海": {
        "province": "广东",
        "hotels": [
            {"name": "珠海长隆横琴湾酒店", "type": "豪华型", "price_per_night": 1500, "rating": 4.8, "facilities": ["WiFi", "泳池", "水上乐园"], "address": "横琴新区富祥湾"},
            {"name": "珠海海泉湾度假酒店", "type": "高档型", "price_per_night": 680, "rating": 4.6, "facilities": ["WiFi", "温泉", "泳池"], "address": "金湾区"},
            {"name": "珠海拱北口岸青旅", "type": "经济型", "price_per_night": 79, "rating": 4.3, "facilities": ["WiFi"], "address": "香洲区拱北"},
        ],
        "restaurants": [
            {"name": "珠海湾仔海鲜街", "cuisine": "海鲜", "avg_price": 128, "rating": 4.6, "specialties": ["横琴蚝", "白灼海虾", "清蒸石斑"]},
            {"name": "金悦轩海鲜酒家", "cuisine": "粤菜", "avg_price": 118, "rating": 4.7, "specialties": ["避风塘炒蟹", "烧鹅", "虾饺"]},
            {"name": "斗门重壳蟹", "cuisine": "海鲜", "avg_price": 98, "rating": 4.6, "specialties": ["重壳蟹", "禾虫", "黄沙蚬"]},
            {"name": "唐家湾茶餐厅", "cuisine": "港式", "avg_price": 45, "rating": 4.5, "specialties": ["菠萝油", "丝袜奶茶", "车仔面"]},
            {"name": "拱北口岸美食", "cuisine": "各地美食", "avg_price": 58, "rating": 4.4, "specialties": ["葡国鸡", "非洲鸡", "蛋挞"]},
            {"name": "横琴蚝生态餐厅", "cuisine": "海鲜", "avg_price": 88, "rating": 4.5, "specialties": ["炭烧蚝", "蒜蓉蒸蚝", "煎蚝饼"]},
            {"name": "渔人码头海鲜", "cuisine": "海鲜", "avg_price": 108, "rating": 4.5, "specialties": ["椒盐皮皮虾", "蒜蓉扇贝", "白灼虾"]},
            {"name": "北山甜品", "cuisine": "甜品", "avg_price": 20, "rating": 4.4, "specialties": ["双皮奶", "姜撞奶", "杨枝甘露"]},
        ],
        "attractions": [
            {"name": "长隆海洋王国", "type": "主题公园", "price": 395, "rating": 4.8, "description": "全球顶级海洋主题乐园"},
            {"name": "情侣路", "type": "城市景观", "price": 0, "rating": 4.7, "description": "珠海城市名片"},
            {"name": "渔女雕像", "type": "城市地标", "price": 0, "rating": 4.6, "description": "珠海象征"},
            {"name": "外伶仃岛", "type": "海岛风光", "price": 120, "rating": 4.7, "description": "海上明珠"},
            {"name": "东澳岛", "type": "海岛风光", "price": 100, "rating": 4.6, "description": "翡翠南沙湾"},
            {"name": "圆明新园", "type": "主题公园", "price": 0, "rating": 4.4, "description": "圆明园微缩景观"},
            {"name": "珠海横琴长隆国际马戏城", "type": "演艺娱乐", "price": 280, "rating": 4.5, "description": "国际马戏表演"},
            {"name": "海泉湾", "type": "度假区", "price": 188, "rating": 4.4, "description": "温泉度假区"},
            {"name": "石景山公园", "type": "城市公园", "price": 0, "rating": 4.4, "description": "俯瞰香洲港"},
            {"name": "梅溪牌坊", "type": "历史文化", "price": 0, "rating": 4.5, "description": "清朝牌坊群"},
            {"name": "唐家湾古镇", "type": "古镇风情", "price": 0, "rating": 4.4, "description": "近代名人故里"},
            {"name": "会同古村", "type": "古镇风情", "price": 0, "rating": 4.3, "description": "岭南古村"},
            {"name": "板障山森林公园", "type": "自然风光", "price": 0, "rating": 4.4, "description": "登高望远"},
            {"name": "淇澳岛红树林", "type": "自然生态", "price": 0, "rating": 4.5, "description": "红树林湿地"},
            {"name": "珠海大剧院", "type": "城市地标", "price": 0, "rating": 4.5, "description": "日月贝"},
        ],
    },
    "佛山": {
        "province": "广东",
        "hotels": [
            {"name": "佛山保利洲际酒店", "type": "豪华型", "price_per_night": 980, "rating": 4.7, "facilities": ["WiFi", "泳池", "SPA"], "address": "禅城区汾江中路"},
            {"name": "佛山岭南天地马哥孛罗酒店", "type": "高档型", "price_per_night": 580, "rating": 4.6, "facilities": ["WiFi", "餐厅", "健身房"], "address": "禅城区祖庙路"},
            {"name": "佛山顺德大良青旅", "type": "经济型", "price_per_night": 69, "rating": 4.3, "facilities": ["WiFi"], "address": "顺德区大良"},
        ],
        "restaurants": [
            {"name": "顺德人家", "cuisine": "顺德菜", "avg_price": 98, "rating": 4.7, "specialties": ["均安蒸猪", "煎鱼饼", "陈村粉"]},
            {"name": "欢姐伦教糕", "cuisine": "顺德小吃", "avg_price": 25, "rating": 4.6, "specialties": ["伦教糕", "双皮奶", "姜撞奶"]},
            {"name": "松记餐厅", "cuisine": "顺德菜", "avg_price": 78, "rating": 4.8, "specialties": ["水蛇粥", "拆鱼羹", "酿三宝"]},
            {"name": "红星光发煲仔饭", "cuisine": "煲仔饭", "avg_price": 35, "rating": 4.5, "specialties": ["黄鳝煲仔饭", "腊味煲仔饭", "窝蛋牛肉饭"]},
            {"name": "细妹五香牛杂", "cuisine": "佛山小吃", "avg_price": 20, "rating": 4.5, "specialties": ["五香牛杂", "萝卜牛杂", "牛杂汤"]},
            {"name": "陈村粉店", "cuisine": "面食", "avg_price": 30, "rating": 4.5, "specialties": ["陈村粉", "牛腩陈村粉", "排骨陈村粉"]},
            {"name": "太艮堡毋米粥", "cuisine": "顺德菜", "avg_price": 88, "rating": 4.6, "specialties": ["毋米粥", "牛肉粥", "鱼片粥"]},
            {"name": "金榜牛奶店", "cuisine": "甜品", "avg_price": 15, "rating": 4.5, "specialties": ["双皮奶", "姜撞奶", "牛奶糕"]},
        ],
        "attractions": [
            {"name": "佛山祖庙", "type": "历史文化", "price": 20, "rating": 4.7, "description": "佛山文化标志"},
            {"name": "西樵山", "type": "自然风光", "price": 70, "rating": 4.6, "description": "南粤名山"},
            {"name": "顺德清晖园", "type": "历史文化", "price": 15, "rating": 4.6, "description": "岭南四大名园"},
            {"name": "南风古灶", "type": "历史文化", "price": 25, "rating": 4.5, "description": "五百年窑火不灭"},
            {"name": "梁园", "type": "历史文化", "price": 10, "rating": 4.5, "description": "岭南园林"},
            {"name": "逢简水乡", "type": "古镇风情", "price": 0, "rating": 4.6, "description": "岭南水乡"},
            {"name": "顺德长鹿旅游休博园", "type": "主题公园", "price": 120, "rating": 4.4, "description": "综合乐园"},
            {"name": "三水芦苞祖庙", "type": "历史文化", "price": 10, "rating": 4.3, "description": "北江古庙"},
            {"name": "佛山创意产业园", "type": "文创街区", "price": 0, "rating": 4.3, "description": "文创集聚区"},
            {"name": "岭南天地", "type": "历史街区", "price": 0, "rating": 4.5, "description": "骑楼建筑群"},
            {"name": "南海影视城", "type": "主题公园", "price": 90, "rating": 4.3, "description": "影视拍摄基地"},
            {"name": "三水森林公园", "type": "自然风光", "price": 30, "rating": 4.3, "description": "城市绿肺"},
            {"name": "顺德博物馆", "type": "博物馆", "price": 0, "rating": 4.4, "description": "顺德历史文化"},
            {"name": "平洲玉器街", "type": "购物商圈", "price": 0, "rating": 4.4, "description": "玉器集散地"},
            {"name": "丹灶仙湖", "type": "自然风光", "price": 0, "rating": 4.3, "description": "休闲胜地"},
        ],
    },
    "海口": {
        "province": "海南",
        "hotels": [
            {"name": "海口香格里拉大酒店", "type": "豪华型", "price_per_night": 1080, "rating": 4.8, "facilities": ["WiFi", "泳池", "SPA"], "address": "龙华区滨海大道"},
            {"name": "海口骑楼民宿", "type": "特色民宿", "price_per_night": 380, "rating": 4.6, "facilities": ["WiFi", "早餐"], "address": "龙华区中山路"},
            {"name": "海口海府路青旅", "type": "经济型", "price_per_night": 59, "rating": 4.3, "facilities": ["WiFi"], "address": "美兰区海府路"},
        ],
        "restaurants": [
            {"name": "海口骑楼老街老爸茶", "cuisine": "海南小吃", "avg_price": 20, "rating": 4.7, "specialties": ["老爸茶", "海南粉", "抱罗粉"]},
            {"name": "文昌糟粕醋", "cuisine": "海南菜", "avg_price": 35, "rating": 4.6, "specialties": ["糟粕醋", "海鲜", "蔬菜"]},
            {"name": "海大南门夜市", "cuisine": "小吃", "avg_price": 25, "rating": 4.5, "specialties": ["清补凉", "炒粉", "烧烤"]},
            {"name": "龙泉集团", "cuisine": "琼菜", "avg_price": 68, "rating": 4.5, "specialties": ["文昌鸡", "椰子饭", "东山羊"]},
            {"name": "泰龙城小吃街", "cuisine": "小吃", "avg_price": 20, "rating": 4.4, "specialties": ["炸炸", "烤生蚝", "清补凉"]},
            {"name": "丁村万人海鲜广场", "cuisine": "海鲜", "avg_price": 128, "rating": 4.5, "specialties": ["和乐蟹", "皮皮虾", "石斑鱼"]},
            {"name": "恒兴发茶店", "cuisine": "早茶", "avg_price": 30, "rating": 4.5, "specialties": ["虾饺", "叉烧包", "肠粉"]},
            {"name": "老盐记", "cuisine": "海南小吃", "avg_price": 15, "rating": 4.4, "specialties": ["老盐柠檬", "老盐黄皮", "清补凉"]},
        ],
        "attractions": [
            {"name": "骑楼老街", "type": "历史文化", "price": 0, "rating": 4.7, "description": "百年南洋骑楼"},
            {"name": "假日海滩", "type": "海滩风光", "price": 0, "rating": 4.6, "description": "海口最美海滩"},
            {"name": "万绿园", "type": "城市公园", "price": 0, "rating": 4.5, "description": "海口城市绿肺"},
            {"name": "火山口地质公园", "type": "自然风光", "price": 60, "rating": 4.6, "description": "万年火山奇观"},
            {"name": "日月广场免税店", "type": "购物商圈", "price": 0, "rating": 4.5, "description": "免税购物天堂"},
            {"name": "海南省博物馆", "type": "博物馆", "price": 0, "rating": 4.5, "description": "海南历史文化"},
            {"name": "五公祠", "type": "历史文化", "price": 20, "rating": 4.5, "description": "海南第一楼"},
            {"name": "白沙门公园", "type": "城市公园", "price": 0, "rating": 4.4, "description": "海滨公园"},
            {"name": "海口钟楼", "type": "城市地标", "price": 0, "rating": 4.4, "description": "海口标志建筑"},
            {"name": "冯小刚电影公社", "type": "主题公园", "price": 138, "rating": 4.3, "description": "电影主题小镇"},
            {"name": "文昌卫星发射中心", "type": "现代都市", "price": 100, "rating": 4.6, "description": "航天发射基地"},
            {"name": "观澜湖度假区", "type": "度假区", "price": 0, "rating": 4.4, "description": "高尔夫度假区"},
            {"name": "西海岸带状公园", "type": "自然风光", "price": 0, "rating": 4.3, "description": "滨海休闲带"},
            {"name": "泰华古庙", "type": "历史文化", "price": 0, "rating": 4.3, "description": "海口古庙"},
            {"name": "金牛岭公园", "type": "城市公园", "price": 0, "rating": 4.3, "description": "城市休闲公园"},
        ],
    },
    "南宁": {
        "province": "广西",
        "hotels": [
            {"name": "南宁万达文华酒店", "type": "豪华型", "price_per_night": 880, "rating": 4.7, "facilities": ["WiFi", "泳池", "SPA"], "address": "青秀区东葛路"},
            {"name": "南宁沃顿酒店", "type": "高档型", "price_per_night": 480, "rating": 4.5, "facilities": ["WiFi", "餐厅", "健身房"], "address": "青秀区民族大道"},
            {"name": "南宁中山路青旅", "type": "经济型", "price_per_night": 59, "rating": 4.3, "facilities": ["WiFi"], "address": "兴宁区中山路"},
        ],
        "restaurants": [
            {"name": "中山路美食街", "cuisine": "小吃", "avg_price": 25, "rating": 4.6, "specialties": ["老友粉", "卷筒粉", "酸嘢"]},
            {"name": "复记老友粉", "cuisine": "广西小吃", "avg_price": 18, "rating": 4.7, "specialties": ["老友粉", "老友面", "老友伊面"]},
            {"name": "漓江小聚", "cuisine": "桂菜", "avg_price": 78, "rating": 4.5, "specialties": ["啤酒鱼", "荔浦芋头", "柠檬鸭"]},
            {"name": "高峰柠檬鸭", "cuisine": "桂菜", "avg_price": 68, "rating": 4.6, "specialties": ["柠檬鸭", "白切鸡", "酸笋炒牛肉"]},
            {"name": "建政路小吃街", "cuisine": "小吃", "avg_price": 20, "rating": 4.4, "specialties": ["烤猪蹄", "酸嘢", "糖水"]},
            {"name": "农院路美食", "cuisine": "各地美食", "avg_price": 35, "rating": 4.4, "specialties": ["螺蛳粉", "烧烤", "奶茶"]},
            {"name": "肥仔烧烤", "cuisine": "烧烤", "avg_price": 58, "rating": 4.5, "specialties": ["烤田鸡", "烤生蚝", "烤茄子"]},
            {"name": "水街老牌米粉", "cuisine": "广西小吃", "avg_price": 15, "rating": 4.5, "specialties": ["生榨米粉", "老友粉", "卷筒粉"]},
        ],
        "attractions": [
            {"name": "青秀山", "type": "自然风光", "price": 20, "rating": 4.7, "description": "南宁绿肺"},
            {"name": "南宁园博园", "type": "主题公园", "price": 60, "rating": 4.5, "description": "国际园林博览园"},
            {"name": "广西民族博物馆", "type": "博物馆", "price": 0, "rating": 4.6, "description": "民族文化展览"},
            {"name": "南宁方特东盟神画", "type": "主题公园", "price": 260, "rating": 4.5, "description": "东盟主题乐园"},
            {"name": "邕江夜游", "type": "城市景观", "price": 80, "rating": 4.5, "description": "邕江两岸夜景"},
            {"name": "中山路", "type": "美食街区", "price": 0, "rating": 4.5, "description": "南宁美食地标"},
            {"name": "三街两巷", "type": "历史街区", "price": 0, "rating": 4.4, "description": "百年老街区"},
            {"name": "南湖公园", "type": "城市公园", "price": 0, "rating": 4.4, "description": "城市休闲公园"},
            {"name": "广西科技馆", "type": "博物馆", "price": 30, "rating": 4.4, "description": "科普教育基地"},
            {"name": "大明山", "type": "自然风光", "price": 90, "rating": 4.5, "description": "天然氧吧"},
            {"name": "扬美古镇", "type": "古镇风情", "price": 0, "rating": 4.4, "description": "千年古镇"},
            {"name": "南宁动物园", "type": "主题公园", "price": 50, "rating": 4.3, "description": "广西最大动物园"},
            {"name": "广西文化艺术中心", "type": "现代都市", "price": 0, "rating": 4.4, "description": "文化地标"},
            {"name": "灵水", "type": "自然风光", "price": 30, "rating": 4.3, "description": "天然泉水湖"},
            {"name": "南宁孔庙", "type": "历史文化", "price": 0, "rating": 4.3, "description": "岭南孔庙"},
        ],
    },
    # ==================== 华东地区 ====================
    "苏州": {
        "province": "江苏",
        "hotels": [
            {"name": "苏州柏悦酒店", "type": "豪华型", "price_per_night": 1800, "rating": 4.9, "facilities": ["WiFi", "泳池", "SPA"], "address": "工业园区星海街"},
            {"name": "苏州平江路民宿", "type": "特色民宿", "price_per_night": 480, "rating": 4.6, "facilities": ["WiFi", "早餐"], "address": "姑苏区平江路"},
            {"name": "苏州观前街青旅", "type": "经济型", "price_per_night": 79, "rating": 4.3, "facilities": ["WiFi"], "address": "姑苏区观前街"},
        ],
        "restaurants": [
            {"name": "松鹤楼", "cuisine": "苏帮菜", "avg_price": 128, "rating": 4.7, "specialties": ["松鼠鳜鱼", "响油鳝糊", "蟹粉豆腐"]},
            {"name": "得月楼", "cuisine": "苏帮菜", "avg_price": 108, "rating": 4.6, "specialties": ["樱桃肉", "叫花鸡", "清炒虾仁"]},
            {"name": "哑巴生煎", "cuisine": "苏州小吃", "avg_price": 25, "rating": 4.6, "specialties": ["生煎包", "小馄饨", "粉丝汤"]},
            {"name": "朱鸿兴", "cuisine": "面食", "avg_price": 35, "rating": 4.5, "specialties": ["焖肉面", "爆鱼面", "奥灶面"]},
            {"name": "黄天源", "cuisine": "苏州点心", "avg_price": 25, "rating": 4.5, "specialties": ["桂花糕", "糖粥", "酒酿圆子"]},
            {"name": "协和菜馆", "cuisine": "苏帮菜", "avg_price": 88, "rating": 4.5, "specialties": ["母油船鸭", "蜜汁火方", "响油鳝糊"]},
            {"name": "五芳斋", "cuisine": "小吃", "avg_price": 20, "rating": 4.4, "specialties": ["粽子", "小笼包", "汤圆"]},
            {"name": "陆稿荐", "cuisine": "卤味", "avg_price": 45, "rating": 4.5, "specialties": ["酱鸭", "酱肉", "卤猪蹄"]},
        ],
        "attractions": [
            {"name": "拙政园", "type": "世界文化遗产", "price": 70, "rating": 4.8, "description": "中国四大名园之首"},
            {"name": "虎丘", "type": "历史文化", "price": 60, "rating": 4.7, "description": "吴中第一名胜"},
            {"name": "留园", "type": "世界文化遗产", "price": 45, "rating": 4.7, "description": "中国四大名园"},
            {"name": "金鸡湖", "type": "城市景观", "price": 0, "rating": 4.6, "description": "城市湖泊公园"},
            {"name": "平江路", "type": "历史街区", "price": 0, "rating": 4.6, "description": "苏州最有韵味的老街"},
            {"name": "寒山寺", "type": "佛教圣地", "price": 20, "rating": 4.5, "description": "姑苏城外寒山寺"},
            {"name": "苏州博物馆", "type": "博物馆", "price": 0, "rating": 4.7, "description": "贝聿铭封山之作"},
            {"name": "同里古镇", "type": "古镇风情", "price": 100, "rating": 4.6, "description": "水乡明珠"},
            {"name": "周庄", "type": "古镇风情", "price": 100, "rating": 4.5, "description": "中国第一水乡"},
            {"name": "狮子林", "type": "世界文化遗产", "price": 40, "rating": 4.5, "description": "假山王国"},
            {"name": "网师园", "type": "世界文化遗产", "price": 40, "rating": 4.5, "description": "小园极则"},
            {"name": "山塘街", "type": "历史街区", "price": 0, "rating": 4.5, "description": "姑苏第一名街"},
            {"name": "苏州中心", "type": "购物商圈", "price": 0, "rating": 4.4, "description": "现代商业地标"},
            {"name": "沧浪亭", "type": "世界文化遗产", "price": 20, "rating": 4.4, "description": "苏州最古老园林"},
            {"name": "盘门景区", "type": "历史文化", "price": 40, "rating": 4.4, "description": "水陆城门并存"},
        ],
    },
    "宁波": {
        "province": "浙江",
        "hotels": [
            {"name": "宁波香格里拉大酒店", "type": "豪华型", "price_per_night": 980, "rating": 4.8, "facilities": ["WiFi", "泳池", "SPA"], "address": "鄞州区民安路"},
            {"name": "宁波老外滩民宿", "type": "特色民宿", "price_per_night": 380, "rating": 4.5, "facilities": ["WiFi", "早餐"], "address": "江北区老外滩"},
            {"name": "宁波天一广场青旅", "type": "经济型", "price_per_night": 69, "rating": 4.3, "facilities": ["WiFi"], "address": "海曙区天一广场"},
        ],
        "restaurants": [
            {"name": "缸鸭狗", "cuisine": "宁波菜", "avg_price": 68, "rating": 4.7, "specialties": ["汤圆", "年糕", "油赞子"]},
            {"name": "向阳渔港", "cuisine": "海鲜", "avg_price": 128, "rating": 4.6, "specialties": ["红膏炝蟹", "雪菜大汤黄鱼", "葱油海瓜子"]},
            {"name": "南塘老街小吃", "cuisine": "宁波小吃", "avg_price": 25, "rating": 4.5, "specialties": ["油赞子", "年糕", "汤圆"]},
            {"name": "宁波酒家", "cuisine": "甬菜", "avg_price": 98, "rating": 4.6, "specialties": ["冰糖甲鱼", "锅烧鳗", "腐皮包黄鱼"]},
            {"name": "石浦渔港海鲜", "cuisine": "海鲜", "avg_price": 108, "rating": 4.5, "specialties": ["清蒸梭子蟹", "椒盐皮皮虾", "白灼虾"]},
            {"name": "老宁波1926", "cuisine": "宁波菜", "avg_price": 78, "rating": 4.5, "specialties": ["雪菜黄鱼", "咸齑大汤", "烤菜"]},
            {"name": "味一早餐", "cuisine": "宁波小吃", "avg_price": 15, "rating": 4.4, "specialties": ["猪油汤圆", "豆沙汤圆", "油条"]},
            {"name": "城隍庙小吃", "cuisine": "小吃", "avg_price": 20, "rating": 4.4, "specialties": ["汤圆", "馄饨", "春卷"]},
        ],
        "attractions": [
            {"name": "天一阁", "type": "博物馆", "price": 30, "rating": 4.7, "description": "中国最古老私人藏书楼"},
            {"name": "老外滩", "type": "历史街区", "price": 0, "rating": 4.6, "description": "百年租界风情"},
            {"name": "东钱湖", "type": "自然风光", "price": 0, "rating": 4.6, "description": "浙江最大天然湖泊"},
            {"name": "普陀山", "type": "佛教圣地", "price": 160, "rating": 4.8, "description": "观音菩萨道场"},
            {"name": "雪窦山", "type": "佛教圣地", "price": 150, "rating": 4.6, "description": "弥勒菩萨道场"},
            {"name": "南塘老街", "type": "历史街区", "price": 0, "rating": 4.5, "description": "宁波美食聚集地"},
            {"name": "天一广场", "type": "购物商圈", "price": 0, "rating": 4.5, "description": "宁波商业中心"},
            {"name": "鼓楼步行街", "type": "历史街区", "price": 0, "rating": 4.4, "description": "千年鼓楼"},
            {"name": "宁波博物馆", "type": "博物馆", "price": 0, "rating": 4.5, "description": "王澍设计"},
            {"name": "象山影视城", "type": "主题公园", "price": 150, "rating": 4.4, "description": "影视拍摄基地"},
            {"name": "前童古镇", "type": "古镇风情", "price": 0, "rating": 4.5, "description": "江南明清古镇"},
            {"name": "月湖", "type": "城市公园", "price": 0, "rating": 4.4, "description": "宁波城市客厅"},
            {"name": "保国寺", "type": "历史文化", "price": 20, "rating": 4.5, "description": "千年古刹"},
            {"name": "溪口风景区", "type": "自然风光", "price": 120, "rating": 4.6, "description": "蒋氏故里"},
            {"name": "象山石浦渔港", "type": "历史文化", "price": 60, "rating": 4.4, "description": "中国渔文化之乡"},
        ],
    },
    "无锡": {
        "province": "江苏",
        "hotels": [
            {"name": "无锡太湖华邑酒店", "type": "豪华型", "price_per_night": 1080, "rating": 4.8, "facilities": ["WiFi", "泳池", "SPA"], "address": "滨湖区太湖新城"},
            {"name": "无锡拈花湾民宿", "type": "特色民宿", "price_per_night": 580, "rating": 4.6, "facilities": ["WiFi", "禅意体验"], "address": "滨湖区马山"},
            {"name": "无锡三阳广场青旅", "type": "经济型", "price_per_night": 69, "rating": 4.3, "facilities": ["WiFi"], "address": "梁溪区三阳广场"},
        ],
        "restaurants": [
            {"name": "三凤桥肉庄", "cuisine": "无锡菜", "avg_price": 98, "rating": 4.7, "specialties": ["酱排骨", "无锡小笼", "脆鳝"]},
            {"name": "王兴记", "cuisine": "无锡小吃", "avg_price": 35, "rating": 4.6, "specialties": ["小笼包", "馄饨", "蟹粉小笼"]},
            {"name": "朝阳楼", "cuisine": "无锡菜", "avg_price": 88, "rating": 4.5, "specialties": ["梁溪脆鳝", "清蒸白鱼", "太湖三白"]},
            {"name": "南长街小吃", "cuisine": "小吃", "avg_price": 25, "rating": 4.4, "specialties": ["豆腐花", "玉兰饼", "梅花糕"]},
            {"name": "湖滨路美食街", "cuisine": "各地美食", "avg_price": 68, "rating": 4.4, "specialties": ["本帮菜", "日料", "火锅"]},
            {"name": "穆桂英美食", "cuisine": "无锡菜", "avg_price": 78, "rating": 4.5, "specialties": ["无锡排骨", "响油鳝糊", "八宝饭"]},
            {"name": "小笼包专门店", "cuisine": "无锡小吃", "avg_price": 30, "rating": 4.5, "specialties": ["无锡小笼", "蟹黄小笼", "鲜肉小笼"]},
            {"name": "太湖船菜馆", "cuisine": "太湖菜", "avg_price": 128, "rating": 4.6, "specialties": ["太湖三白", "银鱼炒蛋", "清蒸白鱼"]},
        ],
        "attractions": [
            {"name": "鼋头渚", "type": "自然风光", "price": 90, "rating": 4.8, "description": "太湖绝佳处"},
            {"name": "灵山大佛", "type": "佛教圣地", "price": 210, "rating": 4.8, "description": "88米青铜大佛"},
            {"name": "拈花湾", "type": "古镇风情", "price": 120, "rating": 4.6, "description": "禅意小镇"},
            {"name": "南长街", "type": "历史街区", "price": 0, "rating": 4.5, "description": "古运河畔老街"},
            {"name": "惠山古镇", "type": "古镇风情", "price": 0, "rating": 4.5, "description": "祠堂文化群"},
            {"name": "蠡园", "type": "自然风光", "price": 30, "rating": 4.5, "description": "太湖园林"},
            {"name": "无锡博物院", "type": "博物馆", "price": 0, "rating": 4.4, "description": "无锡历史文化"},
            {"name": "清名桥古运河", "type": "历史文化", "price": 0, "rating": 4.5, "description": "古运河活化石"},
            {"name": "锡惠公园", "type": "城市公园", "price": 10, "rating": 4.4, "description": "城市山林"},
            {"name": "梅园", "type": "自然风光", "price": 30, "rating": 4.5, "description": "梅园横山"},
            {"name": "三国城", "type": "主题公园", "price": 75, "rating": 4.4, "description": "三国影视基地"},
            {"name": "水浒城", "type": "主题公园", "price": 55, "rating": 4.3, "description": "水浒影视基地"},
            {"name": "太湖湿地公园", "type": "自然生态", "price": 50, "rating": 4.4, "description": "太湖生态湿地"},
            {"name": "东林书院", "type": "历史文化", "price": 0, "rating": 4.4, "description": "风声雨声读书声"},
            {"name": "崇安寺步行街", "type": "购物商圈", "price": 0, "rating": 4.3, "description": "无锡商业中心"},
        ],
    },
    "绍兴": {
        "province": "浙江",
        "hotels": [
            {"name": "绍兴咸亨酒店", "type": "高档型", "price_per_night": 580, "rating": 4.6, "facilities": ["WiFi", "餐厅"], "address": "越城区鲁迅中路"},
            {"name": "绍兴书圣故里民宿", "type": "特色民宿", "price_per_night": 320, "rating": 4.5, "facilities": ["WiFi", "早餐"], "address": "越城区书圣故里"},
            {"name": "绍兴火车站青旅", "type": "经济型", "price_per_night": 59, "rating": 4.3, "facilities": ["WiFi"], "address": "越城区车站路"},
        ],
        "restaurants": [
            {"name": "咸亨酒店", "cuisine": "绍兴菜", "avg_price": 78, "rating": 4.7, "specialties": ["茴香豆", "臭豆腐", "醉鸡"]},
            {"name": "绍兴饭店", "cuisine": "绍兴菜", "avg_price": 88, "rating": 4.6, "specialties": ["梅菜扣肉", "醉虾", "酱鸭"]},
            {"name": "寻宝记", "cuisine": "绍兴菜", "avg_price": 68, "rating": 4.5, "specialties": ["花雕鸡", "臭豆腐", "油炸臭豆腐"]},
            {"name": "鲁迅故里小吃", "cuisine": "小吃", "avg_price": 20, "rating": 4.5, "specialties": ["臭豆腐", "奶油小攀", "黄酒棒冰"]},
            {"name": "王老汉臭豆腐", "cuisine": "绍兴小吃", "avg_price": 10, "rating": 4.5, "specialties": ["臭豆腐", "炸年糕", "烤肠"]},
            {"name": "沈园私房菜", "cuisine": "绍兴菜", "avg_price": 78, "rating": 4.5, "specialties": ["沈园十景", "黄酒鸭", "醉蟹"]},
            {"name": "老街小吃", "cuisine": "小吃", "avg_price": 25, "rating": 4.4, "specialties": ["臭豆腐", "茴香豆", "黄酒"]},
            {"name": "越味观", "cuisine": "绍兴菜", "avg_price": 68, "rating": 4.5, "specialties": ["霉干菜扣肉", "醉鸡", "酱三样"]},
        ],
        "attractions": [
            {"name": "鲁迅故里", "type": "历史文化", "price": 0, "rating": 4.7, "description": "百草园三味书屋"},
            {"name": "沈园", "type": "历史文化", "price": 40, "rating": 4.6, "description": "陆游唐婉爱情故事"},
            {"name": "东湖", "type": "自然风光", "price": 50, "rating": 4.6, "description": "盆景式山水"},
            {"name": "兰亭", "type": "历史文化", "price": 70, "rating": 4.6, "description": "书法圣地"},
            {"name": "安昌古镇", "type": "古镇风情", "price": 0, "rating": 4.5, "description": "师爷之乡"},
            {"name": "仓桥直街", "type": "历史街区", "price": 0, "rating": 4.5, "description": "原汁原味老街"},
            {"name": "柯岩风景区", "type": "自然风光", "price": 100, "rating": 4.5, "description": "石佛、鉴湖、鲁镇"},
            {"name": "大禹陵", "type": "历史文化", "price": 0, "rating": 4.5, "description": "华夏始祖"},
            {"name": "会稽山", "type": "佛教圣地", "price": 50, "rating": 4.4, "description": "佛教圣地"},
            {"name": "八字桥", "type": "历史文化", "price": 0, "rating": 4.4, "description": "最古老立交桥"},
            {"name": "秋瑾故居", "type": "历史文化", "price": 0, "rating": 4.4, "description": "巾帼英雄故居"},
            {"name": "蔡元培故居", "type": "历史文化", "price": 0, "rating": 4.3, "description": "北大之父故居"},
            {"name": "绍兴黄酒博物馆", "type": "博物馆", "price": 30, "rating": 4.4, "description": "黄酒文化"},
            {"name": "镜湖湿地公园", "type": "自然风光", "price": 0, "rating": 4.4, "description": "城市湿地"},
            {"name": "西施故里", "type": "历史文化", "price": 0, "rating": 4.3, "description": "浣纱溪畔"},
        ],
    },
    "嘉兴": {
        "province": "浙江",
        "hotels": [
            {"name": "嘉兴希尔顿酒店", "type": "豪华型", "price_per_night": 780, "rating": 4.7, "facilities": ["WiFi", "泳池", "SPA"], "address": "南湖区中环南路"},
            {"name": "乌镇西栅民宿", "type": "特色民宿", "price_per_night": 580, "rating": 4.6, "facilities": ["WiFi", "早餐", "江南风情"], "address": "桐乡市乌镇"},
            {"name": "嘉兴月河青旅", "type": "经济型", "price_per_night": 69, "rating": 4.3, "facilities": ["WiFi"], "address": "南湖区月河"},
        ],
        "restaurants": [
            {"name": "五芳斋", "cuisine": "嘉兴小吃", "avg_price": 25, "rating": 4.7, "specialties": ["粽子", "鲜肉粽", "蛋黄粽"]},
            {"name": "月河美食街", "cuisine": "各地美食", "avg_price": 58, "rating": 4.5, "specialties": ["南湖船菜", "酱鸭", "白鱼"]},
            {"name": "乌镇通安客栈", "cuisine": "江南菜", "avg_price": 88, "rating": 4.6, "specialties": ["白水鱼", "酱鸭", "定升糕"]},
            {"name": "桐乡煲", "cuisine": "煲类", "avg_price": 58, "rating": 4.5, "specialties": ["羊肉煲", "鱼头煲", "鸡煲"]},
            {"name": "西塘送子来凤桥小吃", "cuisine": "小吃", "avg_price": 20, "rating": 4.4, "specialties": ["管老太臭豆腐", "荷叶粉蒸肉", "酒酿"]},
            {"name": "平湖糟蛋", "cuisine": "嘉兴特产", "avg_price": 30, "rating": 4.5, "specialties": ["糟蛋", "糟鸡", "糟鸭"]},
            {"name": "海宁缸肉", "cuisine": "杭帮菜", "avg_price": 68, "rating": 4.5, "specialties": ["缸肉", "宴球", "汪菜"]},
            {"name": "乌镇羊肉面", "cuisine": "面食", "avg_price": 35, "rating": 4.5, "specialties": ["羊肉面", "酱羊肉", "红烧羊肉"]},
        ],
        "attractions": [
            {"name": "乌镇", "type": "古镇风情", "price": 150, "rating": 4.8, "description": "中国最后的枕水人家"},
            {"name": "西塘古镇", "type": "古镇风情", "price": 95, "rating": 4.7, "description": "生活着的千年古镇"},
            {"name": "南湖", "type": "历史文化", "price": 0, "rating": 4.6, "description": "红船精神发源地"},
            {"name": "月河历史街区", "type": "历史街区", "price": 0, "rating": 4.5, "description": "嘉兴小巷风情"},
            {"name": "海宁盐官观潮景区", "type": "自然风光", "price": 0, "rating": 4.6, "description": "天下奇观钱江潮"},
            {"name": "九龙山旅游度假区", "type": "度假区", "price": 0, "rating": 4.4, "description": "滨海度假区"},
            {"name": "海宁皮革城", "type": "购物商圈", "price": 0, "rating": 4.4, "description": "皮革之都"},
            {"name": "平湖东湖景区", "type": "自然风光", "price": 0, "rating": 4.4, "description": "东湖八景"},
            {"name": "濮院古镇", "type": "古镇风情", "price": 0, "rating": 4.3, "description": "毛衫之都"},
            {"name": "茅盾故居", "type": "历史文化", "price": 0, "rating": 4.4, "description": "文学巨匠故里"},
            {"name": "金庸书院", "type": "历史文化", "price": 0, "rating": 4.3, "description": "武侠文化"},
            {"name": "中国丝绸博物馆", "type": "博物馆", "price": 0, "rating": 4.4, "description": "丝绸文化"},
            {"name": "桐乡石门桂花村", "type": "自然风光", "price": 0, "rating": 4.3, "description": "桂花之乡"},
            {"name": "嘉兴博物馆", "type": "博物馆", "price": 0, "rating": 4.3, "description": "马家浜文化"},
            {"name": "新塍古镇", "type": "古镇风情", "price": 0, "rating": 4.3, "description": "江南小蓬莱"},
        ],
    },
    "南通": {
        "province": "江苏",
        "hotels": [
            {"name": "南通希尔顿酒店", "type": "豪华型", "price_per_night": 780, "rating": 4.7, "facilities": ["WiFi", "泳池", "SPA"], "address": "崇川区工农路"},
            {"name": "南通濠河畔民宿", "type": "特色民宿", "price_per_night": 320, "rating": 4.5, "facilities": ["WiFi", "早餐"], "address": "崇川区濠河边"},
            {"name": "南通火车站青旅", "type": "经济型", "price_per_night": 59, "rating": 4.3, "facilities": ["WiFi"], "address": "崇川区火车站"},
        ],
        "restaurants": [
            {"name": "南通大饭店", "cuisine": "南通菜", "avg_price": 88, "rating": 4.6, "specialties": ["天下第一鲜", "文峰饭店", "提汤羊肉"]},
            {"name": "狼山鸡", "cuisine": "南通菜", "avg_price": 78, "rating": 4.5, "specialties": ["狼山鸡", "文蛤蒸蛋", "炒河豚"]},
            {"name": "西寺路小吃", "cuisine": "小吃", "avg_price": 20, "rating": 4.4, "specialties": ["脆饼", "蓝印花布", "蟹黄汤包"]},
            {"name": "濠河夜市", "cuisine": "小吃", "avg_price": 35, "rating": 4.4, "specialties": ["烧烤", "小龙虾", "臭豆腐"]},
            {"name": "如东风情", "cuisine": "海鲜", "avg_price": 98, "rating": 4.5, "specialties": ["文蛤", "竹蛏", "泥螺"]},
            {"name": "海门叠石桥美食", "cuisine": "各地美食", "avg_price": 58, "rating": 4.4, "specialties": ["提汤羊肉", "沙地八大碗"]},
            {"name": "启东吕四渔港", "cuisine": "海鲜", "avg_price": 108, "rating": 4.5, "specialties": ["吕四带鱼", "梭子蟹", "白虾"]},
            {"name": "南通脆饼店", "cuisine": "点心", "avg_price": 25, "rating": 4.4, "specialties": ["南通脆饼", "麻糕", "脆饼"]},
        ],
        "attractions": [
            {"name": "濠河风景区", "type": "城市景观", "price": 0, "rating": 4.6, "description": "千年护城河"},
            {"name": "狼山风景区", "type": "佛教圣地", "price": 70, "rating": 4.6, "description": "八小佛教名山之首"},
            {"name": "南通博物苑", "type": "博物馆", "price": 0, "rating": 4.5, "description": "中国第一座公共博物馆"},
            {"name": "啬园", "type": "历史文化", "price": 20, "rating": 4.4, "description": "张謇纪念园"},
            {"name": "唐闸古镇", "type": "古镇风情", "price": 0, "rating": 4.4, "description": "近代工业遗存"},
            {"name": "如皋水绘园", "type": "历史文化", "price": 30, "rating": 4.5, "description": "徽派园林"},
            {"name": "吕四渔港", "type": "历史文化", "price": 0, "rating": 4.3, "description": "千年渔港"},
            {"name": "张謇故居", "type": "历史文化", "price": 20, "rating": 4.4, "description": "状元实业家"},
            {"name": "南通方特探险王国", "type": "主题公园", "price": 200, "rating": 4.3, "description": "亲子游乐"},
            {"name": "洋口港", "type": "自然风光", "price": 0, "rating": 4.3, "description": "海滨风光"},
            {"name": "家纺城", "type": "购物商圈", "price": 0, "rating": 4.3, "description": "中国家纺之都"},
            {"name": "南通科技馆", "type": "博物馆", "price": 20, "rating": 4.3, "description": "科普教育"},
            {"name": "金蛤岛", "type": "自然风光", "price": 0, "rating": 4.3, "description": "滩涂风光"},
            {"name": "海安角斜鹤乡", "type": "自然生态", "price": 0, "rating": 4.3, "description": "丹顶鹤栖息地"},
            {"name": "如东小洋口", "type": "自然风光", "price": 0, "rating": 4.3, "description": "海上迪斯科"},
        ],
    },
    "金华": {
        "province": "浙江",
        "hotels": [
            {"name": "金华万达嘉华酒店", "type": "豪华型", "price_per_night": 680, "rating": 4.7, "facilities": ["WiFi", "泳池", "健身房"], "address": "婺城区八一南街"},
            {"name": "横店影视城酒店", "type": "特色酒店", "price_per_night": 480, "rating": 4.5, "facilities": ["WiFi", "餐厅"], "address": "东阳市横店镇"},
            {"name": "金华火车站青旅", "type": "经济型", "price_per_night": 59, "rating": 4.3, "facilities": ["WiFi"], "address": "婺城区火车站"},
        ],
        "restaurants": [
            {"name": "金华煲庄", "cuisine": "金华菜", "avg_price": 78, "rating": 4.6, "specialties": ["金华煲", "金华火腿", "金华汤包"]},
            {"name": "金华酥饼店", "cuisine": "金华小吃", "avg_price": 15, "rating": 4.5, "specialties": ["金华酥饼", "金华火腿饼", "干菜饼"]},
            {"name": "兰溪游埠古镇", "cuisine": "小吃", "avg_price": 25, "rating": 4.5, "specialties": ["豆浆", "油条", "烧饼"]},
            {"name": "永康肉麦饼", "cuisine": "金华小吃", "avg_price": 15, "rating": 4.5, "specialties": ["肉麦饼", "永康糖麦饼", "菜麦饼"]},
            {"name": "横店美食街", "cuisine": "各地美食", "avg_price": 58, "rating": 4.4, "specialties": ["东阳土菜", "金华火腿", "煲庄"]},
            {"name": "义乌小吃街", "cuisine": "小吃", "avg_price": 30, "rating": 4.4, "specialties": ["义乌红糖", "糖洋", "麻糍"]},
            {"name": "金华火腿庄", "cuisine": "特产", "avg_price": 68, "rating": 4.5, "specialties": ["火腿蒸蛋", "火腿蒸鱼", "火腿炖鸡"]},
            {"name": "兰溪鸡子馃", "cuisine": "金华小吃", "avg_price": 12, "rating": 4.4, "specialties": ["鸡子馃", "兰溪牛肉面", "霉干菜饼"]},
        ],
        "attractions": [
            {"name": "横店影视城", "type": "主题公园", "price": 330, "rating": 4.6, "description": "中国好莱坞"},
            {"name": "双龙洞", "type": "自然风光", "price": 90, "rating": 4.6, "description": "叶圣陶名篇"},
            {"name": "义乌国际商贸城", "type": "购物商圈", "price": 0, "rating": 4.5, "description": "全球最大小商品市场"},
            {"name": "兰溪诸葛八卦村", "type": "古镇风情", "price": 90, "rating": 4.5, "description": "诸葛亮后裔聚居地"},
            {"name": "牛头山", "type": "自然风光", "price": 80, "rating": 4.5, "description": "江南小九寨"},
            {"name": "方岩风景区", "type": "自然风光", "price": 60, "rating": 4.4, "description": "丹霞地貌"},
            {"name": "金华古子城", "type": "历史街区", "price": 0, "rating": 4.4, "description": "千年古城"},
            {"name": "游埠古镇", "type": "古镇风情", "price": 0, "rating": 4.4, "description": "水上茶楼"},
            {"name": "永康方岩", "type": "自然风光", "price": 60, "rating": 4.4, "description": "方岩朝圣"},
            {"name": "磐安花溪", "type": "自然风光", "price": 50, "rating": 4.4, "description": "浙中大峡谷"},
            {"name": "东阳卢宅", "type": "历史文化", "price": 40, "rating": 4.4, "description": "民间故宫"},
            {"name": "横店梦幻谷", "type": "主题公园", "price": 200, "rating": 4.3, "description": "夜间主题乐园"},
            {"name": "金华火腿博物馆", "type": "博物馆", "price": 0, "rating": 4.3, "description": "火腿文化"},
            {"name": "磐安百丈潭", "type": "自然风光", "price": 40, "rating": 4.3, "description": "天然氧吧"},
            {"name": "义乌佛堂古镇", "type": "古镇风情", "price": 0, "rating": 4.3, "description": "千年古镇"},
        ],
    },
    "扬州": {
        "province": "江苏",
        "hotels": [
            {"name": "扬州迎宾馆", "type": "豪华型", "price_per_night": 980, "rating": 4.8, "facilities": ["WiFi", "泳池", "SPA"], "address": "邗江区瘦西湖路"},
            {"name": "扬州长乐客栈", "type": "特色民宿", "price_per_night": 380, "rating": 4.6, "facilities": ["WiFi", "早餐", "园林体验"], "address": "广陵区东关街"},
            {"name": "扬州东关街青旅", "type": "经济型", "price_per_night": 69, "rating": 4.3, "facilities": ["WiFi"], "address": "广陵区东关街"},
        ],
        "restaurants": [
            {"name": "富春茶社", "cuisine": "扬州早茶", "avg_price": 88, "rating": 4.8, "specialties": ["蟹黄汤包", "翡翠烧卖", "千层油糕"]},
            {"name": "冶春茶社", "cuisine": "扬州早茶", "avg_price": 78, "rating": 4.7, "specialties": ["三丁包", "五丁包", "大煮干丝"]},
            {"name": "扬州炒饭专门店", "cuisine": "扬州菜", "avg_price": 35, "rating": 4.5, "specialties": ["扬州炒饭", "文思豆腐", "清炒虾仁"]},
            {"name": "东关街小吃", "cuisine": "小吃", "avg_price": 20, "rating": 4.5, "specialties": ["藕粉圆", "四喜汤圆", "豆腐脑"]},
            {"name": "粗茶淡饭", "cuisine": "扬州菜", "avg_price": 68, "rating": 4.6, "specialties": ["扬州三头宴", "拆烩鲢鱼头", "扒烧整猪头"]},
            {"name": "西园饭店", "cuisine": "淮扬菜", "avg_price": 108, "rating": 4.6, "specialties": ["大煮干丝", "三套鸭", "清蒸狮子头"]},
            {"name": "共和春", "cuisine": "扬州小吃", "avg_price": 25, "rating": 4.5, "specialties": ["虾籽饺面", "五丁包", "干拌面"]},
            {"name": "扬州宴", "cuisine": "淮扬菜", "avg_price": 128, "rating": 4.7, "specialties": ["文思豆腐", "清蒸鲥鱼", "扬州老鹅"]},
        ],
        "attractions": [
            {"name": "瘦西湖", "type": "自然风光", "price": 100, "rating": 4.8, "description": "两堤花柳全依水"},
            {"name": "个园", "type": "世界文化遗产", "price": 45, "rating": 4.7, "description": "四季假山"},
            {"name": "何园", "type": "世界文化遗产", "price": 45, "rating": 4.7, "description": "晚清第一园"},
            {"name": "东关街", "type": "历史街区", "price": 0, "rating": 4.6, "description": "千年商业街"},
            {"name": "大明寺", "type": "佛教圣地", "price": 30, "rating": 4.6, "description": "鉴真东渡出发地"},
            {"name": "京杭大运河扬州段", "type": "世界文化遗产", "price": 0, "rating": 4.5, "description": "运河文化"},
            {"name": "茱萸湾", "type": "自然风光", "price": 40, "rating": 4.4, "description": "运河生态公园"},
            {"name": "汪氏小苑", "type": "历史文化", "price": 30, "rating": 4.5, "description": "盐商大宅"},
            {"name": "扬州博物馆", "type": "博物馆", "price": 0, "rating": 4.5, "description": "扬州八怪"},
            {"name": "朱自清故居", "type": "历史文化", "price": 0, "rating": 4.4, "description": "文学名家故居"},
            {"name": "宋夹城遗址公园", "type": "历史文化", "price": 0, "rating": 4.4, "description": "宋代古城遗址"},
            {"name": "瘦西湖温泉", "type": "度假区", "price": 198, "rating": 4.5, "description": "温泉度假"},
            {"name": "扬州双博馆", "type": "博物馆", "price": 0, "rating": 4.4, "description": "雕版印刷"},
            {"name": "凤凰岛", "type": "自然风光", "price": 30, "rating": 4.3, "description": "生态湿地"},
            {"name": "高邮盂城驿", "type": "历史文化", "price": 30, "rating": 4.4, "description": "古代驿站"},
        ],
    },
    "湖州": {
        "province": "浙江",
        "hotels": [
            {"name": "湖州喜来登温泉度假酒店", "type": "豪华型", "price_per_night": 1080, "rating": 4.8, "facilities": ["WiFi", "温泉", "泳池"], "address": "吴兴区太湖度假区"},
            {"name": "南浔古镇民宿", "type": "特色民宿", "price_per_night": 380, "rating": 4.5, "facilities": ["WiFi", "早餐"], "address": "南浔区南浔镇"},
            {"name": "湖州火车站青旅", "type": "经济型", "price_per_night": 59, "rating": 4.3, "facilities": ["WiFi"], "address": "吴兴区火车站"},
        ],
        "restaurants": [
            {"name": "丁莲芳千张包子", "cuisine": "湖州小吃", "avg_price": 25, "rating": 4.6, "specialties": ["千张包子", "双交面", "丁莲芳粉丝"]},
            {"name": "周生记馄饨", "cuisine": "湖州小吃", "avg_price": 20, "rating": 4.5, "specialties": ["馄饨", "汤包", "春卷"]},
            {"name": "太湖船菜", "cuisine": "湖州菜", "avg_price": 108, "rating": 4.6, "specialties": ["太湖三白", "银鱼炒蛋", "清蒸白鱼"]},
            {"name": "练市羊肉", "cuisine": "湖州菜", "avg_price": 68, "rating": 4.5, "specialties": ["红烧羊肉", "羊肉面", "白切羊肉"]},
            {"name": "南浔古镇美食", "cuisine": "小吃", "avg_price": 25, "rating": 4.5, "specialties": ["双交面", "桔红糕", "桔红糕"]},
            {"name": "莫干山农家乐", "cuisine": "农家菜", "avg_price": 88, "rating": 4.5, "specialties": ["笋干老鸭煲", "土鸡煲", "野菜"]},
            {"name": "湖州大馄饨", "cuisine": "湖州小吃", "avg_price": 15, "rating": 4.4, "specialties": ["大馄饨", "小馄饨", "汤圆"]},
            {"name": "太湖边烧烤", "cuisine": "烧烤", "avg_price": 58, "rating": 4.4, "specialties": ["烤鱼", "烤虾", "烤玉米"]},
        ],
        "attractions": [
            {"name": "南浔古镇", "type": "古镇风情", "price": 95, "rating": 4.7, "description": "中西合璧水乡"},
            {"name": "莫干山", "type": "自然风光", "price": 0, "rating": 4.7, "description": "江南第一山"},
            {"name": "太湖旅游度假区", "type": "度假区", "price": 0, "rating": 4.5, "description": "太湖风光"},
            {"name": "安吉竹博园", "type": "自然风光", "price": 30, "rating": 4.5, "description": "竹子大观园"},
            {"name": "中南百草园", "type": "自然生态", "price": 80, "rating": 4.4, "description": "生态乐园"},
            {"name": "飞英塔", "type": "历史文化", "price": 20, "rating": 4.5, "description": "塔里塔"},
            {"name": "铁佛寺", "type": "佛教圣地", "price": 0, "rating": 4.3, "description": "千年古刹"},
            {"name": "衣裳街", "type": "历史街区", "price": 0, "rating": 4.4, "description": "湖州老街"},
            {"name": "安吉余村", "type": "自然风光", "price": 0, "rating": 4.4, "description": "两山理念发源地"},
            {"name": "藏龙百瀑", "type": "自然风光", "price": 60, "rating": 4.4, "description": "江南最大瀑布群"},
            {"name": "中国大竹海", "type": "自然风光", "price": 50, "rating": 4.5, "description": "卧虎藏龙取景地"},
            {"name": "长兴金钉子地质公园", "type": "博物馆", "price": 30, "rating": 4.3, "description": "地质奇观"},
            {"name": "安吉Hello Kitty乐园", "type": "主题公园", "price": 230, "rating": 4.4, "description": "Hello Kitty主题"},
            {"name": "湖州博物馆", "type": "博物馆", "price": 0, "rating": 4.3, "description": "湖州历史"},
            {"name": "安吉天赋湖", "type": "自然风光", "price": 0, "rating": 4.3, "description": "天然湖泊"},
        ],
    },
    "泉州": {
        "province": "福建",
        "hotels": [
            {"name": "泉州迎宾馆", "type": "豪华型", "price_per_night": 780, "rating": 4.7, "facilities": ["WiFi", "泳池", "SPA"], "address": "丰泽区东海"},
            {"name": "泉州西街民宿", "type": "特色民宿", "price_per_night": 280, "rating": 4.5, "facilities": ["WiFi", "早餐"], "address": "鲤城区西街"},
            {"name": "泉州钟楼青旅", "type": "经济型", "price_per_night": 59, "rating": 4.3, "facilities": ["WiFi"], "address": "鲤城区钟楼"},
        ],
        "restaurants": [
            {"name": "好成财牛排馆", "cuisine": "泉州小吃", "avg_price": 35, "rating": 4.7, "specialties": ["牛肉羹", "牛排", "咸饭"]},
            {"name": "面线糊", "cuisine": "泉州小吃", "avg_price": 15, "rating": 4.6, "specialties": ["面线糊", "醋肉", "油条"]},
            {"name": "侯阿婆肉粽", "cuisine": "泉州小吃", "avg_price": 15, "rating": 4.6, "specialties": ["烧肉粽", "牛肉羹", "元宵圆"]},
            {"name": "东兴牛肉店", "cuisine": "泉州菜", "avg_price": 45, "rating": 4.5, "specialties": ["牛肉火锅", "牛肉丸", "牛杂"]},
            {"name": "石花膏四果汤", "cuisine": "甜品", "avg_price": 10, "rating": 4.5, "specialties": ["石花膏", "四果汤", "仙草冻"]},
            {"name": "润饼菜", "cuisine": "泉州小吃", "avg_price": 12, "rating": 4.5, "specialties": ["润饼", "春卷", "菜头酸"]},
            {"name": "姜母鸭", "cuisine": "闽南菜", "avg_price": 68, "rating": 4.5, "specialties": ["姜母鸭", "烧鸭", "卤鸭"]},
            {"name": "海鲜大排档", "cuisine": "海鲜", "avg_price": 88, "rating": 4.4, "specialties": ["海蛎煎", "清蒸鱼", "虾姑"]},
        ],
        "attractions": [
            {"name": "开元寺", "type": "佛教圣地", "price": 0, "rating": 4.7, "description": "福建最大佛教寺院"},
            {"name": "西街", "type": "历史街区", "price": 0, "rating": 4.6, "description": "泉州最古老街道"},
            {"name": "洛阳桥", "type": "世界文化遗产", "price": 0, "rating": 4.6, "description": "中国古代四大名桥"},
            {"name": "清源山", "type": "自然风光", "price": 55, "rating": 4.6, "description": "老君岩"},
            {"name": "崇武古城", "type": "历史文化", "price": 45, "rating": 4.5, "description": "海防古城"},
            {"name": "关岳庙", "type": "历史文化", "price": 0, "rating": 4.5, "description": "闽南关帝庙"},
            {"name": "蟳埔村", "type": "历史文化", "price": 0, "rating": 4.5, "description": "簪花围渔女"},
            {"name": "泉州海外交通史博物馆", "type": "博物馆", "price": 0, "rating": 4.5, "description": "海丝文化"},
            {"name": "清净寺", "type": "历史文化", "price": 3, "rating": 4.5, "description": "中国最古老清真寺之一"},
            {"name": "天后宫", "type": "历史文化", "price": 0, "rating": 4.4, "description": "海神妈祖庙"},
            {"name": "草庵", "type": "佛教圣地", "price": 0, "rating": 4.4, "description": "摩尼教遗址"},
            {"name": "闽台缘博物馆", "type": "博物馆", "price": 0, "rating": 4.5, "description": "闽台文化"},
            {"name": "德化九仙山", "type": "自然风光", "price": 40, "rating": 4.4, "description": "闽中屋脊"},
            {"name": "惠安女风情", "type": "历史文化", "price": 0, "rating": 4.4, "description": "惠安女服饰文化"},
            {"name": "安平桥", "type": "世界文化遗产", "price": 0, "rating": 4.4, "description": "五里桥"},
        ],
    },
    "福州": {
        "province": "福建",
        "hotels": [
            {"name": "福州香格里拉大酒店", "type": "豪华型", "price_per_night": 980, "rating": 4.8, "facilities": ["WiFi", "泳池", "SPA"], "address": "鼓楼区新权南路"},
            {"name": "福州三坊七巷民宿", "type": "特色民宿", "price_per_night": 380, "rating": 4.5, "facilities": ["WiFi", "早餐"], "address": "鼓楼区三坊七巷"},
            {"name": "福州火车站青旅", "type": "经济型", "price_per_night": 69, "rating": 4.3, "facilities": ["WiFi"], "address": "鼓楼区火车站"},
        ],
        "restaurants": [
            {"name": "安泰楼", "cuisine": "福州菜", "avg_price": 88, "rating": 4.7, "specialties": ["佛跳墙", "荔枝肉", "醉排骨"]},
            {"name": "老福洲", "cuisine": "福州小吃", "avg_price": 35, "rating": 4.6, "specialties": ["鱼丸", "肉燕", "锅边糊"]},
            {"name": "同利肉燕", "cuisine": "福州小吃", "avg_price": 20, "rating": 4.6, "specialties": ["肉燕", "太平燕", "燕皮"]},
            {"name": "捞化", "cuisine": "福州小吃", "avg_price": 20, "rating": 4.5, "specialties": ["捞化", "兴化米粉", "拌面"]},
            {"name": "福州聚春园", "cuisine": "福州菜", "avg_price": 128, "rating": 4.6, "specialties": ["佛跳墙", "鸡汤氽海蚌", "淡糟香螺片"]},
            {"name": "达明路美食街", "cuisine": "小吃", "avg_price": 25, "rating": 4.4, "specialties": ["鱼丸", "锅边", "芋泥"]},
            {"name": "永和鱼丸", "cuisine": "福州小吃", "avg_price": 18, "rating": 4.5, "specialties": ["鱼丸", "鱼滑", "鱼汤"]},
            {"name": "依海肉燕", "cuisine": "福州小吃", "avg_price": 15, "rating": 4.4, "specialties": ["肉燕", "燕皮", "鱼丸"]},
        ],
        "attractions": [
            {"name": "三坊七巷", "type": "历史文化", "price": 0, "rating": 4.7, "description": "中国城市里坊制度活化石"},
            {"name": "鼓山", "type": "自然风光", "price": 0, "rating": 4.6, "description": "福州第一名山"},
            {"name": "西湖公园", "type": "城市公园", "price": 0, "rating": 4.5, "description": "福州西湖"},
            {"name": "马尾船政文化景区", "type": "历史文化", "price": 30, "rating": 4.5, "description": "中国船政文化"},
            {"name": "福建博物院", "type": "博物馆", "price": 0, "rating": 4.5, "description": "福建历史文化"},
            {"name": "上下杭", "type": "历史街区", "price": 0, "rating": 4.4, "description": "福州商业街"},
            {"name": "闽江夜游", "type": "城市景观", "price": 100, "rating": 4.5, "description": "闽江两岸夜景"},
            {"name": "烟台山", "type": "历史文化", "price": 0, "rating": 4.5, "description": "万国建筑博物馆"},
            {"name": "林则徐纪念馆", "type": "历史文化", "price": 0, "rating": 4.5, "description": "虎门销烟英雄"},
            {"name": "福州大学", "type": "高校参观", "price": 0, "rating": 4.3, "description": "福建省211大学"},
            {"name": "南后街", "type": "购物商圈", "price": 0, "rating": 4.4, "description": "三坊七巷主街"},
            {"name": "于山风景区", "type": "自然风光", "price": 0, "rating": 4.4, "description": "城中山"},
            {"name": "鼓岭", "type": "自然风光", "price": 0, "rating": 4.4, "description": "避暑胜地"},
            {"name": "仓山老洋房", "type": "历史文化", "price": 0, "rating": 4.3, "description": "万国建筑群"},
            {"name": "福州国家森林公园", "type": "自然风光", "price": 0, "rating": 4.5, "description": "城市天然氧吧"},
        ],
    },
    "厦门": {
        "province": "福建",
        "hotels": [
            {"name": "厦门康莱德酒店", "type": "豪华型", "price_per_night": 1500, "rating": 4.9, "facilities": ["WiFi", "泳池", "SPA"], "address": "思明区环岛路"},
            {"name": "鼓浪屿别墅酒店", "type": "特色民宿", "price_per_night": 580, "rating": 4.6, "facilities": ["WiFi", "海景", "早餐"], "address": "思明区鼓浪屿"},
            {"name": "厦门中山路青旅", "type": "经济型", "price_per_night": 79, "rating": 4.3, "facilities": ["WiFi"], "address": "思明区中山路"},
        ],
        "restaurants": [
            {"name": "沙茶面", "cuisine": "厦门小吃", "avg_price": 20, "rating": 4.7, "specialties": ["沙茶面", "海蛎煎", "烧肉粽"]},
            {"name": "莲欢海蛎煎", "cuisine": "厦门小吃", "avg_price": 25, "rating": 4.6, "specialties": ["海蛎煎", "沙茶面", "烧仙草"]},
            {"name": "局口拌面", "cuisine": "厦门小吃", "avg_price": 15, "rating": 4.5, "specialties": ["拌面", "扁食", "春卷"]},
            {"name": "佳味再添", "cuisine": "厦门菜", "avg_price": 58, "rating": 4.5, "specialties": ["姜母鸭", "同安封肉", "土笋冻"]},
            {"name": "鼓浪屿馅饼", "cuisine": "点心", "avg_price": 15, "rating": 4.5, "specialties": ["馅饼", "肉松", "麻糍"]},
            {"name": "八市海鲜", "cuisine": "海鲜", "avg_price": 108, "rating": 4.5, "specialties": ["海鲜加工", "椒盐皮皮虾", "清蒸石斑"]},
            {"name": "厦门老字号", "cuisine": "闽南菜", "avg_price": 88, "rating": 4.6, "specialties": ["佛跳墙", "炒面线", "五香卷"]},
            {"name": "中山路夜市", "cuisine": "小吃", "avg_price": 25, "rating": 4.4, "specialties": ["烤串", "臭豆腐", "花生汤"]},
        ],
        "attractions": [
            {"name": "鼓浪屿", "type": "世界文化遗产", "price": 0, "rating": 4.8, "description": "海上花园"},
            {"name": "厦门大学", "type": "高校参观", "price": 0, "rating": 4.7, "description": "中国最美大学"},
            {"name": "南普陀寺", "type": "佛教圣地", "price": 0, "rating": 4.7, "description": "闽南佛教圣地"},
            {"name": "环岛路", "type": "城市景观", "price": 0, "rating": 4.6, "description": "最美马拉松赛道"},
            {"name": "曾厝垵", "type": "文创街区", "price": 0, "rating": 4.5, "description": "文艺渔村"},
            {"name": "中山路步行街", "type": "购物商圈", "price": 0, "rating": 4.5, "description": "骑楼建筑商业街"},
            {"name": "集美学村", "type": "历史文化", "price": 0, "rating": 4.5, "description": "嘉庚建筑"},
            {"name": "胡里山炮台", "type": "历史文化", "price": 25, "rating": 4.5, "description": "世界古炮王"},
            {"name": "植物园", "type": "自然风光", "price": 30, "rating": 4.6, "description": "热带雨林"},
            {"name": "白城沙滩", "type": "海滩风光", "price": 0, "rating": 4.4, "description": "厦大海滩"},
            {"name": "厦门老院子", "type": "主题公园", "price": 120, "rating": 4.4, "description": "闽南文化"},
            {"name": "沙坡尾", "type": "文创街区", "price": 0, "rating": 4.5, "description": "艺术西区"},
            {"name": "铁路文化公园", "type": "城市公园", "price": 0, "rating": 4.4, "description": "铁路改造绿道"},
            {"name": "五缘湾湿地公园", "type": "自然生态", "price": 0, "rating": 4.4, "description": "城市湿地"},
            {"name": "东坪山", "type": "自然风光", "price": 0, "rating": 4.3, "description": "厦门后花园"},
        ],
    },
}


def get_extended_city_data(city: str):
    """获取扩展城市数据"""
    return EXTENDED_CITY_DB.get(city)
