"""
扩展城市知识库 V2 - 增加餐厅和景点数量，满足5-6天行程
"""

# 扩展城市数据 - 每个城市6-8个餐厅，10-15个景点
EXTENDED_CITY_DB = {
    # ==================== 华东地区 ====================
    "上海": {
        "province": "上海",
        "hotels": [
            {"name": "上海外滩华尔道夫酒店", "type": "豪华型", "price_per_night": 2800, "rating": 4.9, "facilities": ["WiFi", "泳池", "SPA", "米其林餐厅"], "address": "黄浦区中山东一路2号"},
            {"name": "上海静安香格里拉大酒店", "type": "高档型", "price_per_night": 1200, "rating": 4.8, "facilities": ["WiFi", "泳池", "健身房", "餐厅"], "address": "静安区延安中路1218号"},
            {"name": "上海人民广场地铁站青旅", "type": "经济型", "price_per_night": 128, "rating": 4.3, "facilities": ["WiFi", "公共厨房"], "address": "黄浦区南京西路"},
        ],
        "restaurants": [
            {"name": "鼎泰丰（恒隆广场店）", "cuisine": "台湾菜", "avg_price": 128, "rating": 4.8, "specialties": ["小笼包", "蟹粉小笼", "红油抄手"]},
            {"name": "新天地朗廷酒店凯旋餐厅", "cuisine": "法餐", "avg_price": 258, "rating": 4.7, "specialties": ["鹅肝", "牛排", "甜品"]},
            {"name": "小杨生煎", "cuisine": "上海小吃", "avg_price": 25, "rating": 4.5, "specialties": ["生煎包", "牛肉粉丝汤", "蟹壳黄"]},
            {"name": "南翔馒头店", "cuisine": "上海小吃", "avg_price": 35, "rating": 4.6, "specialties": ["南翔小笼", "蟹粉小笼", "鲜肉小笼"]},
            {"name": "上海老饭店", "cuisine": "本帮菜", "avg_price": 128, "rating": 4.6, "specialties": ["八宝鸭", "扣三丝", "红烧肉"]},
            {"name": "绿波廊", "cuisine": "本帮菜", "avg_price": 158, "rating": 4.7, "specialties": ["眉毛酥", "枣泥酥", "桂花拉糕"]},
            {"name": "老正兴", "cuisine": "本帮菜", "avg_price": 88, "rating": 4.5, "specialties": ["油爆虾", "腌笃鲜", "草头圈子"]},
            {"name": "沈大成", "cuisine": "上海点心", "avg_price": 30, "rating": 4.5, "specialties": ["条头糕", "双酿团", "青团"]},
        ],
        "attractions": [
            {"name": "外滩", "type": "城市地标", "price": 0, "rating": 4.9, "description": "万国建筑博览群，夜景绝美"},
            {"name": "东方明珠", "type": "城市地标", "price": 120, "rating": 4.7, "description": "上海电视塔，透明观光廊"},
            {"name": "豫园", "type": "历史文化", "price": 40, "rating": 4.6, "description": "明代古典园林，城隍庙商圈"},
            {"name": "上海迪士尼乐园", "type": "主题公园", "price": 475, "rating": 4.8, "description": "中国大陆首座迪士尼"},
            {"name": "田子坊", "type": "文创街区", "price": 0, "rating": 4.5, "description": "弄堂里的艺术街区"},
            {"name": "新天地", "type": "时尚街区", "price": 0, "rating": 4.6, "description": "石库门建筑改造"},
            {"name": "南京路步行街", "type": "购物商圈", "price": 0, "rating": 4.5, "description": "中华商业第一街"},
            {"name": "中华艺术宫", "type": "博物馆", "price": 0, "rating": 4.5, "description": "世博会中国馆"},
            {"name": "上海博物馆", "type": "博物馆", "price": 0, "rating": 4.7, "description": "中国古代艺术博物馆"},
            {"name": "朱家角古镇", "type": "古镇风情", "price": 0, "rating": 4.5, "description": "上海版周庄"},
            {"name": "迪士尼小镇", "type": "购物商圈", "price": 0, "rating": 4.4, "description": "迪士尼配套商业区"},
            {"name": "武康路", "type": "历史街区", "price": 0, "rating": 4.6, "description": "网红打卡地，武康大楼"},
            {"name": "思南公馆", "type": "历史街区", "price": 0, "rating": 4.5, "description": "花园洋房建筑群"},
            {"name": "上海科技馆", "type": "博物馆", "price": 60, "rating": 4.5, "description": "科普教育基地"},
            {"name": "欢乐谷", "type": "主题公园", "price": 230, "rating": 4.4, "description": "华侨城主题乐园"},
        ],
    },
    "烟台": {
        "province": "山东",
        "hotels": [
            {"name": "烟台希尔顿酒店", "type": "豪华型", "price_per_night": 880, "rating": 4.7, "facilities": ["WiFi", "泳池", "海景"], "address": "莱山区滨海路"},
            {"name": "烟台海滨青旅", "type": "经济型", "price_per_night": 69, "rating": 4.3, "facilities": ["WiFi"], "address": "芝罘区海滨"},
        ],
        "restaurants": [
            {"name": "蓬莱小面", "cuisine": "烟台小吃", "avg_price": 15, "rating": 4.6, "specialties": ["蓬莱小面", "烟台焖子", "鲅鱼水饺"]},
            {"name": "渔人码头", "cuisine": "海鲜", "avg_price": 128, "rating": 4.6, "specialties": ["海鲜", "烧烤", "啤酒"]},
            {"name": "烟台大饭店", "cuisine": "鲁菜", "avg_price": 108, "rating": 4.6, "specialties": ["葱烧海参", "九转大肠", "爆炒腰花"]},
            {"name": "东山海鲜市场", "cuisine": "海鲜", "avg_price": 88, "rating": 4.5, "specialties": ["清蒸螃蟹", "辣炒蛤蜊", "烤生蚝"]},
            {"name": "烟台焖子", "cuisine": "烟台小吃", "avg_price": 15, "rating": 4.5, "specialties": ["焖子", "烟台大樱桃", "海肠饺子"]},
            {"name": "蓬莱海鲜大排档", "cuisine": "海鲜", "avg_price": 100, "rating": 4.5, "specialties": ["海鲜大咖", "鲅鱼水饺", "海胆蒸蛋"]},
            {"name": "烟台啤酒屋", "cuisine": "烧烤", "avg_price": 68, "rating": 4.4, "specialties": ["烤鱿鱼", "烤海鲜", "烟台啤酒"]},
            {"name": "福山大面", "cuisine": "面食", "avg_price": 25, "rating": 4.5, "specialties": ["福山大面", "海鲜面", "打卤面"]},
        ],
        "attractions": [
            {"name": "蓬莱阁", "type": "历史文化", "price": 100, "rating": 4.8, "description": "人间仙境，八仙过海传说"},
            {"name": "长岛", "type": "海岛风光", "price": 120, "rating": 4.7, "description": "海上仙山，最美海岛"},
            {"name": "烟台山", "type": "历史文化", "price": 50, "rating": 4.6, "description": "近代建筑群，领事馆旧址"},
            {"name": "养马岛", "type": "海岛风光", "price": 0, "rating": 4.5, "description": "天马行空，网红海岛"},
            {"name": "张裕葡萄酒博物馆", "type": "工业旅游", "price": 50, "rating": 4.5, "description": "百年酒庄"},
            {"name": "金沙滩", "type": "海滩风光", "price": 0, "rating": 4.5, "description": "中国北方第一滩"},
            {"name": "南山大佛", "type": "佛教圣地", "price": 120, "rating": 4.5, "description": "世界最大锡青铜坐佛"},
            {"name": "烟台海昌渔人码头", "type": "度假区", "price": 100, "rating": 4.4, "description": "海洋主题乐园"},
            {"name": "崆峒岛", "type": "海岛风光", "price": 80, "rating": 4.4, "description": "烟台最美海岛"},
            {"name": "烟台植物园", "type": "自然生态", "price": 30, "rating": 4.3, "description": "城市绿肺"},
            {"name": "昆嵛山", "type": "自然风光", "price": 40, "rating": 4.5, "description": "道教全真派发祥地"},
            {"name": "烟台大学", "type": "高校参观", "price": 0, "rating": 4.3, "description": "最美海边大学"},
            {"name": "月亮湾", "type": "自然风光", "price": 0, "rating": 4.4, "description": "天然海水浴场"},
            {"name": "烟台国际博览中心", "type": "现代建筑", "price": 0, "rating": 4.3, "description": "烟台地标建筑"},
            {"name": "塔山风景区", "type": "自然风光", "price": 30, "rating": 4.3, "description": "登高望远，俯瞰烟台"},
        ],
    },
    "北京": {
        "province": "北京",
        "hotels": [
            {"name": "北京王府井文华东方酒店", "type": "豪华型", "price_per_night": 2200, "rating": 4.9, "facilities": ["WiFi", "泳池", "SPA", "米其林餐厅"], "address": "东城区王府井大街269号"},
            {"name": "北京前门皇家驿栈", "type": "高档型", "price_per_night": 680, "rating": 4.6, "facilities": ["WiFi", "餐厅", "健身房"], "address": "东城区前门大街48号"},
            {"name": "北京三里屯青旅", "type": "经济型", "price_per_night": 168, "rating": 4.4, "facilities": ["WiFi", "公共厨房"], "address": "朝阳区三里屯路"},
        ],
        "restaurants": [
            {"name": "全聚德烤鸭店", "cuisine": "京菜", "avg_price": 168, "rating": 4.6, "specialties": ["烤鸭", "芥末鸭掌", "火燎鸭心"]},
            {"name": "海底捞火锅", "cuisine": "火锅", "avg_price": 128, "rating": 4.7, "specialties": ["番茄锅底", "捞派毛肚", "虾滑"]},
            {"name": "护国寺小吃", "cuisine": "北京小吃", "avg_price": 35, "rating": 4.5, "specialties": ["豆汁", "焦圈", "驴打滚"]},
            {"name": "四季民福烤鸭店", "cuisine": "京菜", "avg_price": 158, "rating": 4.7, "specialties": ["烤鸭", "芥末鸭掌", "小吊梨汤"]},
            {"name": "东来顺饭庄", "cuisine": "涮羊肉", "avg_price": 128, "rating": 4.6, "specialties": ["铜锅涮肉", "手切羊肉", "糖蒜"]},
            {"name": "便宜坊烤鸭", "cuisine": "京菜", "avg_price": 148, "rating": 4.5, "specialties": ["焖炉烤鸭", "芥末鸭掌", "盐水鸭肝"]},
            {"name": "姚记炒肝", "cuisine": "北京小吃", "avg_price": 25, "rating": 4.4, "specialties": ["炒肝", "卤煮火烧", "爆肚"]},
            {"name": "北京炸酱面大王", "cuisine": "面食", "avg_price": 35, "rating": 4.4, "specialties": ["炸酱面", "打卤面", "麻酱面"]},
        ],
        "attractions": [
            {"name": "故宫博物院", "type": "世界文化遗产", "price": 60, "rating": 4.9, "description": "明清两代皇宫"},
            {"name": "八达岭长城", "type": "世界文化遗产", "price": 40, "rating": 4.8, "description": "万里长城最精华段"},
            {"name": "天坛公园", "type": "世界文化遗产", "price": 15, "rating": 4.7, "description": "明清祭天场所"},
            {"name": "颐和园", "type": "皇家园林", "price": 30, "rating": 4.8, "description": "中国最大皇家园林"},
            {"name": "天安门广场", "type": "文化地标", "price": 0, "rating": 4.7, "description": "世界最大城市广场"},
            {"name": "南锣鼓巷", "type": "历史街区", "price": 0, "rating": 4.5, "description": "北京最古老的街区"},
            {"name": "798艺术区", "type": "艺术园区", "price": 0, "rating": 4.5, "description": "当代艺术集聚地"},
            {"name": "什刹海", "type": "自然风光", "price": 0, "rating": 4.5, "description": "老北京风情"},
            {"name": "圆明园", "type": "历史遗迹", "price": 10, "rating": 4.6, "description": "万园之园遗址"},
            {"name": "雍和宫", "type": "佛教圣地", "price": 25, "rating": 4.6, "description": "北京最大藏传佛教寺院"},
            {"name": "国家博物馆", "type": "博物馆", "price": 0, "rating": 4.7, "description": "中国最大博物馆"},
            {"name": "奥林匹克公园", "type": "现代都市", "price": 0, "rating": 4.5, "description": "鸟巢、水立方"},
            {"name": "明十三陵", "type": "世界文化遗产", "price": 40, "rating": 4.5, "description": "明朝皇帝陵墓群"},
            {"name": "景山公园", "type": "皇家园林", "price": 2, "rating": 4.5, "description": "俯瞰故宫最佳位置"},
            {"name": "北海公园", "type": "皇家园林", "price": 10, "rating": 4.5, "description": "让我们荡起双桨"},
        ],
    },
    "成都": {
        "province": "四川",
        "hotels": [
            {"name": "成都博舍酒店", "type": "豪华型", "price_per_night": 1500, "rating": 4.9, "facilities": ["WiFi", "泳池", "SPA"], "address": "锦江区笔帖式街81号"},
            {"name": "成都宽窄巷子亚朵酒店", "type": "高档型", "price_per_night": 520, "rating": 4.7, "facilities": ["WiFi", "餐厅", "健身房"], "address": "青羊区宽窄巷子附近"},
            {"name": "成都梦之旅青旅", "type": "经济型", "price_per_night": 98, "rating": 4.4, "facilities": ["WiFi", "公共厨房"], "address": "武侯区锦里附近"},
        ],
        "restaurants": [
            {"name": "大龙燚火锅", "cuisine": "火锅", "avg_price": 108, "rating": 4.7, "specialties": ["麻辣锅底", "鲜毛肚", "鸭肠"]},
            {"name": "陈麻婆豆腐", "cuisine": "川菜", "avg_price": 58, "rating": 4.6, "specialties": ["麻婆豆腐", "回锅肉", "宫保鸡丁"]},
            {"name": "龙抄手总店", "cuisine": "成都小吃", "avg_price": 42, "rating": 4.5, "specialties": ["抄手", "钟水饺", "赖汤圆"]},
            {"name": "蜀大侠火锅", "cuisine": "火锅", "avg_price": 128, "rating": 4.6, "specialties": ["牛肉火锅", "毛肚", "黄喉"]},
            {"name": "集渔泰式海鲜火锅", "cuisine": "泰式火锅", "avg_price": 158, "rating": 4.5, "specialties": ["冬阴功锅底", "海鲜", "甜品"]},
            {"name": "成都吃客", "cuisine": "川菜", "avg_price": 88, "rating": 4.6, "specialties": ["裸奔坨坨虾", "烤鱼", "冒菜"]},
            {"name": "甘食记肥肠粉", "cuisine": "成都小吃", "avg_price": 25, "rating": 4.5, "specialties": ["肥肠粉", "锅盔", "军屯锅盔"]},
            {"name": "双流老妈兔头", "cuisine": "成都小吃", "avg_price": 35, "rating": 4.5, "specialties": ["兔头", "冷吃兔", "钵钵鸡"]},
        ],
        "attractions": [
            {"name": "大熊猫繁育研究基地", "type": "自然生态", "price": 55, "rating": 4.8, "description": "近距离观看大熊猫"},
            {"name": "武侯祠", "type": "历史文化", "price": 50, "rating": 4.7, "description": "三国文化圣地"},
            {"name": "锦里古街", "type": "民俗风情", "price": 0, "rating": 4.6, "description": "小吃一条街"},
            {"name": "宽窄巷子", "type": "历史文化", "price": 0, "rating": 4.7, "description": "清朝古街区"},
            {"name": "都江堰", "type": "世界文化遗产", "price": 80, "rating": 4.8, "description": "水利工程奇迹"},
            {"name": "青城山", "type": "自然风光", "price": 80, "rating": 4.7, "description": "道教圣地"},
            {"name": "杜甫草堂", "type": "历史文化", "price": 50, "rating": 4.6, "description": "诗圣故居"},
            {"name": "金沙遗址博物馆", "type": "博物馆", "price": 70, "rating": 4.6, "description": "古蜀文明"},
            {"name": "成都博物馆", "type": "博物馆", "price": 0, "rating": 4.5, "description": "了解成都历史"},
            {"name": "文殊院", "type": "佛教圣地", "price": 0, "rating": 4.5, "description": "成都最古老寺庙"},
            {"name": "望江楼公园", "type": "城市公园", "price": 0, "rating": 4.4, "description": "竹林公园"},
            {"name": "人民公园", "type": "城市公园", "price": 0, "rating": 4.5, "description": "喝茶掏耳朵"},
            {"name": "东郊记忆", "type": "文创街区", "price": 0, "rating": 4.4, "description": "工业遗址改造"},
            {"name": "黄龙溪古镇", "type": "古镇风情", "price": 0, "rating": 4.5, "description": "千年水码头"},
            {"name": "峨眉山", "type": "自然风光", "price": 160, "rating": 4.8, "description": "佛教四大名山之一"},
        ],
    },
    "西安": {
        "province": "陕西",
        "hotels": [
            {"name": "西安威斯汀酒店", "type": "豪华型", "price_per_night": 1200, "rating": 4.8, "facilities": ["WiFi", "泳池", "SPA"], "address": "碑林区雁塔北路"},
            {"name": "西安钟楼亚朵酒店", "type": "高档型", "price_per_night": 480, "rating": 4.6, "facilities": ["WiFi", "餐厅", "健身房"], "address": "碑林区东大街"},
            {"name": "西安湘子门国际青旅", "type": "经济型", "price_per_night": 89, "rating": 4.5, "facilities": ["WiFi", "公共厨房"], "address": "碑林区湘子门街"},
        ],
        "restaurants": [
            {"name": "老孙家羊肉泡馍", "cuisine": "陕菜", "avg_price": 48, "rating": 4.7, "specialties": ["羊肉泡馍", "肉夹馍", "凉皮"]},
            {"name": "德发长饺子馆", "cuisine": "饺子宴", "avg_price": 68, "rating": 4.6, "specialties": ["饺子宴", "酸汤水饺", "锅贴"]},
            {"name": "永兴坊美食街", "cuisine": "陕西小吃", "avg_price": 38, "rating": 4.5, "specialties": ["biangbiang面", "肉丸胡辣汤", "甑糕"]},
            {"name": "同盛祥", "cuisine": "清真菜", "avg_price": 58, "rating": 4.6, "specialties": ["牛羊肉泡馍", "烤肉", "酸梅汤"]},
            {"name": "春发生", "cuisine": "陕西小吃", "avg_price": 35, "rating": 4.5, "specialties": ["葫芦头泡馍", "油泼面", "臊子面"]},
            {"name": "贾三灌汤包", "cuisine": "清真小吃", "avg_price": 30, "rating": 4.5, "specialties": ["灌汤包", "八宝粥", "麻酱凉皮"]},
            {"name": "盛志望麻酱酿皮", "cuisine": "陕西小吃", "avg_price": 15, "rating": 4.4, "specialties": ["麻酱酿皮", "凉皮", "冰峰"]},
            {"name": "魏家凉皮", "cuisine": "陕西小吃", "avg_price": 20, "rating": 4.4, "specialties": ["秘制凉皮", "肉夹馍", "凉皮"]},
        ],
        "attractions": [
            {"name": "秦始皇兵马俑", "type": "世界文化遗产", "price": 120, "rating": 4.9, "description": "世界第八大奇迹"},
            {"name": "西安城墙", "type": "历史古迹", "price": 54, "rating": 4.8, "description": "中国保存最完整古城墙"},
            {"name": "大雁塔", "type": "历史古迹", "price": 40, "rating": 4.7, "description": "唐代佛塔"},
            {"name": "华清宫", "type": "历史遗迹", "price": 120, "rating": 4.6, "description": "唐代皇家温泉"},
            {"name": "回民街", "type": "美食街区", "price": 0, "rating": 4.5, "description": "西安美食集中地"},
            {"name": "陕西历史博物馆", "type": "博物馆", "price": 0, "rating": 4.8, "description": "中国第一座大型博物馆"},
            {"name": "大唐不夜城", "type": "现代都市", "price": 0, "rating": 4.6, "description": "盛唐文化步行街"},
            {"name": "钟鼓楼", "type": "历史古迹", "price": 50, "rating": 4.6, "description": "西安地标"},
            {"name": "碑林博物馆", "type": "博物馆", "price": 50, "rating": 4.6, "description": "书法艺术宝库"},
            {"name": "小雁塔", "type": "历史古迹", "price": 0, "rating": 4.5, "description": "唐代佛塔"},
            {"name": "大明宫国家遗址公园", "type": "历史遗迹", "price": 60, "rating": 4.5, "description": "唐代皇宫遗址"},
            {"name": "华山", "type": "自然风光", "price": 160, "rating": 4.8, "description": "奇险天下第一山"},
            {"name": "永兴坊", "type": "美食街区", "price": 0, "rating": 4.4, "description": "摔碗酒网红地"},
            {"name": "曲江海洋极地公园", "type": "主题公园", "price": 180, "rating": 4.4, "description": "海洋世界"},
            {"name": "大唐芙蓉园", "type": "主题公园", "price": 120, "rating": 4.5, "description": "唐代园林"},
        ],
    },
    "杭州": {
        "province": "浙江",
        "hotels": [
            {"name": "杭州西子湖四季酒店", "type": "豪华型", "price_per_night": 2800, "rating": 4.9, "facilities": ["WiFi", "泳池", "SPA"], "address": "西湖区灵隐路5号"},
            {"name": "杭州西湖亚朵酒店", "type": "高档型", "price_per_night": 580, "rating": 4.7, "facilities": ["WiFi", "餐厅", "健身房"], "address": "西湖区北山路"},
            {"name": "杭州青旅", "type": "经济型", "price_per_night": 128, "rating": 4.4, "facilities": ["WiFi", "公共厨房"], "address": "上城区河坊街"},
        ],
        "restaurants": [
            {"name": "楼外楼", "cuisine": "杭帮菜", "avg_price": 128, "rating": 4.7, "specialties": ["西湖醋鱼", "东坡肉", "龙井虾仁"]},
            {"name": "外婆家", "cuisine": "杭帮菜", "avg_price": 68, "rating": 4.6, "specialties": ["茶香鸡", "麻婆豆腐", "绿茶饼"]},
            {"name": "知味观", "cuisine": "杭帮菜", "avg_price": 58, "rating": 4.5, "specialties": ["小笼包", "猫耳朵", "片儿川"]},
            {"name": "新白鹿餐厅", "cuisine": "杭帮菜", "avg_price": 65, "rating": 4.5, "specialties": ["蛋黄鸡翅", "糖醋里脊", "绿茶饼"]},
            {"name": "弄堂里", "cuisine": "杭帮菜", "avg_price": 78, "rating": 4.5, "specialties": ["酱鸭", "西湖藕粉", "桂花糕"]},
            {"name": "奎元馆", "cuisine": "面食", "avg_price": 45, "rating": 4.5, "specialties": ["虾爆鳝面", "片儿川", "拌川"]},
            {"name": "河坊街小吃", "cuisine": "小吃", "avg_price": 25, "rating": 4.4, "specialties": ["定胜糕", "葱包桧", "西湖藕粉"]},
            {"name": "楼外楼孤山店", "cuisine": "杭帮菜", "avg_price": 158, "rating": 4.6, "specialties": ["宋嫂鱼羹", "叫化童鸡", "西湖莼菜汤"]},
        ],
        "attractions": [
            {"name": "西湖", "type": "世界文化遗产", "price": 0, "rating": 4.9, "description": "人间天堂"},
            {"name": "灵隐寺", "type": "佛教圣地", "price": 75, "rating": 4.8, "description": "江南名刹"},
            {"name": "千岛湖", "type": "自然风光", "price": 150, "rating": 4.7, "description": "天下第一秀水"},
            {"name": "西溪湿地", "type": "自然生态", "price": 80, "rating": 4.6, "description": "城市湿地"},
            {"name": "宋城", "type": "主题公园", "price": 310, "rating": 4.5, "description": "千古情演出"},
            {"name": "河坊街", "type": "历史街区", "price": 0, "rating": 4.5, "description": "南宋御街"},
            {"name": "九溪烟树", "type": "自然风光", "price": 0, "rating": 4.6, "description": "徒步圣地"},
            {"name": "雷峰塔", "type": "历史古迹", "price": 40, "rating": 4.6, "description": "白蛇传传说"},
            {"name": "龙井村", "type": "自然风光", "price": 0, "rating": 4.5, "description": "龙井茶乡"},
            {"name": "良渚古城遗址", "type": "世界文化遗产", "price": 80, "rating": 4.7, "description": "五千年文明"},
            {"name": "京杭大运河", "type": "世界文化遗产", "price": 0, "rating": 4.5, "description": "世界最长运河"},
            {"name": "钱塘江", "type": "自然风光", "price": 0, "rating": 4.5, "description": "钱塘江大潮"},
            {"name": "中国美术学院", "type": "高校参观", "price": 0, "rating": 4.5, "description": "艺术殿堂"},
            {"name": "浙江大学", "type": "高校参观", "price": 0, "rating": 4.4, "description": "中国顶尖大学"},
            {"name": "湘湖", "type": "自然风光", "price": 0, "rating": 4.5, "description": "西湖姊妹湖"},
        ],
    },
    "武汉": {
        "province": "湖北",
        "hotels": [
            {"name": "武汉光谷希尔顿酒店", "type": "豪华型", "price_per_night": 880, "rating": 4.7, "facilities": ["WiFi", "泳池", "健身房"], "address": "东湖高新区光谷大道"},
            {"name": "武汉户部巷青旅", "type": "经济型", "price_per_night": 69, "rating": 4.3, "facilities": ["WiFi"], "address": "武昌区户部巷"},
        ],
        "restaurants": [
            {"name": "蔡林记", "cuisine": "武汉小吃", "avg_price": 15, "rating": 4.7, "specialties": ["热干面", "三鲜豆皮", "糊汤粉"]},
            {"name": "靓靓蒸虾", "cuisine": "小龙虾", "avg_price": 128, "rating": 4.6, "specialties": ["油焖大虾", "蒜蓉虾", "清蒸虾"]},
            {"name": "老通城", "cuisine": "武汉小吃", "avg_price": 25, "rating": 4.5, "specialties": ["三鲜豆皮", "谈炎记水饺"]},
            {"name": "艳阳天", "cuisine": "鄂菜", "avg_price": 88, "rating": 4.5, "specialties": ["排骨藕汤", "武昌鱼", "沔阳三蒸"]},
            {"name": "小桃园煨汤", "cuisine": "湖北菜", "avg_price": 58, "rating": 4.5, "specialties": ["煨汤", "排骨藕汤", "鸡汤"]},
            {"name": "亢龙太子酒轩", "cuisine": "鄂菜", "avg_price": 98, "rating": 4.5, "specialties": ["太子鱼", "清蒸武昌鱼", "红菜薹炒腊肉"]},
            {"name": "周黑鸭", "cuisine": "卤味", "avg_price": 35, "rating": 4.5, "specialties": ["鸭脖", "鸭翅", "鸭锁骨"]},
            {"name": "德华楼", "cuisine": "武汉小吃", "avg_price": 20, "rating": 4.4, "specialties": ["包子", "年糕", "汤圆"]},
        ],
        "attractions": [
            {"name": "黄鹤楼", "type": "历史文化", "price": 70, "rating": 4.8, "description": "江南三大名楼之一"},
            {"name": "东湖", "type": "自然风光", "price": 0, "rating": 4.7, "description": "中国最大城中湖"},
            {"name": "武汉大学", "type": "高校参观", "price": 0, "rating": 4.6, "description": "中国最美大学"},
            {"name": "户部巷", "type": "美食街区", "price": 0, "rating": 4.5, "description": "武汉早点一条街"},
            {"name": "长江大桥", "type": "城市地标", "price": 0, "rating": 4.6, "description": "万里长江第一桥"},
            {"name": "昙华林", "type": "文创街区", "price": 0, "rating": 4.5, "description": "文艺青年聚集地"},
            {"name": "汉口江滩", "type": "城市景观", "price": 0, "rating": 4.5, "description": "夜景绝美"},
            {"name": "武汉欢乐谷", "type": "主题公园", "price": 200, "rating": 4.5, "description": "华侨城主题乐园"},
            {"name": "湖北省博物馆", "type": "博物馆", "price": 0, "rating": 4.7, "description": "曾侯乙编钟"},
            {"name": "古德寺", "type": "佛教圣地", "price": 8, "rating": 4.5, "description": "异域风情寺庙"},
            {"name": "光谷步行街", "type": "购物商圈", "price": 0, "rating": 4.4, "description": "武汉最繁华商圈"},
            {"name": "东湖绿道", "type": "城市景观", "price": 0, "rating": 4.5, "description": "骑行圣地"},
            {"name": "江汉路步行街", "type": "购物商圈", "price": 0, "rating": 4.5, "description": "百年商业街"},
            {"name": "归元禅寺", "type": "佛教圣地", "price": 10, "rating": 4.4, "description": "武汉四大佛教丛林"},
            {"name": "知音号", "type": "演艺娱乐", "price": 298, "rating": 4.5, "description": "漂移式体验剧"},
        ],
    },
    "南京": {
        "province": "江苏",
        "hotels": [
            {"name": "南京香格里拉大酒店", "type": "豪华型", "price_per_night": 1500, "rating": 4.8, "facilities": ["WiFi", "泳池", "SPA"], "address": "鼓楼区中央路329号"},
            {"name": "南京夫子庙青旅", "type": "经济型", "price_per_night": 89, "rating": 4.4, "facilities": ["WiFi"], "address": "秦淮区贡院街"},
        ],
        "restaurants": [
            {"name": "南京大牌档", "cuisine": "南京菜", "avg_price": 88, "rating": 4.7, "specialties": ["盐水鸭", "鸭血粉丝汤", "狮子头"]},
            {"name": "回味鸭血粉丝汤", "cuisine": "南京小吃", "avg_price": 25, "rating": 4.6, "specialties": ["鸭血粉丝汤", "锅贴", "汤包"]},
            {"name": "绿柳居", "cuisine": "素食", "avg_price": 65, "rating": 4.5, "specialties": ["素什锦", "素鹅", "素鸡"]},
            {"name": "韩复兴", "cuisine": "卤味", "avg_price": 45, "rating": 4.5, "specialties": ["盐水鸭", "板鸭", "鸭肫"]},
            {"name": "奇芳阁", "cuisine": "南京小吃", "avg_price": 35, "rating": 4.5, "specialties": ["鸭油酥烧饼", "什锦菜包", "麻油干丝"]},
            {"name": "莲湖糕团店", "cuisine": "南京小吃", "avg_price": 20, "rating": 4.4, "specialties": ["赤豆元宵", "桂花糕", "马蹄糕"]},
            {"name": "南京精菜馆", "cuisine": "南京菜", "avg_price": 108, "rating": 4.5, "specialties": ["美人肝", "蛋烧卖", "松鼠鱼"]},
            {"name": "马祥兴菜馆", "cuisine": "清真菜", "avg_price": 78, "rating": 4.4, "specialties": ["美人肝", "凤尾虾", "蛋烧卖"]},
        ],
        "attractions": [
            {"name": "中山陵", "type": "历史文化", "price": 0, "rating": 4.9, "description": "孙中山先生陵墓"},
            {"name": "夫子庙-秦淮河", "type": "历史文化", "price": 0, "rating": 4.7, "description": "桨声灯影"},
            {"name": "明孝陵", "type": "世界文化遗产", "price": 70, "rating": 4.8, "description": "明太祖陵墓"},
            {"name": "总统府", "type": "历史文化", "price": 35, "rating": 4.6, "description": "中国近代史博物馆"},
            {"name": "南京博物院", "type": "博物馆", "price": 0, "rating": 4.8, "description": "中国三大博物馆之一"},
            {"name": "玄武湖", "type": "自然风光", "price": 0, "rating": 4.6, "description": "江南最大城内公园"},
            {"name": "老门东", "type": "历史街区", "price": 0, "rating": 4.5, "description": "传统民居建筑群"},
            {"name": "紫金山", "type": "自然风光", "price": 0, "rating": 4.5, "description": "金陵龙脉"},
            {"name": "鸡鸣寺", "type": "佛教圣地", "price": 10, "rating": 4.5, "description": "南朝四百八十寺"},
            {"name": "雨花台", "type": "红色旅游", "price": 0, "rating": 4.5, "description": "烈士陵园"},
            {"name": "牛首山", "type": "佛教圣地", "price": 98, "rating": 4.5, "description": "佛顶宫"},
            {"name": "栖霞山", "type": "自然风光", "price": 25, "rating": 4.5, "description": "红枫圣地"},
            {"name": "先锋书店", "type": "文创街区", "price": 0, "rating": 4.5, "description": "最美书店"},
            {"name": "1912街区", "type": "时尚街区", "price": 0, "rating": 4.4, "description": "酒吧街"},
            {"name": "南京眼步行桥", "type": "城市地标", "price": 0, "rating": 4.4, "description": "青奥会地标"},
        ],
    },
    # ==================== 云南地区 ====================
    "大理": {
        "province": "云南",
        "hotels": [
            {"name": "大理古城既下山酒店", "type": "高档型", "price_per_night": 680, "rating": 4.8, "facilities": ["WiFi", "停车场", "餐厅"]},
            {"name": "洱海天域海景民宿", "type": "特色民宿", "price_per_night": 520, "rating": 4.7, "facilities": ["WiFi", "海景房", "早餐"]},
            {"name": "大理青旅背包客栈", "type": "经济型", "price_per_night": 128, "rating": 4.3, "facilities": ["WiFi", "公共厨房"]},
        ],
        "restaurants": [
            {"name": "段公子·大理私房菜", "cuisine": "云南菜", "avg_price": 88, "rating": 4.7, "specialties": ["酸辣鱼", "乳扇", "鲜花饼"]},
            {"name": "翠田餐厅", "cuisine": "白族菜", "avg_price": 65, "rating": 4.6, "specialties": ["砂锅鱼", "凉鸡米线", "饵块"]},
            {"name": "坏猴子酒吧餐厅", "cuisine": "融合菜", "avg_price": 52, "rating": 4.4, "specialties": ["汉堡", "意面", "精酿啤酒"]},
            {"name": "复兴路上段小吃", "cuisine": "白族小吃", "avg_price": 25, "rating": 4.5, "specialties": ["喜洲粑粑", "烤乳扇", "凉鸡米线"]},
            {"name": "人民路美食", "cuisine": "云南菜", "avg_price": 55, "rating": 4.5, "specialties": ["烤鱼", "菌菇火锅", "鲜花饼"]},
            {"name": "双廊海景餐厅", "cuisine": "海鲜", "avg_price": 98, "rating": 4.5, "specialties": ["烤鱼", "海鲜拼盘", "啤酒"]},
            {"name": "古城小吃摊", "cuisine": "小吃", "avg_price": 20, "rating": 4.4, "specialties": ["烤饵块", "米线", "冰粉"]},
            {"name": "喜洲古镇餐厅", "cuisine": "白族菜", "avg_price": 60, "rating": 4.5, "specialties": ["白族八大碗", "喜洲粑粑", "三道茶"]},
        ],
        "attractions": [
            {"name": "洱海", "type": "自然风光", "price": 0, "rating": 4.9, "description": "高原湖泊，骑行环湖"},
            {"name": "大理古城", "type": "历史文化", "price": 0, "rating": 4.7, "description": "白族文化聚集地"},
            {"name": "崇圣寺三塔", "type": "历史古迹", "price": 75, "rating": 4.8, "description": "大理地标"},
            {"name": "苍山", "type": "自然风光", "price": 35, "rating": 4.7, "description": "十九峰十八溪"},
            {"name": "双廊古镇", "type": "古镇风情", "price": 0, "rating": 4.6, "description": "洱海东岸最美小镇"},
            {"name": "喜洲古镇", "type": "古镇风情", "price": 0, "rating": 4.5, "description": "白族民居建筑群"},
            {"name": "南诏风情岛", "type": "海岛风光", "price": 50, "rating": 4.5, "description": "洱海三岛之一"},
            {"name": "蝴蝶泉", "type": "自然风光", "price": 60, "rating": 4.4, "description": "蝴蝶聚会奇观"},
            {"name": "天龙八部影视城", "type": "主题公园", "price": 52, "rating": 4.3, "description": "金庸武侠世界"},
            {"name": "鸡足山", "type": "佛教圣地", "price": 80, "rating": 4.5, "description": "迦叶道场"},
            {"name": "沙溪古镇", "type": "古镇风情", "price": 0, "rating": 4.6, "description": "茶马古道集市"},
            {"name": "巍山古城", "type": "历史街区", "price": 0, "rating": 4.4, "description": "南诏发祥地"},
            {"name": "苍山索道", "type": "自然风光", "price": 150, "rating": 4.5, "description": "俯瞰洱海全景"},
            {"name": "大理大学", "type": "高校参观", "price": 0, "rating": 4.4, "description": "最浪漫大学"},
            {"name": "洱海游船", "type": "自然风光", "price": 142, "rating": 4.5, "description": "洱海全景游览"},
        ],
    },
    "丽江": {
        "province": "云南",
        "hotels": [
            {"name": "丽江和府洲际度假酒店", "type": "豪华型", "price_per_night": 1200, "rating": 4.9, "facilities": ["WiFi", "泳池", "SPA"]},
            {"name": "丽江花间堂问云山庄", "type": "特色民宿", "price_per_night": 480, "rating": 4.7, "facilities": ["WiFi", "花园", "茶室"]},
            {"name": "丽江懒猫青旅", "type": "经济型", "price_per_night": 89, "rating": 4.5, "facilities": ["WiFi", "公共厨房"]},
        ],
        "restaurants": [
            {"name": "阿妈意纳西饮食院", "cuisine": "纳西菜", "avg_price": 78, "rating": 4.8, "specialties": ["纳西烤鱼", "鸡豆凉粉", "腊排骨火锅"]},
            {"name": "88号小吃店", "cuisine": "云南小吃", "avg_price": 35, "rating": 4.6, "specialties": ["米线", "饵丝", "丽江粑粑"]},
            {"name": "滇厨餐厅", "cuisine": "滇菜", "avg_price": 68, "rating": 4.5, "specialties": ["汽锅鸡", "过桥米线", "鲜花饼"]},
            {"name": "钰洁腊排骨", "cuisine": "纳西菜", "avg_price": 65, "rating": 4.6, "specialties": ["腊排骨火锅", "纳西烤肉", "洋芋鸡"]},
            {"name": "唠叨坊私房菜", "cuisine": "纳西菜", "avg_price": 55, "rating": 4.5, "specialties": ["纳西炒饭", "黑山羊火锅", "酸菜鱼"]},
            {"name": "束河三眼井饭馆", "cuisine": "纳西菜", "avg_price": 58, "rating": 4.5, "specialties": ["水性杨花", "丽江粑粑", "米灌肠"]},
            {"name": "大石桥小吃", "cuisine": "小吃", "avg_price": 20, "rating": 4.4, "specialties": ["鸡豆凉粉", "丽江粑粑", "酥油茶"]},
            {"name": "忠义市场烧烤", "cuisine": "烧烤", "avg_price": 45, "rating": 4.4, "specialties": ["烤肉", "烤鱼", "烤豆腐"]},
        ],
        "attractions": [
            {"name": "丽江古城", "type": "世界文化遗产", "price": 0, "rating": 4.8, "description": "纳西族古镇"},
            {"name": "玉龙雪山", "type": "自然风光", "price": 100, "rating": 4.9, "description": "海拔5596米"},
            {"name": "束河古镇", "type": "古镇风情", "price": 0, "rating": 4.6, "description": "更安静的纳西古镇"},
            {"name": "拉市海湿地公园", "type": "自然风光", "price": 30, "rating": 4.5, "description": "候鸟栖息地"},
            {"name": "虎跳峡", "type": "自然奇观", "price": 65, "rating": 4.7, "description": "世界最深峡谷之一"},
            {"name": "泸沽湖", "type": "自然风光", "price": 100, "rating": 4.8, "description": "东方女儿国"},
            {"name": "白沙古镇", "type": "古镇风情", "price": 0, "rating": 4.5, "description": "白沙壁画"},
            {"name": "木府", "type": "历史文化", "price": 40, "rating": 4.5, "description": "纳西族紫禁城"},
            {"name": "黑龙潭公园", "type": "城市公园", "price": 0, "rating": 4.5, "description": "玉龙雪山倒影"},
            {"name": "蓝月谷", "type": "自然风光", "price": 0, "rating": 4.6, "description": "九寨沟般的水景"},
            {"name": "观音峡", "type": "自然风光", "price": 60, "rating": 4.4, "description": "茶马古道关隘"},
            {"name": "束河茶马古道博物馆", "type": "博物馆", "price": 0, "rating": 4.3, "description": "茶马文化"},
            {"name": "丽江千古情", "type": "演艺娱乐", "price": 280, "rating": 4.5, "description": "大型演出"},
            {"name": "玉水寨", "type": "自然风光", "price": 50, "rating": 4.4, "description": "东巴文化圣地"},
            {"name": "文笔山", "type": "自然风光", "price": 30, "rating": 4.3, "description": "俯瞰丽江古城"},
        ],
    },
    "三亚": {
        "province": "海南",
        "hotels": [
            {"name": "三亚亚特兰蒂斯酒店", "type": "豪华型", "price_per_night": 2800, "rating": 4.9, "facilities": ["水族馆", "水上乐园", "私人沙滩"]},
            {"name": "三亚湾红树林度假酒店", "type": "高档型", "price_per_night": 880, "rating": 4.7, "facilities": ["泳池", "沙滩", "餐厅"]},
            {"name": "三亚大东海海景青旅", "type": "经济型", "price_per_night": 158, "rating": 4.3, "facilities": ["WiFi", "海景"]},
        ],
        "restaurants": [
            {"name": "林姐香味海鲜", "cuisine": "海鲜", "avg_price": 158, "rating": 4.8, "specialties": ["清蒸石斑鱼", "椒盐皮皮虾", "蒜蓉扇贝"]},
            {"name": "嗲嗲的椰子鸡", "cuisine": "海南菜", "avg_price": 98, "rating": 4.7, "specialties": ["椰子鸡", "文昌鸡", "清补凉"]},
            {"name": "琼乡阁海南菜餐厅", "cuisine": "琼菜", "avg_price": 75, "rating": 4.6, "specialties": ["东山羊", "和乐蟹", "加积鸭"]},
            {"name": "第一市场海鲜加工", "cuisine": "海鲜", "avg_price": 120, "rating": 4.5, "specialties": ["海鲜加工", "芒果螺", "海胆蒸蛋"]},
            {"name": "抱罗粉", "cuisine": "海南小吃", "avg_price": 18, "rating": 4.5, "specialties": ["抱罗粉", "海南粉", "后安粉"]},
            {"name": "小海豚海鲜广场", "cuisine": "海鲜", "avg_price": 138, "rating": 4.5, "specialties": ["龙虾", "石斑鱼", "生蚝"]},
            {"name": "崖州古城小吃", "cuisine": "小吃", "avg_price": 25, "rating": 4.4, "specialties": ["崖城臭豆腐", "猪肠粑", "椰子饭"]},
            {"name": "春园海鲜广场", "cuisine": "海鲜", "avg_price": 128, "rating": 4.5, "specialties": ["海鲜火锅", "香辣蟹", "椒盐虾"]},
        ],
        "attractions": [
            {"name": "亚龙湾", "type": "海滩风光", "price": 0, "rating": 4.9, "description": "天下第一湾"},
            {"name": "蜈支洲岛", "type": "海岛风光", "price": 144, "rating": 4.8, "description": "中国马尔代夫"},
            {"name": "天涯海角", "type": "文化地标", "price": 68, "rating": 4.5, "description": "浪漫圣地"},
            {"name": "南山文化旅游区", "type": "佛教文化", "price": 129, "rating": 4.7, "description": "108米海上观音"},
            {"name": "呀诺达雨林", "type": "热带雨林", "price": 158, "rating": 4.6, "description": "天然氧吧"},
            {"name": "槟榔谷", "type": "民俗文化", "price": 96, "rating": 4.5, "description": "黎苗风情"},
            {"name": "鹿回头", "type": "城市地标", "price": 42, "rating": 4.5, "description": "俯瞰三亚湾夜景"},
            {"name": "大东海", "type": "海滩风光", "price": 0, "rating": 4.5, "description": "免费公共海滩"},
            {"name": "三亚湾", "type": "海滩风光", "price": 0, "rating": 4.4, "description": "椰梦长廊看日落"},
            {"name": "亚特兰蒂斯水世界", "type": "主题公园", "price": 298, "rating": 4.6, "description": "水上乐园"},
            {"name": "海棠湾免税城", "type": "购物商圈", "price": 0, "rating": 4.5, "description": "免税购物天堂"},
            {"name": "崖州古城", "type": "历史文化", "price": 0, "rating": 4.3, "description": "千年古城"},
            {"name": "南湾猴岛", "type": "自然生态", "price": 163, "rating": 4.4, "description": "猕猴王国"},
            {"name": "热带天堂森林公园", "type": "热带雨林", "price": 158, "rating": 4.5, "description": "非诚勿扰2取景地"},
            {"name": "西岛", "type": "海岛风光", "price": 98, "rating": 4.4, "description": "渔村文化体验"},
        ],
    },
    "北京": {
        "province": "北京",
        "hotels": [
            {"name": "北京王府井文华东方酒店", "type": "豪华型", "price_per_night": 2200, "rating": 4.9, "facilities": ["WiFi", "泳池", "SPA"]},
            {"name": "北京前门皇家驿栈", "type": "高档型", "price_per_night": 680, "rating": 4.6, "facilities": ["WiFi", "餐厅", "健身房"]},
            {"name": "北京三里屯青旅", "type": "经济型", "price_per_night": 168, "rating": 4.4, "facilities": ["WiFi", "公共厨房"]},
        ],
        "restaurants": [
            {"name": "全聚德烤鸭店", "cuisine": "京菜", "avg_price": 168, "rating": 4.6, "specialties": ["烤鸭", "芥末鸭掌", "火燎鸭心"]},
            {"name": "四季民福烤鸭店", "cuisine": "京菜", "avg_price": 158, "rating": 4.7, "specialties": ["烤鸭", "小吊梨汤", "芥末鸭掌"]},
            {"name": "护国寺小吃", "cuisine": "北京小吃", "avg_price": 35, "rating": 4.5, "specialties": ["豆汁", "焦圈", "驴打滚"]},
            {"name": "海底捞火锅", "cuisine": "火锅", "avg_price": 128, "rating": 4.7, "specialties": ["番茄锅底", "捞派毛肚", "虾滑"]},
            {"name": "东来顺饭庄", "cuisine": "涮羊肉", "avg_price": 128, "rating": 4.6, "specialties": ["铜锅涮肉", "手切羊肉", "糖蒜"]},
            {"name": "便宜坊烤鸭", "cuisine": "京菜", "avg_price": 148, "rating": 4.5, "specialties": ["焖炉烤鸭", "盐水鸭肝", "芥末鸭掌"]},
            {"name": "姚记炒肝", "cuisine": "北京小吃", "avg_price": 25, "rating": 4.4, "specialties": ["炒肝", "卤煮火烧", "爆肚"]},
            {"name": "北京炸酱面大王", "cuisine": "面食", "avg_price": 35, "rating": 4.4, "specialties": ["炸酱面", "打卤面", "麻酱面"]},
        ],
        "attractions": [
            {"name": "故宫博物院", "type": "世界文化遗产", "price": 60, "rating": 4.9, "description": "明清两代皇宫"},
            {"name": "八达岭长城", "type": "世界文化遗产", "price": 40, "rating": 4.8, "description": "万里长城最精华段"},
            {"name": "天坛公园", "type": "世界文化遗产", "price": 15, "rating": 4.7, "description": "明清祭天场所"},
            {"name": "颐和园", "type": "皇家园林", "price": 30, "rating": 4.8, "description": "中国最大皇家园林"},
            {"name": "天安门广场", "type": "文化地标", "price": 0, "rating": 4.7, "description": "世界最大城市广场"},
            {"name": "南锣鼓巷", "type": "历史街区", "price": 0, "rating": 4.5, "description": "北京最古老的街区"},
            {"name": "798艺术区", "type": "艺术园区", "price": 0, "rating": 4.5, "description": "当代艺术集聚地"},
            {"name": "什刹海", "type": "自然风光", "price": 0, "rating": 4.5, "description": "老北京风情"},
            {"name": "圆明园", "type": "历史遗迹", "price": 10, "rating": 4.6, "description": "万园之园遗址"},
            {"name": "雍和宫", "type": "佛教圣地", "price": 25, "rating": 4.6, "description": "北京最大藏传佛教寺院"},
            {"name": "国家博物馆", "type": "博物馆", "price": 0, "rating": 4.7, "description": "中国最大博物馆"},
            {"name": "奥林匹克公园", "type": "现代都市", "price": 0, "rating": 4.5, "description": "鸟巢、水立方"},
            {"name": "明十三陵", "type": "世界文化遗产", "price": 40, "rating": 4.5, "description": "明朝皇帝陵墓群"},
            {"name": "景山公园", "type": "皇家园林", "price": 2, "rating": 4.5, "description": "俯瞰故宫最佳位置"},
            {"name": "北海公园", "type": "皇家园林", "price": 10, "rating": 4.5, "description": "让我们荡起双桨"},
        ],
    },
    "成都": {
        "province": "四川",
        "hotels": [
            {"name": "成都博舍酒店", "type": "豪华型", "price_per_night": 1500, "rating": 4.9, "facilities": ["WiFi", "泳池", "SPA"]},
            {"name": "成都宽窄巷子亚朵酒店", "type": "高档型", "price_per_night": 520, "rating": 4.7, "facilities": ["WiFi", "餐厅", "健身房"]},
            {"name": "成都梦之旅青旅", "type": "经济型", "price_per_night": 98, "rating": 4.4, "facilities": ["WiFi", "公共厨房"]},
        ],
        "restaurants": [
            {"name": "大龙燚火锅", "cuisine": "火锅", "avg_price": 108, "rating": 4.7, "specialties": ["麻辣锅底", "鲜毛肚", "鸭肠"]},
            {"name": "陈麻婆豆腐", "cuisine": "川菜", "avg_price": 58, "rating": 4.6, "specialties": ["麻婆豆腐", "回锅肉", "宫保鸡丁"]},
            {"name": "龙抄手总店", "cuisine": "成都小吃", "avg_price": 42, "rating": 4.5, "specialties": ["抄手", "钟水饺", "赖汤圆"]},
            {"name": "蜀大侠火锅", "cuisine": "火锅", "avg_price": 128, "rating": 4.6, "specialties": ["牛肉火锅", "毛肚", "黄喉"]},
            {"name": "集渔泰式海鲜火锅", "cuisine": "泰式火锅", "avg_price": 158, "rating": 4.5, "specialties": ["冬阴功锅底", "海鲜", "甜品"]},
            {"name": "成都吃客", "cuisine": "川菜", "avg_price": 88, "rating": 4.6, "specialties": ["裸奔坨坨虾", "烤鱼", "冒菜"]},
            {"name": "甘食记肥肠粉", "cuisine": "成都小吃", "avg_price": 25, "rating": 4.5, "specialties": ["肥肠粉", "锅盔", "军屯锅盔"]},
            {"name": "双流老妈兔头", "cuisine": "成都小吃", "avg_price": 35, "rating": 4.5, "specialties": ["兔头", "冷吃兔", "钵钵鸡"]},
        ],
        "attractions": [
            {"name": "大熊猫繁育研究基地", "type": "自然生态", "price": 55, "rating": 4.8, "description": "近距离观看大熊猫"},
            {"name": "武侯祠", "type": "历史文化", "price": 50, "rating": 4.7, "description": "三国文化圣地"},
            {"name": "锦里古街", "type": "民俗风情", "price": 0, "rating": 4.6, "description": "小吃一条街"},
            {"name": "宽窄巷子", "type": "历史文化", "price": 0, "rating": 4.7, "description": "清朝古街区"},
            {"name": "都江堰", "type": "世界文化遗产", "price": 80, "rating": 4.8, "description": "水利工程奇迹"},
            {"name": "青城山", "type": "自然风光", "price": 80, "rating": 4.7, "description": "道教圣地"},
            {"name": "杜甫草堂", "type": "历史文化", "price": 50, "rating": 4.6, "description": "诗圣故居"},
            {"name": "金沙遗址博物馆", "type": "博物馆", "price": 70, "rating": 4.6, "description": "古蜀文明"},
            {"name": "成都博物馆", "type": "博物馆", "price": 0, "rating": 4.5, "description": "了解成都历史"},
            {"name": "文殊院", "type": "佛教圣地", "price": 0, "rating": 4.5, "description": "成都最古老寺庙"},
            {"name": "望江楼公园", "type": "城市公园", "price": 0, "rating": 4.4, "description": "竹林公园"},
            {"name": "人民公园", "type": "城市公园", "price": 0, "rating": 4.5, "description": "喝茶掏耳朵"},
            {"name": "东郊记忆", "type": "文创街区", "price": 0, "rating": 4.4, "description": "工业遗址改造"},
            {"name": "黄龙溪古镇", "type": "古镇风情", "price": 0, "rating": 4.5, "description": "千年水码头"},
            {"name": "峨眉山", "type": "自然风光", "price": 160, "rating": 4.8, "description": "佛教四大名山之一"},
        ],
    },
    "西安": {
        "province": "陕西",
        "hotels": [
            {"name": "西安威斯汀酒店", "type": "豪华型", "price_per_night": 1200, "rating": 4.8, "facilities": ["WiFi", "泳池", "SPA"]},
            {"name": "西安钟楼亚朵酒店", "type": "高档型", "price_per_night": 480, "rating": 4.6, "facilities": ["WiFi", "餐厅", "健身房"]},
            {"name": "西安湘子门国际青旅", "type": "经济型", "price_per_night": 89, "rating": 4.5, "facilities": ["WiFi", "公共厨房"]},
        ],
        "restaurants": [
            {"name": "老孙家羊肉泡馍", "cuisine": "陕菜", "avg_price": 48, "rating": 4.7, "specialties": ["羊肉泡馍", "肉夹馍", "凉皮"]},
            {"name": "德发长饺子馆", "cuisine": "饺子宴", "avg_price": 68, "rating": 4.6, "specialties": ["饺子宴", "酸汤水饺", "锅贴"]},
            {"name": "永兴坊美食街", "cuisine": "陕西小吃", "avg_price": 38, "rating": 4.5, "specialties": ["biangbiang面", "肉丸胡辣汤", "甑糕"]},
            {"name": "同盛祥", "cuisine": "清真菜", "avg_price": 58, "rating": 4.6, "specialties": ["牛羊肉泡馍", "烤肉", "酸梅汤"]},
            {"name": "春发生", "cuisine": "陕西小吃", "avg_price": 35, "rating": 4.5, "specialties": ["葫芦头泡馍", "油泼面", "臊子面"]},
            {"name": "贾三灌汤包", "cuisine": "清真小吃", "avg_price": 30, "rating": 4.5, "specialties": ["灌汤包", "八宝粥", "麻酱凉皮"]},
            {"name": "盛志望麻酱酿皮", "cuisine": "陕西小吃", "avg_price": 15, "rating": 4.4, "specialties": ["麻酱酿皮", "凉皮", "冰峰"]},
            {"name": "魏家凉皮", "cuisine": "陕西小吃", "avg_price": 20, "rating": 4.4, "specialties": ["秘制凉皮", "肉夹馍", "凉皮"]},
        ],
        "attractions": [
            {"name": "秦始皇兵马俑", "type": "世界文化遗产", "price": 120, "rating": 4.9, "description": "世界第八大奇迹"},
            {"name": "西安城墙", "type": "历史古迹", "price": 54, "rating": 4.8, "description": "中国保存最完整古城墙"},
            {"name": "大雁塔", "type": "历史古迹", "price": 40, "rating": 4.7, "description": "唐代佛塔"},
            {"name": "华清宫", "type": "历史遗迹", "price": 120, "rating": 4.6, "description": "唐代皇家温泉"},
            {"name": "回民街", "type": "美食街区", "price": 0, "rating": 4.5, "description": "西安美食集中地"},
            {"name": "陕西历史博物馆", "type": "博物馆", "price": 0, "rating": 4.8, "description": "中国第一座大型博物馆"},
            {"name": "大唐不夜城", "type": "现代都市", "price": 0, "rating": 4.6, "description": "盛唐文化步行街"},
            {"name": "钟鼓楼", "type": "历史古迹", "price": 50, "rating": 4.6, "description": "西安地标"},
            {"name": "碑林博物馆", "type": "博物馆", "price": 50, "rating": 4.6, "description": "书法艺术宝库"},
            {"name": "小雁塔", "type": "历史古迹", "price": 0, "rating": 4.5, "description": "唐代佛塔"},
            {"name": "大明宫国家遗址公园", "type": "历史遗迹", "price": 60, "rating": 4.5, "description": "唐代皇宫遗址"},
            {"name": "华山", "type": "自然风光", "price": 160, "rating": 4.8, "description": "奇险天下第一山"},
            {"name": "永兴坊", "type": "美食街区", "price": 0, "rating": 4.4, "description": "摔碗酒网红地"},
            {"name": "曲江海洋极地公园", "type": "主题公园", "price": 180, "rating": 4.4, "description": "海洋世界"},
            {"name": "大唐芙蓉园", "type": "主题公园", "price": 120, "rating": 4.5, "description": "唐代园林"},
        ],
    },
    "杭州": {
        "province": "浙江",
        "hotels": [
            {"name": "杭州西子湖四季酒店", "type": "豪华型", "price_per_night": 2800, "rating": 4.9, "facilities": ["WiFi", "泳池", "SPA"]},
            {"name": "杭州西湖亚朵酒店", "type": "高档型", "price_per_night": 580, "rating": 4.7, "facilities": ["WiFi", "餐厅", "健身房"]},
            {"name": "杭州青旅", "type": "经济型", "price_per_night": 128, "rating": 4.4, "facilities": ["WiFi", "公共厨房"]},
        ],
        "restaurants": [
            {"name": "楼外楼", "cuisine": "杭帮菜", "avg_price": 128, "rating": 4.7, "specialties": ["西湖醋鱼", "东坡肉", "龙井虾仁"]},
            {"name": "外婆家", "cuisine": "杭帮菜", "avg_price": 68, "rating": 4.6, "specialties": ["茶香鸡", "麻婆豆腐", "绿茶饼"]},
            {"name": "知味观", "cuisine": "杭帮菜", "avg_price": 58, "rating": 4.5, "specialties": ["小笼包", "猫耳朵", "片儿川"]},
            {"name": "新白鹿餐厅", "cuisine": "杭帮菜", "avg_price": 65, "rating": 4.5, "specialties": ["蛋黄鸡翅", "糖醋里脊", "绿茶饼"]},
            {"name": "弄堂里", "cuisine": "杭帮菜", "avg_price": 78, "rating": 4.5, "specialties": ["酱鸭", "西湖藕粉", "桂花糕"]},
            {"name": "奎元馆", "cuisine": "面食", "avg_price": 45, "rating": 4.5, "specialties": ["虾爆鳝面", "片儿川", "拌川"]},
            {"name": "河坊街小吃", "cuisine": "小吃", "avg_price": 25, "rating": 4.4, "specialties": ["定胜糕", "葱包桧", "西湖藕粉"]},
            {"name": "楼外楼孤山店", "cuisine": "杭帮菜", "avg_price": 158, "rating": 4.6, "specialties": ["宋嫂鱼羹", "叫化童鸡", "西湖莼菜汤"]},
        ],
        "attractions": [
            {"name": "西湖", "type": "世界文化遗产", "price": 0, "rating": 4.9, "description": "人间天堂"},
            {"name": "灵隐寺", "type": "佛教圣地", "price": 75, "rating": 4.8, "description": "江南名刹"},
            {"name": "千岛湖", "type": "自然风光", "price": 150, "rating": 4.7, "description": "天下第一秀水"},
            {"name": "西溪湿地", "type": "自然生态", "price": 80, "rating": 4.6, "description": "城市湿地"},
            {"name": "宋城", "type": "主题公园", "price": 310, "rating": 4.5, "description": "千古情演出"},
            {"name": "河坊街", "type": "历史街区", "price": 0, "rating": 4.5, "description": "南宋御街"},
            {"name": "九溪烟树", "type": "自然风光", "price": 0, "rating": 4.6, "description": "徒步圣地"},
            {"name": "雷峰塔", "type": "历史古迹", "price": 40, "rating": 4.6, "description": "白蛇传传说"},
            {"name": "龙井村", "type": "自然风光", "price": 0, "rating": 4.5, "description": "龙井茶乡"},
            {"name": "良渚古城遗址", "type": "世界文化遗产", "price": 80, "rating": 4.7, "description": "五千年文明"},
            {"name": "京杭大运河", "type": "世界文化遗产", "price": 0, "rating": 4.5, "description": "世界最长运河"},
            {"name": "钱塘江", "type": "自然风光", "price": 0, "rating": 4.5, "description": "钱塘江大潮"},
            {"name": "中国美术学院", "type": "高校参观", "price": 0, "rating": 4.5, "description": "艺术殿堂"},
            {"name": "浙江大学", "type": "高校参观", "price": 0, "rating": 4.4, "description": "中国顶尖大学"},
            {"name": "湘湖", "type": "自然风光", "price": 0, "rating": 4.5, "description": "西湖姊妹湖"},
        ],
    },
    "武汉": {
        "province": "湖北",
        "hotels": [
            {"name": "武汉光谷希尔顿酒店", "type": "豪华型", "price_per_night": 880, "rating": 4.7, "facilities": ["WiFi", "泳池", "健身房"]},
            {"name": "武汉户部巷青旅", "type": "经济型", "price_per_night": 69, "rating": 4.3, "facilities": ["WiFi"]},
        ],
        "restaurants": [
            {"name": "蔡林记", "cuisine": "武汉小吃", "avg_price": 15, "rating": 4.7, "specialties": ["热干面", "三鲜豆皮", "糊汤粉"]},
            {"name": "靓靓蒸虾", "cuisine": "小龙虾", "avg_price": 128, "rating": 4.6, "specialties": ["油焖大虾", "蒜蓉虾", "清蒸虾"]},
            {"name": "老通城", "cuisine": "武汉小吃", "avg_price": 25, "rating": 4.5, "specialties": ["三鲜豆皮", "谈炎记水饺"]},
            {"name": "艳阳天", "cuisine": "鄂菜", "avg_price": 88, "rating": 4.5, "specialties": ["排骨藕汤", "武昌鱼", "沔阳三蒸"]},
            {"name": "小桃园煨汤", "cuisine": "湖北菜", "avg_price": 58, "rating": 4.5, "specialties": ["煨汤", "排骨藕汤", "鸡汤"]},
            {"name": "亢龙太子酒轩", "cuisine": "鄂菜", "avg_price": 98, "rating": 4.5, "specialties": ["太子鱼", "清蒸武昌鱼", "红菜薹炒腊肉"]},
            {"name": "周黑鸭", "cuisine": "卤味", "avg_price": 35, "rating": 4.5, "specialties": ["鸭脖", "鸭翅", "鸭锁骨"]},
            {"name": "德华楼", "cuisine": "武汉小吃", "avg_price": 20, "rating": 4.4, "specialties": ["包子", "年糕", "汤圆"]},
        ],
        "attractions": [
            {"name": "黄鹤楼", "type": "历史文化", "price": 70, "rating": 4.8, "description": "江南三大名楼之一"},
            {"name": "东湖", "type": "自然风光", "price": 0, "rating": 4.7, "description": "中国最大城中湖"},
            {"name": "武汉大学", "type": "高校参观", "price": 0, "rating": 4.6, "description": "中国最美大学"},
            {"name": "户部巷", "type": "美食街区", "price": 0, "rating": 4.5, "description": "武汉早点一条街"},
            {"name": "长江大桥", "type": "城市地标", "price": 0, "rating": 4.6, "description": "万里长江第一桥"},
            {"name": "昙华林", "type": "文创街区", "price": 0, "rating": 4.5, "description": "文艺青年聚集地"},
            {"name": "汉口江滩", "type": "城市景观", "price": 0, "rating": 4.5, "description": "夜景绝美"},
            {"name": "武汉欢乐谷", "type": "主题公园", "price": 200, "rating": 4.5, "description": "华侨城主题乐园"},
            {"name": "湖北省博物馆", "type": "博物馆", "price": 0, "rating": 4.7, "description": "曾侯乙编钟"},
            {"name": "古德寺", "type": "佛教圣地", "price": 8, "rating": 4.5, "description": "异域风情寺庙"},
            {"name": "光谷步行街", "type": "购物商圈", "price": 0, "rating": 4.4, "description": "武汉最繁华商圈"},
            {"name": "东湖绿道", "type": "城市景观", "price": 0, "rating": 4.5, "description": "骑行圣地"},
            {"name": "江汉路步行街", "type": "购物商圈", "price": 0, "rating": 4.5, "description": "百年商业街"},
            {"name": "归元禅寺", "type": "佛教圣地", "price": 10, "rating": 4.4, "description": "武汉四大佛教丛林"},
            {"name": "知音号", "type": "演艺娱乐", "price": 298, "rating": 4.5, "description": "漂移式体验剧"},
        ],
    },
}


def get_extended_city_data(city: str):
    """获取扩展城市数据"""
    return EXTENDED_CITY_DB.get(city)


def get_extended_city_data(city: str):
    """获取扩展城市数据"""
    return EXTENDED_CITY_DB.get(city)
